### ISSUE TITLE
Contacts

### ISSUE THREAD

**Issue by jamesmontemagno** [xamarin/XamarinComponents#1]
Replicate Xamarin.Mobile functionality of querying each platforms contacts with a simple cross-platform API.

**Comment by jamesmontemagno** [comment]
I am currently working on this with an ETA of end of month: https://github.com/jamesmontemagno/Xamarin.Plugins/

**Comment by soroshsabz** [comment]
ITNOA

@jamesmontemagno Why this issue is closed? Did you not want to add [ContactsPlugin](https://github.com/jamesmontemagno/ContactsPlugin) to popular plugin?
