### ISSUE TITLE
Error after installing Crashlytics

### ISSUE THREAD

**Issue by jrahma** [xamarin/XamarinComponents#1006]
Hi,

I have just installed Crashlytics but now my app is not starting and throwing this error:

**/Users/jassim/Projects/Angels/Angels/Angels.Android/D8: Error: Interface com.google.firebase.iid.zzb used as super class of com.google.firebase.messaging.FirebaseMessagingService. (Angels.Android)**

Kindly help..

Thanks,
[Jassim](https://www.emiratesangels.org)

UAE Angel Investors

**Comment by moljac** [comment]
Thanks for the feedback, but I need more data 
Which Crashlytics? Version?

**Comment by moljac** [comment]
closing this one, because of lack of information and response/feedback.
