### ISSUE TITLE
29 pull requests

### ISSUE THREAD

**Issue by tranb3r** [xamarin/XamarinComponents#1010]
There are now 29 open pull requests in this repo - and counting.
I desperately need an update on #995 but nobody cares.

What's the point in moving all the library bindings into this repo if nobody maintains them ?
Who is responsible for this repo ?
What needs to be done to merge these PRs ?
How can we help ?

Guys, I'm really sorry to tag you here, but I think it's important to clarify this for the community. 
@mattleibow @Redth @moljac @jamesmontemagno @maddyleger1

**Comment by davidortinau** [comment]
@tranb3r as with all our repositories we have to prioritize our efforts in order of impact for customers. Unfortunately for libraries like these, that means they are very low on that list behind top priorities such as .NET 6, Xamarin.Forms, Xamarin.Essentials, SkiaSharp, and Android Support / Android X which currently consumes all our time.

I recommend trying the NuGets on #995 to possibly unblock yourself. https://dev.azure.com/xamarin/public/_build/results?buildId=29868&view=results

Beyond that, the best help for yourself and others wanting to use such libraries is to fork and take PRs.

**Comment by tranb3r** [comment]
Thank you @davidortinau 
I totally understand your priorities.
One remark though: forking the repo is not enough, we also have to "fork" (or duplicate) the nuget package we want to update, which - I think - is not a good practice.

**Comment by gsgou** [comment]
> Thank you @davidortinau
> I totally understand your priorities.
> One remark though: forking the repo is not enough, we also have to "fork" (or duplicate) the nuget package we want to update, which - I think - is not a good practice.

Just mentioning that as seen in https://github.com/tranb3r/securehttpclient/issues/13 forking repos can cause conflicts between packages that reference different implementations in the same project. At least some of the PRs based on popularity of some packages should be quicker addressed.
