### ISSUE TITLE
Xamarin.Azure.NotificationHubs.Android Jetpack/AndroidX

### ISSUE THREAD

**Issue by slarti-zak** [xamarin/XamarinComponents#1016]
Im seeing for the [Xamarin binding of the notification hub](https://www.nuget.org/packages/Xamarin.Azure.NotificationHubs.Android) nuget that for the newest version 1.1.1 it still has a dependency on **Xamarin.Android.Support.v7.AppCompat**.

Are there any plans to release a jetpack/androidX compatible version?

**Comment by mpodwysocki** [comment]
@mattleibow should be able to close this now with AndroidX support

**Comment by mattleibow** [comment]
Good point. The packages are out and about!
