### ISSUE TITLE
Use buildTransitive in Kotlin bindings

### ISSUE THREAD

**Issue by tranb3r** [xamarin/XamarinComponents#1017]
Kotlin bindings use .targets files.
Is there any reason not to use buildTransitive for these .targets, in order to make sure the .jar files are always propagated up to the top-level application ?

More context can be found here: https://github.com/xamarin/XamarinComponents/issues/754

**Comment by moljac** [comment]
Done.

Discussed here: https://github.com/xamarin/XamarinComponents/issues/1136#issuecomment-834470622

Closing.
