### ISSUE TITLE
Update ThreeTenABP binding to last version

### ISSUE THREAD

**Issue by 4brunu** [xamarin/XamarinComponents#1051]
Hey,

First of all, thanks for this Xamarin binding.

Could you please update the binding ThreeTenABP to support version 1.3.0?
https://github.com/JakeWharton/ThreeTenABP/releases/tag/1.3.0

Thanks

**Comment by 4brunu** [comment]
This is now published on nuget.
@antonioser @moljac thanks for your help 👍

**Comment by moljac** [comment]
np
