### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by henrikweimenhog** [xamarin/XamarinComponents#1052]
On the getting started on this github page it states: 
NotificationHub.Initialize(Application, HUB_NAME, CONNECTION_STRING);
but I assume you mean:
NotificationHub.Start(Application, HUB_NAME, CONNECTION_STRING);

**Comment by moljac** [comment]
> On the getting started on this github page it states:

Which getting started?
Sorry, but confused....

**Comment by henrikweimenhog** [comment]
hmm, I thought it was here https://github.com/Azure/azure-notificationhubs-xamarin#getting-started-with-xamarinandroid but it seems to say start() everywhere now.
