### ISSUE TITLE
ExposureNotification iOS 12.5 support

### ISSUE THREAD

**Issue by pavshr** [xamarin/XamarinComponents#1066]
Hello, 

Recently, Apple have added support of [Exposure Notification to iOS 12.5](https://developer.apple.com/documentation/exposurenotification/supporting_exposure_notifications_in_ios_12_5). 

Is there any plans to add support for it in Xamarin.iOS and XPlat cross-plarform lib and can you provide us with any timeline? Thank you.

**Comment by mattleibow** [comment]
Support for iOS 12.5 looks pretty simple at this stage. There are a few things that need to be done but I will get on it right away:
 - [ ] most code checks are for 13.5+, so these will need to change a bit
 - [ ] support for the special callback needs to be implemented

It is important to note that iOS 13.0-13.4 still won't get support for EN.

> Although iOS 13.0 to 13.4 doesn’t support Exposure Notifications, your app might still download onto devices with those versions of iOS. If that happens, present a dialog to let the user know Exposure Notifications isn’t available for their device.

I need to confirm, but it appears that only v2 notifications are available on iOS 12.5

> If you have an app that uses version 1 risk scoring and want to support iOS 12.5, consider updating to the more robust version 2 scoring.

**Comment by mattleibow** [comment]
Work started here: https://github.com/xamarin/XamarinComponents/pull/1072

**Comment by mattleibow** [comment]
I have just pushed the iOS NuGet out: https://www.nuget.org/packages/Xamarin.iOS.ExposureNotification/1.2.2-preview1

The cross-platform one is now building and I'll push that out soon.

**Comment by mattleibow** [comment]
Both PRs have been merged. The iOS version is out and the xplat API is building and will go out as soon as it completes.
