### ISSUE TITLE
Publish on nuget moshi 1.11.0

### ISSUE THREAD

**Issue by 4brunu** [xamarin/XamarinComponents#1067]
Hi,
The binding for moshi 1.11.0 was merged in https://github.com/xamarin/XamarinComponents/pull/997.
But it was never published on nuget https://www.nuget.org/packages/Square.Moshi/.
Could you please publish the version 1.11.0 to nuget?

Thanks

**Comment by moljac** [comment]
Published

https://www.nuget.org/packages/Square.Moshi/1.11.0

Please close the issue

**Comment by 4brunu** [comment]
Thanks 👍
