### ISSUE TITLE
Fix Cake Targets to ensure everything builds.

### ISSUE THREAD

**Issue by JonDouglas** [xamarin/XamarinComponents#108]
There are a few repositories that have defined a target like this:

```
var TARGET = Argument ("t", Argument ("target", "Default"));
```

Because some of these repositories do not have a `Default` task, this fails to build via the build the world-bootstrapper:

`./build.ps1`

Thus you'll get an error:

`Error: The target 'Default' was not found.`

> VS bug [#732180](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/732180)

**Comment by newky2k** [comment]
I don't think this is need now
