### ISSUE TITLE
dependencies on bintray / jCenter

### ISSUE THREAD

**Issue by atsushieno** [xamarin/XamarinComponents#1087]
jFrog has announced that bintray and jCenter are going to shut down and after that it will become impossible to resolve jar/aar dependencies from there.
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

It has huge impacts among Android developers, and that would impact XamarinComponents too. At least there are handful of build.gradle files as well as C# classes such as `Maven.csx` that are being affected.

**Comment by moljac** [comment]
Thanks a lot @atsushieno 

Will see what we can do.
