### ISSUE TITLE
Update Glide to v4.12.0

### ISSUE THREAD

**Issue by tipa** [xamarin/XamarinComponents#1098]
The Glide library was updated to 4.12.0, would be great if the bindings could be updated as well - thanks in advance!
https://github.com/bumptech/glide/releases/tag/v4.12.0

**Comment by 4brunu** [comment]
Hey, I opened https://github.com/xamarin/XamarinComponents/pull/1166 to try to fix this.

**Comment by moljac** [comment]
closing this one
