### ISSUE TITLE
ReactiveX namespace not visible

### ISSUE THREAD

**Issue by jfquarto** [xamarin/XamarinComponents#1110]
I have added the Xamarin.Android.ReactiveX.RxJava 2.2.9 NuGet package to a Xamarin Android application.
I don't see the ReactiveX namespace. The (depency) ReactiveStreams namespace is available though.
I was hoping to use the package as a replacement for the Naxam.Android.RxJava2 package because I need Java 2.2.x support and the Naxam is 2.1.x

**Comment by TomBruyneel** [comment]
Same problem here, the package doesn't seem to export anything at all.

I'm using version 3.0.0

**Comment by jfquarto** [comment]
After some modifications to the (RxJava2) metadata.xml I was able to build it without errors and use the binding dll in my application.

[Metadata.txt](https://github.com/xamarin/XamarinComponents/files/6130465/Metadata.txt)

**Comment by TomBruyneel** [comment]
@jfquarto I needed rxjava3 (to make bindings for the polar sdk) so I decided to "quickly" make my own library. Far from perfect, but at least it allows using Observable and Flowable

https://github.com/TomBruyneel/Android.RxJava

Is there a reason the library in XamarinComponents is that crippled? I realize there is no real reason to ever use ReactiveX java classes in c#. However, when trying to use another library that publicly exports some functions returning a ReactiveX class, this Xamarin library will just not do.

**Comment by TomBruyneel** [comment]
@moljac would it be okay if I further flesh out the rxjava component and make the classes available to c#? I could base it on your rxjava-2.2.10 branch which has not yet been merged and create a pull request after. It would really be beneficial for me in a project and I would like to keep using the Xamarin.Android.... packages instead of rolling out my own.

**Comment by moljac** [comment]
Started bindings from scratch. Seems like some `remove-node` metadata caused isuess.

**Comment by TomBruyneel** [comment]
@moljac if you look at my repository above, with that code it compiles and the completable, flowable and subscriber classses can be used

**Comment by moljac** [comment]
@TomBruyneel @jfquarto 

Guys please test new bindings. New round will be published in hour or two, just waiting for CI.

**Comment by TomBruyneel** [comment]
@moljac looks ok! sorry for the late response, I had some holidays. Thanks!

**Comment by moljac** [comment]
@TomBruyneel 
No problems at all. I hope you enjoyed it. Thanks for the feedback.
