### ISSUE TITLE
Please update Kotlin StdLib NuGet package

### ISSUE THREAD

**Issue by humblehacker** [xamarin/XamarinComponents#1136]
The latest version of the [Kotlin StdLib Nuget is 1.4.20](https://www.nuget.org/packages/Xamarin.Kotlin.StdLib/1.4.20), last updated 5 months ago. Since then, versions [1.4.21](https://mvnrepository.com/artifact/org.jetbrains.kotlin/kotlin-stdlib/1.4.21), [1.4.30](https://mvnrepository.com/artifact/org.jetbrains.kotlin/kotlin-stdlib/1.4.30), [1.4.31](https://mvnrepository.com/artifact/org.jetbrains.kotlin/kotlin-stdlib/1.4.31), [1.4.32](https://mvnrepository.com/artifact/org.jetbrains.kotlin/kotlin-stdlib/1.4.32), and [1.5.0](https://mvnrepository.com/artifact/org.jetbrains.kotlin/kotlin-stdlib/1.5.0) of the native Android library have been released. Please consider updating this NuGet package to one or more of these available versions.

**Comment by humblehacker** [comment]
@jpobst fyi, I was asked to post this on `xamarin/xamarin-android` by @Redth. Should I post future requests for Nuget updates here instead?  I have quite a few more of these requests to make.

**Comment by jpobst** [comment]
Unfortunately, the code for the various Xamarin Nugets is spread all over the place.

AndroidX: https://github.com/xamarin/AndroidX
GooglePlayServices/Firebase: https://github.com/xamarin/GooglePlayServicesComponents
Facebook Components: https://github.com/xamarin/FacebookComponents

And then this repository is just kinda "everything else", which happens to include Kotlin Stdlib.  :wink: 
https://github.com/xamarin/XamarinComponents/tree/master/Android/Kotlin

**Comment by tranb3r** [comment]
Updating this package could also be the opportunity to fix the following issue:
https://github.com/xamarin/XamarinComponents/issues/1017

**Comment by 4brunu** [comment]
I also need this.
Could you please update kotlin to version 1.5.0?

**Comment by tranb3r** [comment]
@moljac 
I see you've opened new PRs for kotlin update.
Could you please fix the buildTransitive issue mentionned here #1017 and here #754 before publishing new nugets ?
Thanks.

**Comment by moljac** [comment]
@tranb3r 

seems like it has already been done:

```
  <ItemGroup>
    <None Update="@(Model.NuGetPackageId).targets" Pack="True" PackagePath="build\$(TargetFramework)" />
    <None Update="@(Model.NuGetPackageId).targets" Pack="True" PackagePath="buildTransitive\$(TargetFramework)" />
  </ItemGroup>
```

see for PR kotlin-1.4.21 (https://github.com/xamarin/XamarinComponents/pull/1140):

https://github.com/xamarin/XamarinComponents/blob/kotlin-1.4.21/Android/Kotlin/source/Project.cshtml#L61-L64

That should be OK. Or am I wrong?

**Comment by tranb3r** [comment]
> That should be OK. Or am I wrong?

@moljac 
Yes, I think this is OK.
I'm a bit surprised the corresponding issues have not been closed...
But the important thing is that the fix is done for the future releases.
Thank you.

**Comment by moljac** [comment]
> I'm a bit surprised the corresponding issues have not been closed...

This repo used to be maintained by 5+ people. Today I am only for Android stuff needed for AndroidX and GPS-FB-MLKit. I must have been missed closing the issue (I did not add buildTransitive, so I did not know it was fixed). Sorry

**Comment by moljac** [comment]
Published.

Closing this issue.

thanks
