### ISSUE TITLE
Update to Google Play Billing Library v3.0.3

### ISSUE THREAD

**Issue by Sevenish** [xamarin/XamarinComponents#1171]
It contains some bug fixes compared to 3.0.0 

Google is forcing apps to update from version 2 by november 2021. Would be nice to have the latest version with bugfixes

**Comment by tipa** [comment]
Google now even released v4.0.0 - would be great if the bindings could get updated!

**Comment by AntRemo** [comment]
Hi @moljac 

Are there any plans to upgrade soon?

Many thanks 🙏
