### ISSUE TITLE
Plugin listing request (Clipboard)

### ISSUE THREAD

**Issue by stavroskasidis** [xamarin/XamarinComponents#118]
Hello,
I have created a plugin for cross platform access to the clipboard. I used the visual studio templates for the projects and I think it qualifies. 
I have also created a pull request ( #106 ) that adds it to the list.

NuGet: https://www.nuget.org/packages/Xamarin.Plugins.Clipboard/

Thank you

**Comment by jamesmontemagno** [comment]
This is included in the share plugin today.
