### ISSUE TITLE
Plugin for Cross-Platform Audio Playback

### ISSUE THREAD

**Issue by deckertron9000** [xamarin/XamarinComponents#12]
Referencing old issue jamesmontemagno/Xamarin.Plugins#73 to create a plugin for cross-platform audio support.

**Comment by SimonSimCity** [comment]
Anyone interested? I have a project, where I soon need something the-like. @deckertron9000 do you have a technical design about how the interfaces could look like?

If no-one ever did something like this, I'll kick it off. Please let me know if there are major design-differences on the different platforms. I'll focus on iOS and Android.

**Comment by shuaihuadu** [comment]
Anyone implemented?

**Comment by SimonSimCity** [comment]
Got the following reference lately: https://github.com/Clancey/gMusic (@clancey)

**Comment by SimonSimCity** [comment]
Found another reference: https://github.com/martijn00/XamarinMediaManager (@martijn00)

**Comment by jamesmontemagno** [comment]
Closing as Martijn's has been added and under active development
