### ISSUE TITLE
Why has the link to CrossDownloadManager been removed?

### ISSUE THREAD

**Issue by SimonSimCity** [xamarin/XamarinComponents#121]
I just recognized, that the link to my library CrossDownloadManager got removed here in the following commit: https://github.com/xamarin/XamarinComponents/commit/8906425b7a741ee670089d4249a89c06517d04aa

Is there a specific reason for removing it, or do you just not want this list to grow extremely large as time goes by?

**Comment by newky2k** [comment]
Hi @SimonSimCity, i don't know why exactly this was removed, but the whole section of additional plugins was removed so the team may have just wanted to focus on the ones in the repo itself.
