### ISSUE TITLE
Xamarin.Build.Download.targets - invalid Id

### ISSUE THREAD

**Issue by endarea** [xamarin/XamarinComponents#1248]
I cannot build the project after adding Xamarin.Firebase.Functions nuget (v120.0.0) . The error message is:
```
Xamarin.Build.Download.targets(3,3): Error XBD020: Invalid item ID firebaseappcheckinterop-16.0.0-beta01 
```
What can it be? I already tried the usual things like deleting the bin/obj folders, rebuilding, restarting, installing different versions of Xamarin.Build.Download. No idea where to even start investigating this issue.

**Comment by AdamEssenmacher** [comment]
I didn't see this issue before opening up a duplicate: https://github.com/xamarin/XamarinComponents/issues/1293

**Comment by jpobst** [comment]
This should be fixed in https://github.com/xamarin/XamarinComponents/pull/1384.
