### ISSUE TITLE
[Xamarin.Build.Download:0.4.2] [Urgent] Clean Visual studio 2017 FINAL installation -> Could not find 7zip.exe in Xamarin installation

### ISSUE THREAD

**Issue by andreabellitto** [xamarin/XamarinComponents#125]
If you try to use a clean installation of Visual studio 2017, on a JUST INSTALLED CLEAN system, `Xamarin.Build.Download` fails with message `Could not find 7zip.exe in Xamarin installation` from the method `Get7ZipPath()`.

It is because on a clean system, Windows registry key for xamarin and visual studio 2017 FINAL are completely different, and so `Get7ZipPath()` method needs to be updated to find the new correct path that is

`C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\Extensions\Xamarin.VisualStudio\7-Zip\7z.exe`

instead of reach the end of the method where

`throw new Exception("Could not find 7zip.exe in Xamarin installation")`

instruction is called.

EDIT:
This is my windows registry content in relevant key for this case:

[Xamarin.reg.txt](https://github.com/xamarin/XamarinComponents/files/828427/Xamarin.reg.txt)
[VisualStudio.reg.txt](https://github.com/xamarin/XamarinComponents/files/828442/VisualStudio.reg.txt)

**Comment by JKennedy24** [comment]
I'm also seeing this issue with latest Xamarin and VS2017

**Comment by newky2k** [comment]
@andreabellitto @JKennedy24  this should be resolved by the latest version which is now at 0.4.11

**Comment by evgenyvalavin** [comment]
Installing 7zip on my computer helped. Xamarin.Build.Download searches for 7Zip in Program Files and other directories under the hood

**Comment by jpsheehan** [comment]
For some reason, Xamarin suddenly wasn't able to find my locally installed version of 7zip anymore. To fix this I set the following MSBuild property in Rider: `XamarinBuildDownloadUser7ZipPath` = `C:\Program Files\7-Zip\7z.exe`. This solved the issue for me.
![image](https://github.com/user-attachments/assets/70be9c01-4b95-435f-9e82-456a73ee2e3a)
