### ISSUE TITLE
Cannot register for telemetry notifications from Estimote SDK. Possibly a problem with the bindings?

### ISSUE THREAD

**Issue by MatthewGerber** [xamarin/XamarinComponents#132]
This iOS issue was reported over in the Xamarin Forums:

https://forums.xamarin.com/discussion/80445/cannot-register-for-telemetry-notifications-from-estimote-sdk-possibly-a-problem-with-the-bindings

Any ideas on how to resolve it?

**Comment by MatthewGerber** [comment]
@jamesmontemagno This probably isn't your component, but can you help me with this issue? I think it's a problem with the bindings in the iOS NuGet. Thoughts?

**Comment by MatthewGerber** [comment]
@jamesmontemagno Actually, this does look like your component, at least judging from the Xamarin Blog [article](https://forums.xamarin.com/discussion/33779) you wrote. Should we expect a response on this, or should we find alternative solutions? As it stands, we can't seem to get telemetry data (acceleration and temperature) from Estimote Beacons. It seems like it might just be a simple issue with the bindings.

**Comment by MatthewGerber** [comment]
@jamesmontemagno Any thoughts? We'd really like to get telemetry (acceleration and temperature) data from our Beacons, but the bindings don't seem to support these.

**Comment by newky2k** [comment]
@MatthewGerber  we have pushed out a new version since the last update which may resolve this.  if not there is this -> https://github.com/Estimote/Xamarin-Bindings/
