### ISSUE TITLE
Error in sample code ?

### ISSUE THREAD

**Issue by teoshinjiat** [xamarin/XamarinComponents#137]
https://github.com/xamarin/XamarinComponents/blob/master/XPlat/Estimote/Android/component/GettingStarted.md
`_region = this.GetBeaconAndRegion().Item2;`

I'm getting red underlined on 'Item2', the error is
`"object does not contain a definition for 'Item2' and no extension method 'Item2' accepting a first argument of type 'object' could be found(are you missing a using directive or an assembly reference?)"`

**Comment by newky2k** [comment]
The sample in the last PR for estimote uses the same code and compile correctly so this should be resolved now
