### ISSUE TITLE
Update Xamarin.Android.Google.BillingClient bindings to v5.0.0

### ISSUE THREAD

**Issue by tipa** [xamarin/XamarinComponents#1375]
[Google Play Billing Library version 5.0.0 has been released](https://developer.android.com/google/play/billing/migrate-gpblv5).
An update to the bindings would be much appreciated! :)

**Comment by daniel-schneider** [comment]
seconded

**Comment by vladik1337228** [comment]
I managed to integrate Google.Play.Billing 5 into the xamarin.

**Comment by EmilAlipiev** [comment]
yes please

**Comment by vecalion** [comment]
@vladik1337228, can you please share your solution?

**Comment by tipa** [comment]
It's theeeere, thanks a lot!
