### ISSUE TITLE
Floating Search View error when textview has focus

### ISSUE THREAD

**Issue by vhugogarcia** [xamarin/XamarinComponents#138]
Hello friends,

I'm trying to make the demo to run on a Xamarin.Android project, however I got an error when I tap on the textview and it gets the focus.
Didn't find class "com.bartoszlipinski.viewpropertyobjectanimator.ViewPropertyObjectAnimator" on path: DexPathList[[zip file "/data/app/com.vh.vandroidfloatingsearchview-1/base.apk"],nativeLibraryDirectories=[/data/app/com.vh.vandroidfloatingsearchview-1/lib/x86_64, /system/fake-libs64, /data/app/com.vh.vandroidfloatingsearchview-1/base.apk!/lib/x86_64, /system/lib64, /vendor/lib64]]

Any idea what could the issue be?

Note: I'm using the same code found on this repository, however I compiled a new version of the original JAVA library and updated the Support versions to 25.1.1

Thanks in advance

**Comment by newky2k** [comment]
@vhugogarcia  The build system use Cake to download and install the jar dependecies so you need to make sure this is run first before building or running the sln files.  This may be why the binding can't locate the classes.
