### ISSUE TITLE
Stuck at Card entry Page on iOS 10.3

### ISSUE THREAD

**Issue by wal33d006** [xamarin/XamarinComponents#152]
As I navigate to the manual card entry page, the "cancel" and "done" buttons of the card entry screen don't work. I have used breakpoints in my code. Even the handlers aren't called on the button clicks.
After the card details are entered, the "done" button doesn't work and the cancel button crashes the application.
![whatsapp image 2017-05-15 at 4 46 16 pm](https://cloud.githubusercontent.com/assets/25613623/26056327/46ae36d8-398e-11e7-99b9-5f80b9307c08.jpeg)
![whatsapp image 2017-05-15 at 4 46 17 pm](https://cloud.githubusercontent.com/assets/25613623/26056328/46f6feb8-398e-11e7-9521-025c2cdd9e59.jpeg)

**Comment by wal33d006** [comment]
@Redth Can you please look into this.
Thanks

**Comment by wal33d006** [comment]
@bholmes @mattleibow 
Can you guys please look into this as well
I am stuck at this since last week

**Comment by bholmes** [comment]
Can you please specify which component is giving the problem.  Is this CardIO?

**Comment by wal33d006** [comment]
@bholmes Yes

**Comment by Redth** [comment]
@wal33d006 does the sample work for you?  It's working fine for me, I'm unable to reproduce the crash, or the Camera/Done buttons not working.

**Comment by jeremymarabel** [comment]
hi @wal33d006 @bholmes ,
I ran into the same issue and found this post. it's a CardIO issue
My app don't crash, but i'm stuck into that screen. It's a bit tricky to reproduce, here are the steps :

_Take a card hard to read (erased numbers or something) or simply hide some numbers with your finger
_Try to scan the credit card (the all square must be green) 
_While the component try to scan, click on the cancel button

You should now be stuck in the card scanner. 

Hope this can be fixed, thank you in advance

**Comment by wal33d006** [comment]
@jeremymarabel 
My screen also stucks there
the buttons don't work at all
Sometimes it crashes and sometimes it doesn't

**Comment by Redth** [comment]
@jeremymarabel and @wal33d006 please try the sample located here: https://github.com/xamarin/XamarinComponents/tree/master/XPlat/CardIO/iOS/samples

I still can't reproduce the issue.

Also, if you can share some code to show how you're using Card.IO that would help.  I tried the steps of trying to read a card with missing numbers and pressing cancel when the square was all green.  It works fine here :/

**Comment by crs2m5smith** [comment]
Has anyone resolved this issue? I am implementing this with Xamarin Forms and ran into same issue with buttons not firing.

**Comment by newky2k** [comment]
@crs2m5smith Could you provide a sample project and further details about the version of iOS etc that you are using

**Comment by crs2m5smith** [comment]
@newky2k  I was actually able to resolve this for me. I will post code below. Issue turned out to move the delegate scope with the PageRenderer class and not creating new instance of it on ViewDidAppear
`    public class CardIORenderer : PageRenderer
    {
        private bool bViewAlreadyDisappeared = false;
        private CardIOPage cardIOPage;
        private CardIOPaymentViewControllerDelegate cardIOPaymentViewControllerDelegate;
        public CardIORenderer()
        {

        }
        protected override void OnElementChanged(VisualElementChangedEventArgs e)
        {
            base.OnElementChanged(e);
            cardIOPage = e.NewElement as CardIOPage;
        }
        public override void ViewDidAppear(bool animated)
        {
            base.ViewDidAppear(animated);

            if (bViewAlreadyDisappeared) return;

            cardIOPaymentViewControllerDelegate = new CardIOPaymentViewControllerDg(cardIOPage);

            // Create and Show the View Controller
            var paymentViewController = new CardIOPaymentViewController(cardIOPaymentViewControllerDelegate, true);

            paymentViewController.AllowFreelyRotatingCardGuide = false;
            Device.BeginInvokeOnMainThread(() =>
            {
                var window = UIApplication.SharedApplication.KeyWindow;
                var vc = window.RootViewController;
                while (vc.PresentedViewController != null)
                {
                    vc = vc.PresentedViewController;
                }
                // Display the card.io interface
                vc.PresentViewController(paymentViewController, true, null);
            });
        }
        public override void ViewDidDisappear(bool animated)
        {
            base.ViewDidDisappear(animated);
            bViewAlreadyDisappeared = true;
        }
    }
    public class CardIOPaymentViewControllerDg : CardIOPaymentViewControllerDelegate
    {
        private CardIOPage cardIOPage;
        private CardIOCard cardIOCard = new CardIOCard();
        public CardIOPaymentViewControllerDg(CardIOPage page)
        {
            cardIOPage = page;   
        }
        public override void UserDidCancelPaymentViewController(CardIOPaymentViewController paymentViewController)
        {
            // do cancel
        }

        public override void UserDidProvideCreditCardInfo(CreditCardInfo card, CardIOPaymentViewController paymentViewController)
        {
            if (card == null)
               // do error
            else
            {
                //do work
            }
        }
    }`

**Comment by wal33d006** [comment]
@newky2k ^ Check this one.

**Comment by Redth** [comment]
Thanks for following up 🥇
