### ISSUE TITLE
CS0246	The type or namespace name 'GSResponse' could not be found (are you missing a using directive or an assembly reference?)	GigyaSDK.Android

### ISSUE THREAD

**Issue by santoshpatro** [xamarin/XamarinComponents#156]
I am trying to build the Gigya components for the solution: GigyaSDK.Android.sln and getting an error related to the GSResponse assembly. Also I see there is no reference to the Gigya SDK. Can anyone help me to fix this issue. Any blogs or articles on  Gigya integration with Xamarin is much appreciated.

**Comment by ASN1234** [comment]
Hi. I am also facing same issue.
Were you able to find a solution for your problem?

**Comment by ASN1234** [comment]
Here is what worked for me...
1) Downloaded the latest Android SDK for Gigya (JAR) from Gigya website.
2) Copy the JAR to the "Jars" folder in the "GigyaSDK.Android" project and set its BuildAction as "EmbeddedJar".
3) Update the entire solution with the latest Xamarin packages from NuGet.

Hope this helps.

**Comment by santoshpatro** [comment]
Thanks a lot for the help

**Comment by newky2k** [comment]
@santoshpatro  You need use the build.cake first as this downloads all neccesary files to allow the solution compile correctly, including the jar files
