### ISSUE TITLE
Missing .jar files

### ISSUE THREAD

**Issue by BrunoVT1992** [xamarin/XamarinComponents#161]
When I try to build the GoogleVr binding library there are missing classes.jar files in every project. Where can I find these?

Or where can I download a nuget package for this?

**Comment by PhilippeTroller** [comment]
up

**Comment by newky2k** [comment]
@BrunoVT1992  have you tried building via cake first, which downloads the jar files first?

**Comment by newky2k** [comment]
No response from the original poster
