### ISSUE TITLE
Attempting to read RSSI for eddystone causes SIGSEGV error

### ISSUE THREAD

**Issue by ghost** [xamarin/XamarinComponents#164]
Hello,

When I attempt to read the rssi value for an eddystone, I get a SIGSEGV error:

Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.

Here is how I am attempting to use it in code:

var rssi = e.Eddystones.First().Rssi;

Thanks!

**Comment by newky2k** [comment]
User no long exists
