### ISSUE TITLE
Error compiling OpenID Android app

### ISSUE THREAD

**Issue by riyadparvez** [xamarin/XamarinComponents#168]
I'm trying to compile OpenId Android sample app. But I keep getting the following error:

> 'AuthorizationService' does not contain a definition for 'CreateCustomTabsIntentBuilder' and no extension method 'CreateCustomTabsIntentBuilder' accepting a first argument of type 'AuthorizationService' could be found (are you missing a using directive or an assembly reference?)

**Comment by newky2k** [comment]
The OpenId packages were updated 3 months ago, and  they should resolve you issue
