### ISSUE TITLE
Please provide NuGet packages from free components

### ISSUE THREAD

**Issue by sdebruyn** [xamarin/XamarinComponents#169]
We were trying to use a component ( https://components.xamarin.com/view/jsqmessagesviewcontroller ) but some of the developers in our team have issues with authentication in to Xamarin Components Store in Visual Studio. I understand that components is more of a deprecated way of publishing packages. Is it possible to publish this component and maybe others as a NuGet package?

**Comment by newky2k** [comment]
hi @SamuelDebruyn,

We have moved JSQMessagesViewController to the public repo and published it to nuget

https://www.nuget.org/packages/Xamarin.JSQMessagesViewController/

You can see, and contribute to the code, here
https://github.com/xamarin/XamarinComponents/tree/master/iOS/JSQMessagesViewController

Thanks
