### ISSUE TITLE
Mono.Options should support handling commands

### ISSUE THREAD

**Issue by lostmsu** [xamarin/XamarinComponents#174]
E.g. something like
```csharp
var commonOptions = new OptionSet(...);
var readOptions = new OptionsSet(commonOptions, ...);
var writeOptions = new OptionsSet(commonOptions, ...);
var commandLineOptions = new OptionSet({ read = readOptions, write = writeOptions });
var ... = commandLineOptions.Parse(args);
```

**Comment by mattleibow** [comment]
I am not sure what you are asking here. Could you expand on this a bit further?

**Comment by lostmsu** [comment]
@mattleibow I think there's currently no way to implement multiple commands in the same app like git does for example. e.g. git commit _commit-options_, git fetch _fetch-options_, etc.

**Comment by mattleibow** [comment]
This probably will be addressed after updating the version of mono.options: #418 
This includes the commit: https://github.com/mono/mono/commit/c1b9fc566a365cf6923218eae9098d0fd0e632ae which is basically what is being requested here.

**Comment by newky2k** [comment]
This has now been resolved and merged in to the master
