### ISSUE TITLE
Plugin for Cross-Platform REST Requests

### ISSUE THREAD

**Issue by alesvi** [xamarin/XamarinComponents#18]
I started this new plugin:

https://github.com/alesvi/Xamarin.Plugins.RestClient

The idea is create all the methods I find useful to send requests to REST APIs. 

Any opinions or ideas will be appreciated.

**Comment by SimonSimCity** [comment]
@alesvi Just out of interest ... what is your reason for not using the C# webservice?

**Comment by maiersoft** [comment]
Also just out interest: Why not use Refit?
https://github.com/paulcbetts/refit
