### ISSUE TITLE
Card.io for Android  doesn't work on v 7.1

### ISSUE THREAD

**Issue by ysavit** [xamarin/XamarinComponents#204]
I compiled and run sample project on my sumsung s8 with **v7.1** - doesn't work. Card is not parsed
Tried on older Marshmallow phone. Works fine.
 Any idea why?

**Comment by newky2k** [comment]
@ysavit  Can you try on the current version and see if the issue is still there?

**Comment by newky2k** [comment]
Closed as no further information after two weeks
