### ISSUE TITLE
ttl for iOS.SimplePing

### ISSUE THREAD

**Issue by bill2004158** [xamarin/XamarinComponents#217]
normally, the output of ping command is:
`64 bytes from 111.13.101.208: icmp_seq=2 ttl=128 time=52.169 ms`

however, it seem SimplePing removed the IP header from received package: https://github.com/xamarin/XamarinComponents/blob/master/iOS/SimplePing/externals/SimplePing/Common/SimplePing.m#L408

the value ttl is in IP header.
if removed the header,
so how can we get the ttl value?

**Comment by jamesmontemagno** [comment]
This is specifically from Apple's implementation for pinging: https://developer.apple.com/library/content/samplecode/SimplePing/Listings/Common_SimplePing_m.html#//apple_ref/doc/uid/DTS10000716-Common_SimplePing_m-DontLinkElementID_4

**Comment by newky2k** [comment]
hi @bill2004158 we just published an update to SimplePing, can you see if this resolves the issue for you
