### ISSUE TITLE
Plugin icon template

### ISSUE THREAD

**Issue by aloisdeniel** [xamarin/XamarinComponents#22]
Could it be possible to have an icon template and associated guidelines for it in order to have uniformized plugins icons ?

Many plugins from @jamesmontemagno have a [blue background](http://www.refractored.com/images/external_map_icon.png), and I've recreated the background template myself, but an official one could be great for everybody : with this a quick look into NuGet package explorer allows us to quickly identify all the plugins.

**Comment by jamesmontemagno** [comment]
Yup, take a look here: https://github.com/jamesmontemagno/Xamarin-Templates/tree/master/Plugins-Templates/icons
