### ISSUE TITLE
Occurring <InvalidCastException> "Media" property in Message

### ISSUE THREAD

**Issue by iroas2** [xamarin/XamarinComponents#227]
I couldn't get the media object eventhough "IsMediaMessage" is "true". It occured <InvalidCastException> what I appended "VideoMediaItem" object..

![screenshot 2017-09-08 17 40 27](https://user-images.githubusercontent.com/23700620/30203372-dd253790-94bc-11e7-8704-db1d03903c6b.png)

**Comment by newky2k** [comment]
@iroas2  JSQMessagesViewController was updated a month ago.  Hopefully this will resolve your issue.
