### ISSUE TITLE
Sample not working on Samsung S8 

### ISSUE THREAD

**Issue by jinalmakwana16** [xamarin/XamarinComponents#236]
Hi There,

I am trying to run this sample code on my Samsung S8, it doesn't find any beacon. Can you please help me what am I missing? I am new to Xamal and Mobile development.

**Comment by mattleibow** [comment]
Hi @jinalmakwana16, what sample is this? There are quite a few in this repo.

**Comment by jinalmakwana16** [comment]
Hi Mattleibow,

It was trying to run XamarinComponents/XPlat/Estimote/Android/ it is not finding any beacons at all.

**Comment by newky2k** [comment]
@jinalmakwana16  Have you managed to fix this issue?

**Comment by newky2k** [comment]
Closing as no repsonse
