### ISSUE TITLE
[XPlat.RadialProgress] It's hard to customize...

### ISSUE THREAD

**Issue by kenny128** [xamarin/XamarinComponents#243]
I'm not sure if it was the intention for the component to be the way it is and not be customizable, if that's the case I'm using it very wrong and terribly sorry for opening the issue in the first place.

What I was trying to do is to change the text on the RadialProgressView to a TextView so i can get it to wrap text and dynamically change font size. I wanted to create a custom RadialProgressView that inherited the base one but many of its variables are not protected and are inaccessible due to it being private. Some the variables I'm most interested in are the radius and progressType, 

I'm current doing this on the Android RadialProgressView but i foresee this being also an issue on the iOS version. 

Maybe I'm probably even going at this idea in the wrong direction. If someone can advice me in the right direction it would be incredibly helpful.

**Comment by newky2k** [comment]
@kenny128  You can create a PR to implement any changes that you want.  We can then review and merge it and allow you to customise it in the way that you want
