### ISSUE TITLE
SlackTextViewController broke with iOS 11, needs emergency patch

### ISSUE THREAD

**Issue by softwaremills** [xamarin/XamarinComponents#244]
The iOS component SlackTextViewController broke in iOS 11. The devs checked in an emergency patch to slackhq/SlackTextViewController, but they've been working on a bunch of other stuff getting it ready for an official release. Meanwhile, it's been a month since iOS 11 dropped, with no official release in sight, and the devs said basically "look, just set your Podfile to source from the checkin instead of the latest version, and you'll be fine."

I've been trying to get Objective Sharpie to work for me, but overall, I'm just finding it difficult getting this thing working. The current XamarinComponents project has a bunch of .a files for different ABIs, but the Xcode project spits out .framework files, and I've been trying to get stuff working, but I'm no expert here.

Anyway, this means a key feature of our iOS app is dead in the water. I hate to complain about something free, but help? Please?

**Comment by softwaremills** [comment]
Thread of the pull request with comments from people testing:
https://github.com/slackhq/SlackTextViewController/pull/624

Main dev comment: "If you are using Cocoapods or Carthage, you can checkout to a specific commit or branch. You don’t need a release to be able to update anyway."
https://github.com/slackhq/SlackTextViewController/issues/607#issuecomment-333606448

**Comment by newky2k** [comment]
This has now been fixed with #246 and has been pushed and published
