### ISSUE TITLE
Mapbox iOS - GetVisibleFeatures returns an abstract class

### ISSUE THREAD

**Issue by krabil-gcs** [xamarin/XamarinComponents#250]
The GetVisibleFeatures (both AtPoint and InRect) methods return an abstract class (Feature[]) which fails to be instantiated when run.  These two examples both fail with the message _"Cannot create an instance of Mapbox.Feature because it is an abstract class"_.  

`Feature[] features =  mapView.GetVisibleFeaturesInRect(mapView.Bounds);`
`var features =  mapView.GetVisibleFeaturesInRect(mapView.Bounds);`

Attempting to cast the return value doesn't work either. The following throws the error _"Error: Cannot convert type 'Mapbox.Feature[]' to 'Mapbox.PointFeature[]'"._

`PointFeature[] features = (PointFeature[]) mapView.GetVisibleFeaturesInRect(mapView.Bounds);`

I am admittedly new to Xamarin, but this seems to be the way to get features from a MapView based on my experience with Mapbox native iOS SDK.  I was unable to find other git issues mentioning this, but I did see someone mention the problem in the review section of the Xamarin Mapbox SDK:

![mapbox_ios_error](https://user-images.githubusercontent.com/33268886/32252302-6bab281e-be5a-11e7-8255-0359cd7943f0.png)

I am using Visual Studio for Mac 7.2.2, macOS 10.12.6 (High Sierra), targeting iOS version 11.03
I can provide more information if needed.

**Comment by Redth** [comment]
We have deprecated our bindings for Mapbox and have delisted the existing NuGet packages for them.

Please see the [README](https://github.com/xamarin/XamarinComponents/blob/master/XPlat/Mapbox/README.md) for more information.
