### ISSUE TITLE
Error building YouTubePlayerSample for iOS

### ISSUE THREAD

**Issue by danielcrenna** [xamarin/XamarinComponents#257]
I assume this has to do with Cocoapods but can't find documentation to get this restore. I'm using latest XamarinStudio and/or latest VisualStudio Mac on a fresh clone.

I also assume there is a process similar to git submodule installation for cocoapods but don't know where to begin with that.

/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/iOS/Xamarin.iOS.ObjCBinding.Common.targets: Error:   Bundle Resource 'Assets.bundle/Assets/YTPlayerView-iframe-player.html' not found on disk (should be at '/Users/[USER]/src/XamarinComponents/XPlat/YouTube.Player/ios/externals/Pods/youtube-ios-player-helper/youtube-ios-player-helper/Assets.bundle/Assets/YTPlayerView-iframe-player.html') (YouTube.Player.iOS)

**Comment by newky2k** [comment]
@danielcrenna Have you tried this lately.  Additionally you have to use the build.cake to download and build the external deps before you can build the source and samples.  

Also we have now published this on nuget -> https://www.nuget.org/packages?q=+Xamarin.YouTube.Player
