### ISSUE TITLE
Xamarin.Forms Portable Solution is very slow

### ISSUE THREAD

**Issue by reader-man** [xamarin/XamarinComponents#26]
Hi, 
 making a "blank app Xamarin.Forms Portable" solution, will take a long time for a blank project to finish doing all the inner projects.

also, closing the solution and re-opening it, takes a long time.

lastly, the compiling of the blank project in debug/release takes a very long time.

Regards.

**Comment by reader-man** [comment]
This issue has been submitted to bugzilla.xamarin:
https://bugzilla.xamarin.com/show_bug.cgi?id=41059

**Comment by jamesmontemagno** [comment]
Thank you for creating the bugzilla and it will be tracked through there.
