### ISSUE TITLE
Made a few plugins, any interest in adding them to the list?

### ISSUE THREAD

**Issue by AnthroHeader** [xamarin/XamarinComponents#261]
I have made a few plugins while learning Xamarin:

[File system](https://github.com/Aftnet/FileSystemPlugin) - A replacement for [PCLStorage](https://github.com/dsplaisted/PCLStorage) with extra functionality, such as support for sandboxing compliant file pickers on UWP/Windows desktop/macOS.
[OAuth2](https://github.com/Aftnet/OAuth2Plugin) - OAuth2 and OpenID connect sign in, creates web browser modal view to handle auth code flow, manages token validity and storage as needed
[Secure storage](https://github.com/Aftnet/SecureStoragePlugin) - reimplemented https://github.com/sameerkapps/SecureStorage to support .net standard, more platforms and use each platform's native keychains instead of encrypted files on disk.

All of them are .net standard and support iOS/Android/UWP/macOS/Windows Desktop.

**Comment by newky2k** [comment]
Hi @albertofustinoni  we have shifted focus to Xamarin Essentials now instead of the current plugins system.    Here is a list of the current features, https://github.com/xamarin/Essentials/wiki/Feature-Support, and it would amazing if you were able to contribute.
