### ISSUE TITLE
Can't install Xamarin.AndroidSwipeLayout

### ISSUE THREAD

**Issue by MagnusJohansson** [xamarin/XamarinComponents#269]
When trying to install the Xamarin.AndroidSwipeLayout Nuget package v1.2.0.1, I get this error:

Attempting to gather dependency information for package 'Xamarin.AndroidSwipeLayout.1.2.0.1' with respect to project 'DroidApp4', targeting 'MonoAndroid,Version=v8.0'
Gathering dependency information took 3.41 sec
Attempting to resolve dependencies for package 'Xamarin.AndroidSwipeLayout.1.2.0.1' with DependencyBehavior 'Lowest'
**Unable to resolve dependency 'Android.Support.v7.RecyclerView'. Source(s) used: 'nuget.org', 'Microsoft Visual Studio Offline Packages'**.
Time Elapsed: 00:00:03.5753021
========== Finished ==========

VS 2017 15.5.1, new empty Android app, then 
>Install-Package Xamarin.AndroidSwipeLayout -Version 1.2.0.1

Manually  installing the 2 dependencies:
Xamarin.Android.Support.v4 
Android.Support.v7.RecyclerView 

Doesn't help either.

**Comment by MagnusJohansson** [comment]
Created a PR #276  with a fix

**Comment by mattleibow** [comment]
Thanks for submitting the PR. A release has been published: https://www.nuget.org/packages/Xamarin.AndroidSwipeLayout/1.2.0.2
