### ISSUE TITLE
Change File System Plugin

### ISSUE THREAD

**Issue by antonioseric** [xamarin/XamarinComponents#27]
You should change File System Plugin to [https://github.com/Aragas/PCLExt.FileStorage](https://github.com/Aragas/PCLExt.FileStorage)
Since current one is very old and doesn't work on Android KitKat and up

**Comment by jamesmontemagno** [comment]
I would recommend working to send a PR down to the original repo as I haven't had any issues with PCL storage at all.

**Comment by Binnette** [comment]
Hi, can somebody please take care of this plugin https://github.com/dsplaisted/PCLStorage ?
It has many issues and some PR. But nobody to maintain it.
Thank you :heart:

**Comment by Binnette** [comment]
Hi, if you want a .NET Standard Storage plugin, please vote here 👍 👍 👍 
https://xamarin.uservoice.com/forums/144858-xamarin-platform-suggestions/suggestions/32307739-create-a-net-standard-storage-plugin-for-xamarin

**Comment by newky2k** [comment]
Hi,

Xamarin Essentials has a file system Api that may be suitable for your needs

https://github.com/xamarin/Essentials/wiki/Feature-Support

Regards

**Comment by jamesmontemagno** [comment]
And on top of the System.IO is in .NET Standard 2.0! No need for PCL Storage
