### ISSUE TITLE
Google Firebase Support 

### ISSUE THREAD

**Issue by sirinath** [xamarin/XamarinComponents#29]
Since Google has been big on Firebase, is it possible to have a Firebase plug-in?

**Comment by SimonSimCity** [comment]
A lot of people seem to wait for it ... https://forums.xamarin.com/discussion/15383/firebase-support

**Comment by SimonSimCity** [comment]
This library seems to be compatible with Xamarin. Can you test it and give feedback? @sirinath https://github.com/ziyasal/FireSharp

**Comment by sirinath** [comment]
I know about it but did not try it because if the not from official channels (i.e., from either Google or Xamarin)

**Comment by bholmes** [comment]
There is some progress on Firebase in other repos.

For Android there pre-release [NuGets.](https://www.nuget.org/packages?q=Xamarin.Firebase)

GitHub work for [Android.](https://github.com/xamarin/GooglePlayServicesComponents/tree/v9.2.0)

GitHub work for [iOS.](https://github.com/SotoiGhost/GoogleApisForiOSComponents/tree/firebase)  This is an employee fork of Xamarin's [repo](https://github.com/xamarin/GoogleApisForiOSComponents)

**Comment by stefanbg** [comment]
Found this one too
https://github.com/rdelrosario/xamarin-plugins/tree/master/PushNotification

Apparently no Firebase support yet but says it's easy to change
https://github.com/rdelrosario/xamarin-plugins/issues/85

**Comment by iManchaDev** [comment]
@stefanbg What type of change is required, I succeed in sending the notification, only issue is the title doesn't show because FireBase uses a body field:

"gcm.notification.body": "testing push"

How do we change this, as my notifications are pushing blanks?

**Comment by AmaralDR** [comment]
@iManchaDev ,

    public void OnMessage(JObject values, DeviceType deviceType)
        {
            Debug.WriteLine("Message Arrived");

            CrossPushNotification.NotificationContentTextKey = "gcm.notification.body";
        }
