### ISSUE TITLE
[Gigya] sample project claims to include facebook and google plus login, but it doesn't

### ISSUE THREAD

**Issue by cinsola** [xamarin/XamarinComponents#293]
The iOs sample project doesn't work as expected and I can't figure out how to connect with facebook and google plus

**Comment by chazim63** [comment]
Did you get the iOS sample project to work?  I cannot even get it to compile. I will appreciate any help.

**Comment by newky2k** [comment]
@cinsola  is this still an issue or have you figured it out?

**Comment by newky2k** [comment]
closed as no response after two weeks
