### ISSUE TITLE
ARCore HelloAr appears that camera doesn't work on startup

### ISSUE THREAD

**Issue by omarrodriguez15** [xamarin/XamarinComponents#298]
When you first start up the HelloAr app, and grant camera access, the app appears like it is not working until you close and re open the app. 

Note: I've submitted a pull request to fix this

**Comment by justintoth** [comment]
How did you get the HelloAr solution building? I get this error:

> /Users/justintoth/Downloads/XamarinComponents-master/Android/ARCore/samples/JavaGL/CSC: Error CS1566: Error reading resource 'obj.jar' -- 'Could not find a part of the path "/Users/justintoth/Downloads/XamarinComponents-master/Android/ARCore/externals/obj.jar".' (CS1566) (JavaGL)

**Comment by omarrodriguez15** [comment]
@justintoth From your error I am guessing you are on a mac, I ran it on Windows. Did you run the build script ? From the ARCore folder run `../../build.sh --target libs`

**Comment by justintoth** [comment]
Yeah that's what I was missing, thanks.

**Comment by newky2k** [comment]
@omarrodriguez15  Hi,  I have now merged your pull request for this issue.
