### ISSUE TITLE
Open Source Test Cloud and Make Available Free Tiers 

### ISSUE THREAD

**Issue by sirinath** [xamarin/XamarinComponents#30]
In light of Twiter's FastLane Pilot it would be worthwhile to  FOSS Test Cloud and also make available a free tier

**Comment by MikeCodesDotNET** [comment]
Hey, 

I've gone ahead and closed this issue as it not related to our components or plugins. If you've general feedback about our products then I highly recommend using UserVoice as this is where we look for feedback.

https://xamarin.uservoice.com/forums/216684-xamarin-test-cloud
