### ISSUE TITLE
Objective Sharpie Open Source

### ISSUE THREAD

**Issue by myriaddevices** [xamarin/XamarinComponents#322]
We use Objective Sharpie incredibly often.  However there's a lot of manual labor that goes into creating a FAT library from Cocoapods, even after the cocoapod compatibility update.

I'd love to share my achievements with the community, and make developers who are scared of Xamarin because they'll loose their cocoapods a little less resistant.

**Comment by newky2k** [comment]
@myriaddevices I don't think there are currently any plans to open source Objective Sharpie i'm afraid.

**Comment by alexsorokoletov** [comment]
@newky2k is it still so?
There are some mistypes that sharpie generates from time to time, would be great if we can fix that.

**Comment by Janglinator** [comment]
@alexsorokoletov 

I'm a dev from Myriad:

We've kinda given up hope of this ever happening.  We have yet to get Swift cocoapods to successfully sign for the app store, and have had to abandon the idea in the meantime.

Sharpie is a great tool, and I'd still love to see it go open source, but until Swift libraries are supported, there's simply no reason to even use Sharpie anymore.  The Objc libraries we use are already bound, and new libraries we would want to bind (using Sharpie) are all written in Swift.

**Comment by alexsorokoletov** [comment]
That's a great point. Lack of easy Swift libraries consumption is a huge disadvantage for Xamarin devs and (I guess) Xamarin is addressing that. We should have a separate discussion for that. I simply want to make sharpie a bit better, even if it works with objective c only

**Comment by Janglinator** [comment]
Same here!  Hopefully it can be re-considered by the Xamarin team.  I'm not sure exactly what the drawbacks to it would be

**Comment by motoko89** [comment]
Two years later and I don't think the condition has improved?

**Comment by mattleibow** [comment]
For swift, I think we got toolings here: https://github.com/xamarin/binding-tools-for-swift

Not sure of the state, might be worth pinging the iOS team on this here: https://aka.ms/dotnet-discord
