### ISSUE TITLE
Mono.Posix.NETStandard does not support Alpine Linux

### ISSUE THREAD

**Issue by hjc4869** [xamarin/XamarinComponents#324]
.NET Core 2.1 preview added Alpine Linux support, and the RID is alpine.3.6-x64.

Since Alpine Linux is based on musl C, which is not fully compatible with glibc, alpine.3.6-x64 does not import linux-x64. The latest [Mono.Posix.NETStandard](https://www.nuget.org/packages/Mono.Posix.NETStandard/) package (1.0.0-beta4) only supports glibc-based Linux distros (linux-x64).

As a result, publishing a project to alpine.3.6-x64 will not include Mono.Posix.NETStandard.dll or libMonoPosixHelper.so.

To resolve this issue, a libMonoPosixHelper.so compiled using musl toolchain should be included in Mono.Posix.NETStandard package, in "alpine-x64" runtime directory.

> VS bug [#732188](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/732188)

**Comment by newky2k** [comment]
hi @hjc4869,  I spoken with @directhex  and they are going to have this assigned to them, but there are no timescales for when it will be done.

Thanks

**Comment by directhex** [comment]
Hi @hjc4869 

The build process for the Mono.Posix.NETStandard package works by extracting thirty-plus libMonoPosixHelper.so files from all our supported Mono package builds - Raspbian 8, Ubuntu 18.04 PowerPC Little Endian, etc.

Whilst we do run some CI on Alpine as part of a general effort to avoid breaking Musl support, we don't actively build release packages for it (I'll be honest, I know absolutely nothing about Alpine packaging). And, subsequently, there's no packages to extract a libMonoPosixHelper.so from.

Plus, it looks like our Alpine lane has been broken for months, and nobody fixed it, which doesn't help.

I can't make any timescale promises, but it's at least on the radar. I can look to special-casing libMonoPosixHelper.so for Alpine from the master-branch builds, to at least have _something_, without needing to learn another packaging system, once we're building/testing successfully again.
