### ISSUE TITLE
PCLStorage is obsolete

### ISSUE THREAD

**Issue by charlesroddie** [xamarin/XamarinComponents#327]
While great in its day, it is no longer maintained and is no longer needed since Xamarin supports .Net Standard 2.0 which has System.IO.

**Comment by mattleibow** [comment]
Just want to point out for more exact info, System.IO was all there in .NET Standard 1.3+

**Comment by newky2k** [comment]
Can i suggest that you take a look at Xamarin Essentials.  this has a filesystemhelper and secure storage API

https://github.com/xamarin/Essentials/wiki/Feature-Support
