### ISSUE TITLE
HelloAR sample project doesn't build, error reading resource obj.jar

### ISSUE THREAD

**Issue by justintoth** [xamarin/XamarinComponents#332]
The HelloAR project doesn't build:

> /Users/justintoth/Downloads/XamarinComponents-master/Android/ARCore/samples/JavaGL/CSC: Error CS1566: Error reading resource 'obj.jar' -- 'Could not find a part of the path "/Users/justintoth/Downloads/XamarinComponents-master/Android/ARCore/externals/obj.jar".' (CS1566) (JavaGL)

When I look at the [JavaGL project](https://github.com/xamarin/XamarinComponents/tree/master/Android/ARCore/samples/JavaGL), sure enough there is no obj.jar file. What am I missing?

**Comment by winnicki** [comment]
Bump

**Comment by justintoth** [comment]
@winnicki See this thread: https://stackoverflow.com/questions/49162567/implementing-arcore-with-xamarin

**Comment by dmarnel** [comment]
I'm seeing cake.build errors:

Error downloading 'XamarinComponent.1.1.0.65' from 'https://api.nuget.org/v3-flatcontainer/xamarincomponent/1.1.0.65/xamarincomponent.1.1.0.65.nupkg'.
crypt32.dll
Error downloading 'XamarinComponent.1.1.0.65' from 'https://api.nuget.org/v3-flatcontainer/xamarincomponent/1.1.0.65/xamarincomponent.1.1.0.65.nupkg'.
crypt32.dll
Install failed. Rolling back...
Error: One or more errors occurred. (Error downloading 'XamarinComponent.1.1.0.65' from 'https://api.nuget.org/v3-flatcontainer/xamarincomponent/1.1.0.65/xamarincomponent.1.1.0.65.nupkg'.)
	Error downloading 'XamarinComponent.1.1.0.65' from 'https://api.nuget.org/v3-flatcontainer/xamarincomponent/1.1.0.65/xamarincomponent.1.1.0.65.nupkg'.
