### ISSUE TITLE
 Cannot dynamically update TMX map using CocosSharp.Forms with Xamarin.Forms

### ISSUE THREAD

**Issue by ammarMheir** [xamarin/XamarinComponents#333]
##Overview

When using CocosSharpView controls hosted in Xamarin.Forms to load a Tiled TMX hex map, however when using methods such as <TilemapLayer>.SetTileGID, RemoveTile or ExtractTile, application hangs then crashes with no error in output window. 

##Steps to replicate

1. [Download attached sample](https://www.dropbox.com/s/rd4z7q7aaz9tfhv/TestMap.zip?dl=0)
2. Build and Deploy to Android device or Emulator
3. Click on ChangeTile Button to call TilemapLayer.RemoveTile
4. Observe application becomes unresponsive

The methods are being called in the TestMapPage.xaml.cs file within the Handle_Clicked method. 

##Expected resulted

To be able to dynamically update the map using <TilemapLayer>.SetTileGID, RemoveTile or ExtractTile methods without having application to freeze

> VS bug [#732191](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/732191)

**Comment by newky2k** [comment]
@ammarMheir  this doesn't appear to be a components issue. Its eiter and issue with CocosSharp itself, or with Xamarin.Forms.  The Xamarin.Forms references in the sample project are several major releases old.

Regards
