### ISSUE TITLE
Gigya XPlat missing gigya.Jar file

### ISSUE THREAD

**Issue by CurtisHerrick** [xamarin/XamarinComponents#334]
What jar file (or Gigya  SDK for Android version) was this Gigya XPlat Android solution developed using?

Since it the jar was missing, I've downloaded the latest (3.3.14.jar for Android) and I'm having a lot of build issues with the wrapper.

**Comment by newky2k** [comment]
hi @CurtisHerrick if you take a look at this file -> https://github.com/xamarin/XamarinComponents/blob/master/XPlat/Gigya/build.cake  you can see the version of the android sdk,  3.3.9, and where its downloading the jar file too.

regards
