### ISSUE TITLE
GigyaSDKSampleiOS Not Working

### ISSUE THREAD

**Issue by chazim63** [xamarin/XamarinComponents#335]
I am trying to compile and run the GiGyaSDKSampleiOS but keep getting this error:

C:\Program Files (x86)\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(700,3): error : Native linking error: framework not found GigyaSDK

The GigyaSDK.iOS project compiles just fine, but the GiGyaSDKSampleiOS project will fail with the mentioned above error.

**Comment by newky2k** [comment]
@chazim63  have you tried running the build.cake via the build targets to download the externals before running the solution.

**Comment by newky2k** [comment]
Closing as no response after two weeks
