### ISSUE TITLE
Gigya XPlat Android - FB/Gigya screenshots needed - Can't get facebook to provide login

### ISSUE THREAD

**Issue by CurtisHerrick** [xamarin/XamarinComponents#336]
I can run the demo as-is provided, with the gigya keys provided, and I do see Facebook as a login provider.  I've created my own Facebook App and am trying to get it to work with my Gigya API Key and account and I can't get Facebook to be presented as a login provider (like this demo code does when ran).  My app shows everything else, just not FB.

Can Facebook app and Gigya config screenshots be added (for the app and account that this GitHub code is using) as supplementary information?  I'm close to getting this working, but miles away at the same time.  Seems like I may have a setting off in FB or Gigya.  I've been trying all combos I can think of with no luck.

Thanks!
Curtis

**Comment by newky2k** [comment]
@CurtisHerrick Is this still an issue for you?

**Comment by newky2k** [comment]
No response for two weeks. closing issue
