### ISSUE TITLE
Xamarin.Build.Download targets always run

### ISSUE THREAD

**Issue by jonathanpeppers** [xamarin/XamarinComponents#341]
See: https://github.com/jonathanpeppers/XamarinAndroidBuildTimes#support-libraries--components

I discovered that the `_XamarinBuildDownloadMasterTarget` target is always running (no matter what) after doing some profiling of Xamarin.Android project builds. This seems to happen even if you build a project that just built (with no changes).

I took an [attempt](https://github.com/xamarin/XamarinComponents/compare/master...jonathanpeppers:proguard-target) to see if I could get a PR fixing it, but didn't quite get it working. I was initially trying to get `_XamarinAndroidBuildAarProguardConfigs` to skip, but it did not seem to matter since the parent target was still running. Thought it best to leave it up to @Redth.

I think if proper sets of `Inputs/Outputs` could be specified for the set of `Xamarin.Build.Download.targets`, we could improve build times in general for `Xamarin.Build.Download` by building incrementally. In theory, they should only need to re-run if references change, or if something major with the project changes.

No rush on this, can just be a TODO-list item for later.

**Comment by Redth** [comment]
I thought we had addressed this with https://github.com/xamarin/XamarinComponents/pull/300 which was released with 0.4.9... Can you confirm you were seeing this behaviour still on 0.4.9? We had quite a bit of feedback that this improved things...

**Comment by jonathanpeppers** [comment]
Whoops, I’ll update the project and try it again.

**Comment by jonathanpeppers** [comment]
I am seeing these targets run every time on 0.4.9, but I don't think it's an issue. They are taking less than 1ms, so the tasks aren't doing anything.

I am going to have to modify the sample (fork it), and redo my numbers I'd say.
