### ISSUE TITLE
iCarousel doesn't have libCarousel.a file

### ISSUE THREAD

**Issue by rkszone** [xamarin/XamarinComponents#342]
Carousel doesn't have  libCarousel.a file. tough I searched for and I found one but code is not working with that lib.a file. Can you please upload the correct .a file for this.
Thanks

**Comment by newky2k** [comment]
@rkszone  Hi, we have just merged an update to ICarousel and the libCarousel.a is downloaded from cocopods and builts as part of the build process, before the binding project is compiled.  You need to do that before you can use the source and samples.
