### ISSUE TITLE
How do I start using Xamarin.AndroidSwipeLayout?

### ISSUE THREAD

**Issue by mronnlun** [xamarin/XamarinComponents#343]
When installing the nuget Xamarin.AndroidSwipeLayout I get an error 

> Project 'xxx' requires the following components installed on your machine: 
Xamarin.Android.Support.v4
JavaLibraryReference: https://dl-ssl.google.com/android/repository/android_m2repository_r10.zip-m2repository/com/android/support/support-v4/21.0.3/support-v4-21.0.3.aar-21.0.3
JavaLibraryReference: https://dl-ssl.google.com/android/repository/android_m2repository_r10.zip-m2repository/com/android/support/support-v4/21.0.3/support-v4-21.0.3.aar-21.0.3
AndroidResources: https://dl-ssl.google.com/android/repository/android_m2repository_r10.zip-m2repository/com/android/support/support-v4/21.0.3/support-v4-21.0.3.aar-21.0.3

Then I'm requested to double click to install them:

> Please double-click here to install it.

Intallation Errors: XA5209 Unzipping failed. Please download 'https://dl-ssl.google.com/android/repository/android_m2repository_r10.zip:m2repository/com/android/support/support-v4/21.0.3/support-v4-21.0.3.aar' and extract it to the 'C:\Users\myself\AppData\Local\Xamarin\Xamarin.Android.Support.v4\21.0.3\embedded' directory
XA5209 Reason: Could not find a part of the path 'C:\Users\myself\AppData\Local\Xamarin\Xamarin.Android.Support.v4\21.0.3\embedded\aidl\'.
XA5207 Please install package: 'Android Support Library' available in SDK installer. Java library file 'C:\Users\myself\AppData\Local\Android\Sdk\extras\android\classes.jar' doesn't exist.
XA5207 Please install package: 'Android Support Library' available in SDK installer. Java library file 'C:\Users\myself\AppData\Local\Android\Sdk\extras\android\libs/internal_impl-21.0.3.jar' doesn't exist.		 	0	

Is it possible to create this nuget so no local install isn't needed? Don't know how to autobuild a project with this dependency.

**Comment by newky2k** [comment]
@mronnlun  Could you please provide some more info about the IDE, OS etc that you are using.

**Comment by newky2k** [comment]
No Response so closing
