### ISSUE TITLE
iRate SKStoreReviewController

### ISSUE THREAD

**Issue by Sebastian1989101** [xamarin/XamarinComponents#351]
Would be great if there is an option to support iOS 10.3+ `SKStoreReviewController.RequestReview()` by the iRate component. Otherwise this component is not allowed by the Apple AppStore Guidelines. 

> **1.1.7 App Store Reviews:**
> Use the provided API to prompt users to review your app; this functionality allows customers to provide an App Store rating and review without the inconvenience of leaving your app, and _we will disallow custom review prompts_.

**Source**: [https://developer.apple.com/app-store/review/guidelines/](https://developer.apple.com/app-store/review/guidelines/) 

Currently I use a overwrite for the `ShouldPromptForRating` Delegate but that seems to be not a clear solution because it prompts on TestFlight users with the wrong dialog because `SKStoreReviewController.RequestReview()` does not prompt for TestFlight. 

My current implementation: 
```
iRate.SharedInstance.ShouldPromptForRating = (arg1, arg2) =>
	{
#if DEBUG
		return false;
#endif
		if (UIDevice.CurrentDevice.CheckSystemVersion(10, 3))
		{
			try
			{
				SKStoreReviewController.RequestReview();
			}
			catch (Exception e)
			{
				Crashes.TrackError(e);
			}

			return false;
		}

		return true;
	};
```

**Comment by newky2k** [comment]
@Sebastian1989101  Thank you for your feedback and this is something we can look into.  In the meantime, if you have a work around you could submit a Pull request with the changes.

Thanks

**Comment by newky2k** [comment]
iRate has now been deprecated and there will not be any further updates for the package.
