### ISSUE TITLE
[OpenID] iOS TokenResponse Parameters Using NSCopying

### ISSUE THREAD

**Issue by aidenkeating** [xamarin/XamarinComponents#355]
I am attempting to create a test for a library I am working on, this involves creating an instance of `TokenResponse`. I would like to add parameters when creating the `TokenResponse`, this requires an `NSDictionary<NSString, NSCopying>`.

https://github.com/xamarin/XamarinComponents/blob/master/XPlat/OpenId/iOS/source/OpenId.AppAuth.iOS/ApiDefinition.cs#L960

I do not seem to be able to create an `NSDictionary` of this type, due to the `NSCopying`. Types such as `NSString` etc. cannot be cast or converted to `NSCopying`.

I am wondering whether this is supposed to be `NSDictionary<NSString, INSCopying>` instead? As `NSString` etc. do implement this interface/protocol.

I am new to Xamarin so I could be missing something here. Any help would be appreciated.

**Comment by aidenkeating** [comment]
@mattleibow I've seen that you have contributed a lot to the OpenID component here. Would you mind taking a look when you have some time? Happy to follow up with a PR if this is an issue.

**Comment by newky2k** [comment]
The PR is ready to go, you just need to sign the CLA and I can merge it
