### ISSUE TITLE
Missing constructor in iOS Mapbox API

### ISSUE THREAD

**Issue by WiredUK** [xamarin/XamarinComponents#359]
A key constructor is missing from the `MGLRasterStyleLayer` class. This means we cannot add a layer with a raster source to the map in an iOS application.

The [constructor that is missing](https://www.mapbox.com/ios-sdk/api/3.7.3/Classes/MGLRasterStyleLayer.html#/c:objc(cs)MGLRasterStyleLayer(im)initWithIdentifier:source:) is:

    init(identifier: String, source: MGLSource)

**Comment by newky2k** [comment]
A fix for the issues has not been merged.  We are working on pushing out a new version of OpenId

**Comment by Redth** [comment]
We have deprecated our bindings for Mapbox and have delisted the existing NuGet packages for them.

Please see the [README](https://github.com/xamarin/XamarinComponents/blob/master/XPlat/Mapbox/README.md) for more information.
