### ISSUE TITLE
!Xamarin.forms requirement from readme ?

### ISSUE THREAD

**Issue by pfaucon** [xamarin/XamarinComponents#365]
The readme suggests that a package should have no dependency on Xamarin.Forms, but I would like to suggest that in some cases it may be valuable to have packages despite the dependency.

For example we needed the ability to take screenshots of a specific view in an app, so I made a plugin to manage that for our project(mainly adapted https://github.com/jamesmontemagno/MediaPlugin/pull/489), but it would be nice to contribute it for the general good.  Is there some sort of XamarinFormsComponents? Otherwise I think it would be good to allow XF-specific plugins, maybe separated from the others to make clear the requirement on XF.

In our case the plugin may be able to eschew XF, except when capturing a specific view, in which case the PCL/.NET only has a reference to the View (inherently an XF object). Below the View everything is native, without the XF reference it would be much much more work, if it is possible.

**Comment by newky2k** [comment]
@pfaucon I will raise the prospect of of adding XForms(possibly in the XPlat section) to the repo where the no XF requirement can be ignored.  I can also get a bit more information about why that requirement is there for starters.

Thank you for your patience

**Comment by newky2k** [comment]
@pfaucon While we can't add it to the main repo if it has Xamarin.Forms dependecies, you could host it in your own repo and add a PR to change the list of plugins to include it on the list.
