### ISSUE TITLE
PLEASE FIX:   ISpiDevice  .Write or .Read methods missing since .7 package.  

### ISSUE THREAD

**Issue by BeanStalka** [xamarin/XamarinComponents#368]
I just upgraded to the latest package (.8) and I can no longer access the SpiDevice.Read or Write methods

Anybody know whats going on with this?

**Comment by BeanStalka** [comment]
UPDATE:

I have updated again to the latest NuGet package (1.0) and it still does not expose the Read or Write methods for AT's SpiDevice.

I can verify that they are in the android source .jar from here:  https://bintray.com/google/androidthings/androidthings-supportlibrary#files/com%2Fgoogle%2Fandroid%2Fthings%2Fandroidthings%2F1.0

These methods are missing all the way back to .7.

If I had to guess, someone is using Xamarin's Bound Library project to create this.  You need to edit the metadata.xml to help with the translation from Java to C#.  Other wise you will miss methods ect.

Please bump this in priority, as I am sure there are a slew of other projects that would like to use SPI in android things.

**Comment by newky2k** [comment]
@BeanStalka  I have asked the developer to look into this issue for you so that can get it resolved for you
thank you for your patience

**Comment by newky2k** [comment]
@BeanStalka We have pushed out a new version of Android Things that has a fix for this issue
