### ISSUE TITLE
Facebook Android SDK Update

### ISSUE THREAD

**Issue by ivzhang** [xamarin/XamarinComponents#378]
Bindings for the Facebook SDK for Android is several versions behind the latest version. Concern from developers that the requirement to resubmit applications for review may cause issues with using an older version of the SDK. Already had a discussion with Jonathan on getting these updated. 

Current version: 4.26.0
https://www.nuget.org/packages/Xamarin.Facebook.Android/

Latest Facebook SDK: 4.32
https://developers.facebook.com/docs/android/

**Comment by newky2k** [comment]
You may want to consider Xamarin.Essentials as it includes Filesystem helper and Secure storage apis

https://github.com/xamarin/Essentials/wiki/Feature-Support

**Comment by newky2k** [comment]
@ivzhang  We are working on this ATM and should have a PR request to implement the update shortly

**Comment by caseyniemann** [comment]
@newky2k we are blocked due to this.  Please provide an update

**Comment by Redth** [comment]
We are working on a branch here: https://github.com/xamarin/FacebookComponents/tree/android-updates?files=1

**Comment by newky2k** [comment]
@caseyniemann it looks this has been merged now from this PR in the facebookcomponents https://github.com/xamarin/FacebookComponents/pull/73
