### ISSUE TITLE
OpenID AppAuth Exception after upgrade Xamarin iOS 10.11

### ISSUE THREAD

**Issue by rambo406** [xamarin/XamarinComponents#380]
After upgrade to Xamarin iOS 11.10.
I have the following error when calling `PresentAuthorizationRequest ` method.

`Unhandled Exception: ObjCRuntime.RuntimeException: Failed to compute the token reference for the type 'OpenId.AppAuth.IAuthorizationFlowSession, OpenId.AppAuth.iOS, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null' because the assembly couldn't be found in the list of registered assemblies. at ObjCRuntime.Class.GetTokenReference (System.Type type) [0x000c8] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.10.1.177/src/Xamarin.iOS/ObjCRuntime/Class.cs:439 at ObjCRuntime.Runtime.FindProtocolWrapperType (System.Type type) [0x00021] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.10.1.177/src/Xamarin.iOS/ObjCRuntime/Runtime.cs:1355 at ObjCRuntime.Runtime.LookupINativeObjectImplementation (System.IntPtr ptr, System.Type targettype, System.Type implementation) [0x00062] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.10.1.177/src/Xamarin.iOS/ObjCRuntime/Runtime.cs:1262 at ObjCRuntime.Runtime.GetINativeObject[T] (System. IntPtr ptr, System.Boolean owns) [0x0008d] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.10.1.177/src/Xamarin.iOS/ObjCRuntime/Runtime.cs:1329 at OpenId.AppAuth.AuthorizationService.PresentAuthorizationRequest (OpenId.AppAuth.AuthorizationRequest request, OpenId.AppAuth.IAuthorizationUICoordinator UICoordinator, OpenId.AppAuth.AuthorizationCallback callback) [0x00069] in <2cd325e58f6243e8b54d78a48a653c17>:0 at TLP.Mobility.iOS.Views.LoginViewController+<BtnLoginTouchUpInside>d6.MoveNext () [0x00137] in D:\Timelog Git Repo\TLP.Mobility\TLP.Mobility\TLP.Mobility.iOS\Views\LoginViewController.cs:54 --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.10.1.177/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/exceptionservices/exceptionservicescommon.cs:152 at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c .<ThrowAsync>b60 (System.Object state) [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.10.1.177/src/Xamarin.iOS/mcs/class/referencesource/mscorlib/system/runtime/compilerservices/AsyncMethodBuilder.cs:1018 at UIKit.UIKitSynchronizationContext+<>cDisplayClass10.<Post>b0 () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.10.1.177/src/Xamarin.iOS/UIKit/UIKitSynchronizationContext.cs:24 at Foundation.NSAsyncActionDispatcher.Apply () [0x00000] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.10.1.177/src/Xamarin.iOS/Foundation/NSAction.cs:125 --- End of stack trace from previous location where exception was thrown --- at (wrapper managed-to-native) UIKit.UIApplication.UIApplicationMain(int,string[],intptr,intptr) at UIKit.UIApplication.Main (System.String[] args, System.IntPtr principal, System.IntPtr delegate) [0x00005] in /Library/Frameworks/Xamarin.iOS.framework/Versions/11.10.1.177/src/Xamarin.iOS/U`

> VS bug [#732187](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/732187)

**Comment by newky2k** [comment]
Hi @rambo406 i've assigned @mattleibow to look into this issue

**Comment by aidenkeating** [comment]
@newky2k @mattleibow @rambo406  Hey guys, I'm also seeing this error. Is there any update on this issue or any workaround suggested?

**Comment by rambo406** [comment]
@aidenkeating what I did was upgrade VS for Mac to "beta". And download VS2017 preview version. Clean the solution and recompile.

**Comment by ssepulveda** [comment]
Any updates to fix this issue ?

**Comment by newky2k** [comment]
@ssepulveda  Can you check again as there has been a main release of VS for Mac, which may resolve the issue.

Regards

**Comment by Redth** [comment]
We are closing this issue since no response was received.  Please open a new issue referring to this one if you have more information.
