### ISSUE TITLE
UART Java.Lang.SecurityException: <Timeout exceeded getting exception details>

### ISSUE THREAD

**Issue by antonsterkhov** [xamarin/XamarinComponents#389]
ERROR] FATAL UNHANDLED EXCEPTION: Java.Lang.SecurityException: Caller lacks required permission com.google.android.things.permission.USE_PERIPHERAL_IO

I'm trying to work with UART but I have a bug that there is no access. What can be wrong ?

**Comment by varunmuley** [comment]
Similar error for me but for using GPIO. Any solutions yet ?

**Comment by varunmuley** [comment]
Was getting similar error for GPIO. Fixed it by adding line,
 < uses-permission android:name="com.google.android.things.permission.USE_PERIPHERAL_IO" />
in the AndroidManifest.xml file.

**Comment by newky2k** [comment]
@antonsterkhov can you see the reply from @varunmuley.  You just need to add the com.google.android.things.permission.USE_PERIPHERAL_IO permission to the AndroidManfiest in your app.

**Comment by rondagdag** [comment]
I am getting the same error even if I added 
<uses-permission android:name="com.google.android.things.permission.USE_PERIPHERAL_IO"/>
to the androidManifest file. Any ideas?
