### ISSUE TITLE
Please add support for background mode.

### ISSUE THREAD

**Issue by jinlook** [xamarin/XamarinComponents#4]
Just like this one.
https://github.com/katzer/cordova-plugin-background-mode

It is a cool plugin for cordova, I wish we could have the same one in xamarin plugins.
Also, the https://github.com/katzer have several other good plugins. 
Please make one or two happened in xamarin world~

**Comment by newky2k** [comment]
Hi @jinlook ,

I would suggesting this as part of Xamarin Essentials as an Issue using this as a template

https://github.com/xamarin/Essentials/wiki/Proposing-New-Features

Regards
