### ISSUE TITLE
STILL FAILING TO BIND  ISpiDevice .Write or .Read methods missing since .7 package

### ISSUE THREAD

**Issue by BeanStalka** [xamarin/XamarinComponents#405]
How is this not a top priority?

Anyone who needs to use the ISPIDevice is screwed.

There is no .Read or .Write exposed.

This needs to be fixed, unless you are good with everyone else rolling their own binding to the library.

So Disappointing.

**Comment by newky2k** [comment]
@BeanStalka  Hi,  I'm am looking into this issue for you

**Comment by newky2k** [comment]
@BeanStalka Could you provide some more information about this issue please, such as version of iOS, IDE, sample code etc.

thanks

**Comment by newky2k** [comment]
@BeanStalka  i have assked the developer to look into this, but as your #368 issue has more detail i'm going to close this one and get him to focus on that one
