### ISSUE TITLE
Problem to run a Xamarin.Android and Xamarin.Forms on new version of android Things

### ISSUE THREAD

**Issue by binhara** [xamarin/XamarinComponents#406]
I try run a simple Xamarin.App on android things and got some issues

A Xamarin.Android work when run from Visual Studio, but dont crash  when start from a adb shell 

 i got some message like 

> E:\XAndroidThingTest>adb shell
> rpi3:/ $ am start br.com.binhara.AppAndroidFormsTest.Android.apk
> Starting: Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] pkg=br.com.binhara.AppAndroidFormsTest.Android.apk }
> Error: Activity not started, unable to resolve Intent { act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 pkg=br.com.binhara.AppAndroidFormsTest.Android.apk }

i put some information on android manifest like 

>   <uses-library android:name="com.google.android.things" />
> 
>         <activity android:name=".MainActivity">
>             <intent-filter>
>                 <action android:name="android.intent.action.MAIN" />
> 
>                 <category android:name="android.intent.category.LAUNCHER" />
>             </intent-filter>
>             <intent-filter>
>                 <action android:name="android.intent.action.MAIN" />
> 
>                 <category android:name="android.intent.category.IOT_LAUNCHER" />
>                 <category android:name="android.intent.category.DEFAULT" />
>             </intent-filter>
>         </activity>

A xamarin.forms app dont work , i got a message : 
Java.Lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.companyname/com.companyname.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "com.companyname.MainActivity" on path: DexPathList[[zip file "/system/framework/com.google.android.things.jar", zip file "/data/app/com.companyname-qtaXNTau7xDLuSTZcM11Sw==/base.apk"],nativeLibraryDirectories=[/data/app/com.companyname-qtaXNTau7xDLuSTZcM11Sw==/lib/arm, /data/app/com.companyname-qtaXNTau7xDLuSTZcM11Sw==/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]

My mainactivity has 

  ```
[Activity(Label = "Sample Thing", MainLauncher = true)]
    [IntentFilter(new[] { Intent.ActionMain }, Categories = new[] { Intent.CategoryLauncher })]
    [IntentFilter(new[] { Intent.ActionMain }, Categories = new[] { "android.intent.category.IOT_LAUNCHER" })]
    [IntentFilter(new[] { Intent.ActionMain}, Categories = new[] { Intent.ActionMain })]
    [IntentFilter(new[] { Intent.ActionMain }, Categories = new[] { Intent.CategoryHome })]
    [IntentFilter(new[] { Intent.ActionMain }, Categories = new[] { Intent.CategoryDefault })]
    public class MainActivity : global::Xamarin.Forms.Platform.Android.FormsAppCompatActivity
```

Can someone help me ?

**Comment by lassana** [comment]
@binhara , have you managed to solve this?

**Comment by newky2k** [comment]
@binhara  Could you provide a sample project for us to test and replicate this issue so we can investigate further. 

Thanks in advance

**Comment by newky2k** [comment]
Closing as no repsonse
