### ISSUE TITLE
Google Analytics for Xamarin Forms

### ISSUE THREAD

**Issue by KSemenenko** [xamarin/XamarinComponents#41]
I think that we all need a cross-platform library for Google Analytics which would easily connect to Xamarin

**Comment by goti2** [comment]
That's what I need!

**Comment by athulh** [comment]
When there is insights why would you need google analytics?

**Comment by KSemenenko** [comment]
I have to use google analytics in several projects, this is a business requirement, they receive analytic from various sources, besides it's very inconvenient when there is a need to assembly google analytics for each platform. That's why I've decided that this library will be useful if someone faces same difficulties.

And this link inspired me:
[https://theconfuzedsourcecode.wordpress.com/2015/07/18/okay-finally-lets-add-google-analytics-to-xamarin-forms](https://theconfuzedsourcecode.wordpress.com/2015/07/18/okay-finally-lets-add-google-analytics-to-xamarin-forms/)
