### ISSUE TITLE
MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: SDWebImageManagerDelegate. The symbol '_OBJC_CLASS_$_SDWebImageManagerDelegate' could not be found in any of the libraries or frameworks linked with your application.

### ISSUE THREAD

**Issue by VincentDondain** [xamarin/XamarinComponents#437]
_From @GeonetJP on August 7, 2018 8:19_

**My setup:**
- Visual Studio for Mac Community Version 7.5.4 (build 3)
- Xamarin SDK updated to the latest
- iOS SDK updated to the latest.

When I run my project it fails with the following:

```
clang : error : linker command failed with exit code 1 (use -v to see invocation)
MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: SDWebImageManagerDelegate. The symbol '_OBJC_CLASS_$_SDWebImageManagerDelegate' could not be found in any of the libraries or frameworks linked with your application.
MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: SDWebImagePrefetcherDelegate. The symbol '_OBJC_CLASS_$_SDWebImagePrefetcherDelegate' could not be found in any of the libraries or frameworks linked with your application.
MTOUCH : error MT5202: Native linking failed. Please review the build log.
```

It started right after the latest updated from both SDK (Xamarin and iOS)

I've read the previous posts with similar issue and I think it can be fixed from your side via an update on your Nuget Package: Xamarin.SDWebImage.

Can you please help with this issue?

_Copied from original issue: xamarin/xamarin-macios#4585_

**Comment by newky2k** [comment]
@VincentDondain  We are in the final stages of releasing a new version of SDWebimage, so this should hopefully fix your problem.

**Comment by GeonetJP** [comment]
Hi @newky2k,

I'm still waiting for your updates on the Xamarin.SDWebImage Component.

Do you have any timescale on this. The current version I'm running on my project is the latest available (version 4.0.0-beta1) but it's still not compiling. Just failing with the same stack trace.

Any details would be helpful. 

Is there any patch applicable on my code to make it work?

Thanks.

**Comment by GeonetJP** [comment]
Hi @VincentDondain, @newky2k,

Is it possible to know when a fixed version of the SDWebImage Component will be available.

I'm running the version 4.0.0-beta1 but it's still failing with the same issue:

> clang : error : linker command failed with exit code 1 (use -v to see invocation)
MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: SDWebImageManagerDelegate. The symbol '_OBJC_CLASS_$_SDWebImageManagerDelegate' could not be found in any of the libraries or frameworks linked with your application.
MTOUCH : error MT5211: Native linking failed, undefined Objective-C class: SDWebImagePrefetcherDelegate. The symbol '_OBJC_CLASS_$_SDWebImagePrefetcherDelegate' could not be found in any of the libraries or frameworks linked with your application.
MTOUCH : error MT5202: Native linking failed. Please review the build log.

I currently have a project to update and to deliver and I can't implement the new features just because this component it's not working at compilation phase.

Do you have any advice or tips e.g. for example to get the component and patch it myself so at least I could make it work locally till you push the official fix.

Any help/support would be great

**Comment by Redth** [comment]
We just pushed v4.4.0 to NuGet which works well in testing here.

Please give it a try!

**Comment by Redth** [comment]
FYI may be a few minutes for it to show up in NuGet.org's index, but here's the direct link:
https://www.nuget.org/packages/Xamarin.SDWebImage/4.4.0

**Comment by GeonetJP** [comment]
Hi @Redth,

I just downloaded the latest version and I confirm that it works perfectly fine now.

Thanks for the fix.

**Comment by fabiorme** [comment]
Hi all, I'm getting the following error, does anyone know how to fix it?

1>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(224,3): warning MT0141: The interpreter is not supported in the simulator. Switching to REPL which provide the same extra features on the simulator.
1>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(224,3): error MT5211: Native linking failed, undefined Objective-C class: MSACAbstractLog. The symbol '_OBJC_CLASS_$_MSACAbstractLog' could not be found in any of the libraries or frameworks linked with your application.
1>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(224,3): error MT5211: Native linking failed, undefined Objective-C class: MSACAppCenter. The symbol '_OBJC_CLASS_$_MSACAppCenter' could not be found in any of the libraries or frameworks linked with your application.
1>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(224,3): error MT5211: Native linking failed, undefined Objective-C class: MSACAppCenterUserDefaults. The symbol '_OBJC_CLASS_$_MSACAppCenterUserDefaults' could not be found in any of the libraries or frameworks linked with your application.
1>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(224,3): error MT5211: Native linking failed, undefined Objective-C class: MSACAppDelegateForwarder. The symbol '_OBJC_CLASS_$_MSACAppDelegateForwarder' could not be found in any of the libraries or frameworks linked with your application.
1>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(224,3): error MT5211: Native linking failed, undefined Objective-C class: MSACChannelUnitConfiguration. The symbol '_OBJC_CLASS_$_MSACChannelUnitConfiguration' could not be found in any of the libraries or frameworks linked with your application.
1>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(224,3): error MT5211: Native linking failed, undefined Objective-C class: MSACDependencyConfiguration. The symbol '_OBJC_CLASS_$_MSACDependencyConfiguration' could not be found in any of the libraries or frameworks linked with your application.
1>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(224,3): error MT5211: Native linking failed, undefined Objective-C class: MSACHttpClient. The symbol '_OBJC_CLASS_$_MSACHttpClient' could not be found in any of the libraries or frameworks linked with your application.
1>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(224,3): error MT5211: Native linking failed, undefined Objective-C class: MSACHttpIngestion. The symbol '_OBJC_CLASS_$_MSACHttpIngestion' could not be found in any of the libraries or frameworks linked with your application.
1>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(224,3): error MT5211: Native linking failed, undefined Objective-C class: MSACHttpUtil. The symbol '_OBJC_CLASS_$_MSACHttpUtil' could not be found in any of the libraries or frameworks linked with your application.
1>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(224,3): error MT5211: Native linking failed, undefined Objective-C class: MSACKeychainUtil. The symbol '_OBJC_CLASS_$_MSACKeychainUtil' could not be found in any of the libraries or frameworks linked with your application.
1>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(224,3): error MT5211: Native linking failed, undefined Objective-C class: MSACLogger. The symbol '_OBJC_CLASS_$_MSACLogger' could not be found in any of the libraries or frameworks linked with your application.
1>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(224,3): error MT5211: Native linking failed, undefined Objective-C class: MSACServiceAbstract. The symbol '_OBJC_CLASS_$_MSACServiceAbstract' could not be found in any of the libraries or frameworks linked with your application.
1>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(224,3): error MT5211: Native linking failed, undefined Objective-C class: MSACSessionContext. The symbol '_OBJC_CLASS_$_MSACSessionContext' could not be found in any of the libraries or frameworks linked with your application.
1>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(224,3): error MT5211: Native linking failed, undefined Objective-C class: MSACUtility. The symbol '_OBJC_CLASS_$_MSACUtility' could not be found in any of the libraries or frameworks linked with your application.
1>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(224,3): error MT5211: Native linking failed, undefined Objective-C class: MSAC_Reachability. The symbol '_OBJC_CLASS_$_MSAC_Reachability' could not be found in any of the libraries or frameworks linked with your application.
1>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(224,3): error MT5210: Native linking failed, undefined symbol: _OBJC_METACLASS_$_MSACAbstractLog. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
1>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(224,3): error MT5210: Native linking failed, undefined symbol: _OBJC_METACLASS_$_MSACHttpIngestion. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
1>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(224,3): error MT5210: Native linking failed, undefined symbol: _OBJC_METACLASS_$_MSACServiceAbstract. Please verify that all the necessary frameworks have been referenced and native libraries are properly linked in.
1>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(224,3): warning MT5215: References to 'System' might require additional -framework=XXX or -lXXX instructions to the native linker
1>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(224,3): warning MT5215: References to 'ole32' might require additional -framework=XXX or -lXXX instructions to the native linker
1>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(224,3): warning MT5215: References to 'System' might require additional -framework=XXX or -lXXX instructions to the native linker
1>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(224,3): warning MT5215: References to 'System.Net.Security' might require additional -framework=XXX or -lXXX instructions to the native linker
1>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(224,3): warning MT5215: References to 'System' might require additional -framework=XXX or -lXXX instructions to the native linker
1>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(224,3): warning MT5215: References to 'System' might require additional -framework=XXX or -lXXX instructions to the native linker
1>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(224,3): warning MT5215: References to 'crypt32' might require additional -framework=XXX or -lXXX instructions to the native linker
1>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(224,3): warning MT5215: References to 'advapi32' might require additional -framework=XXX or -lXXX instructions to the native linker
1>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(224,3): warning MT5215: References to 'kernel32' might require additional -framework=XXX or -lXXX instructions to the native linker
1>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(224,3): warning MT5215: References to 'ncrypt' might require additional -framework=XXX or -lXXX instructions to the native linker
1>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(224,3): error MT5202: Native linking failed. Please review the build log.
1>C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(224,3): error : linker command failed with exit code 1 (use -v to see invocation)
