### ISSUE TITLE
SerializedCert Export for X509Certificate2

### ISSUE THREAD

**Issue by zcleghern** [xamarin/XamarinComponents#439]
For my application, I need SerializedCert to be implemented in X509Certificate2.Export(). Is this planned?

**Comment by newky2k** [comment]
@zcleghern  is this a from component or part of the component repo or is this something related to Xamarin.iOS specifically?

**Comment by zcleghern** [comment]
The Xamarin implementation of X509Certificate2 cannot Export using X509ContentType.SerializedCert as a parameter. My apologies if this is the wrong repo to raise this issue in.

**Comment by newky2k** [comment]
@zcleghern Hi this the components repo, unfortunately i don't think we will be able to help
