### ISSUE TITLE
Crashlytics stacktrace for Xamarin Android

### ISSUE THREAD

**Issue by deckerst** [xamarin/XamarinComponents#443]
I've added the following packages to my Xamarin Forms Android project:
```
  <package id="Xamarin.Android.Crashlytics" version="2.9.4" targetFramework="monoandroid90" />
  <package id="Xamarin.Android.Crashlytics.Answers" version="1.4.2" targetFramework="monoandroid90" />
  <package id="Xamarin.Android.Crashlytics.Beta" version="1.2.9" targetFramework="monoandroid90" />
  <package id="Xamarin.Android.Crashlytics.Core" version="2.6.3" targetFramework="monoandroid90" />
  <package id="Xamarin.Android.Fabric" version="1.4.3" targetFramework="monoandroid90" />
```

In the activity OnCreate() I initialized Crashlytics:
```
            Fabric.Fabric.With(this, new Crashlytics.Crashlytics());
            Crashlytics.Crashlytics.HandleManagedExceptions();
```

Then I added some code to throw an unhandled NullReferenceException on purpose. The following are the logs, where we see first the useful stacktrace from [MonoDroid] and then the useless stacktrace from [AndroidRuntime]:
```
[MonoDroid] UNHANDLED EXCEPTION:
[MonoDroid] System.NullReferenceException: Object reference not set to an instance of an object
[MonoDroid]   at Hermes.Forms.BookmarksPage.OnAppearing () [0x00023] in <819ff9827c24420f92d02104770d9707>:0 
[MonoDroid]   at Xamarin.Forms.Page.SendAppearing () [0x00024] in <79e71a8d444446bbb832a0886d42abe0>:0 
[MonoDroid]   at Xamarin.Forms.Platform.Android.AppCompat.FragmentContainer.SendLifecycleEvent (System.Boolean isAppearing) [0x00059] in <6b73296523894c3d8d57f5a8e3480a43>:0 
[MonoDroid]   at Xamarin.Forms.Platform.Android.AppCompat.FragmentContainer.OnResume () [0x00011] in <6b73296523894c3d8d57f5a8e3480a43>:0 
[MonoDroid]   at Android.Support.V4.App.Fragment.n_OnResume (System.IntPtr jnienv, System.IntPtr native__this) [0x00008] in <836792d8ce234ed6894f18520d811c04>:0 
[MonoDroid]   at (wrapper dynamic-method) System.Object.46(intptr,intptr)
[art] JNI RegisterNativeMethods: attempt to register 0 native methods for md5bcaacea39e485ed8e3d7f0e2edda77a7.MonoException
[art] JNI RegisterNativeMethods: attempt to register 0 native methods for md5bcaacea39e485ed8e3d7f0e2edda77a7.MonoExceptionHelper
[AndroidRuntime] FATAL EXCEPTION: main
[AndroidRuntime] Process: bpu.neil, PID: 23778
[AndroidRuntime] md5bcaacea39e485ed8e3d7f0e2edda77a7.MonoExceptionHelper: (NullReferenceException) Object reference not set to an instance of an object
[AndroidRuntime] 	at md58432a647068b097f9637064b8985a5e0.FragmentContainer.n_onResume(Native Method)
[AndroidRuntime] 	at md58432a647068b097f9637064b8985a5e0.FragmentContainer.onResume(FragmentContainer.java:65)
[AndroidRuntime] 	at android.support.v4.app.Fragment.performResume(Fragment.java:2308)
[AndroidRuntime] 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1465)
...
```

The issue is that in Crashlytics I can only see the useless [AndroidRuntime] stacktrace, and nothing from the [MonoDroid] stacktrace.

Is this a known limitation, or is there a way to get the right stacktrace reported to Crashlytics?

**Comment by Redth** [comment]
We don't currently automatically trap normal .net unhandled exceptions, perhaps you might try:

```
AppDomain.CurrentDomain.UnhandledException += (object sender, UnhandledExceptionEventArgs e) =>
    Crashlytics.LogException(MonoExceptionHelper.Create(e.ExceptionObject as Exception));
```

**Comment by deckerst** [comment]
Thank you for the tip, but in that handler the `e.ExceptionObject` is actually a `Crashlytics.MonoExceptionHelper` with the same useless [AndroidRuntime] stacktrace as the one I pasted above.

I guess the exception created thanks to `Crashlytics.HandleManagedExceptions()` is initialized with the wrong context.

**Comment by Redth** [comment]
I'm not quite sure I understand what you're expecting.  What if you don't use `Crashlytics.HandleManagedExceptions()` and wire up the exception handlers you're expecting yourself?

**Comment by deckerst** [comment]
The Firebase Crash Reporting packages for Android and iOS, as well as the Crashlytics package for iOS all report useful stacktraces (like the one tagged `[MonoDroid]` in my first post above), with no extra customization. My expectation was that this Crashlytics package for Android would too, but apparently it does not so I got confused.

Anyway, thanks for the help.

**Comment by deckerst** [comment]
I took a closer look at `Crashlytics.HandleManagedExceptions()` and I believe the issue is that in the constructors of `MonoException`, the stack elements are assigned to the local member `Stack` but this member is never read anywhere as far as I know. By replacing those assignments by `SetStackTrace(stack);` the right stack traces are finally reported to Crashlytics.

**Comment by Redth** [comment]
Nice catch.  For now you can probably work around this by wiring things up yourself, but we will get a small bug fix release out shortly with this change as well.

**Comment by Redth** [comment]
Crashlytics 2.9.4.1 was just published which should take care of the `MonoException` not properly setting the stack trace.

https://www.nuget.org/packages/Xamarin.Android.Crashlytics/2.9.4.1

**Comment by klemenzarn** [comment]
I am still having some troubles with Crashlytics.HandleManagedExceptions().

Without this line I get stracktraces like:
`Fatal Exception: android.runtime.JavaProxyThrowable: System.NullReferenceException: Object reference not set to an instance of an object
  at MyApp.Core.Pages.PinPage..ctor () [0x00041] in <7737708e43d4468d88ea9448698fbd8e>:0`

From which with `mono-symbolicate` I can get real file name and line numbers like:
`Fatal Exception: android.runtime.JavaProxyThrowable: System.NullReferenceException: Object reference not set to an instance of an object
  at MyApp.Core.Pages.PinPage..ctor () [0x00041] in MyApp.Core\Pages\PinPage.xaml.cs:28 `

But in Crashlytics all crashes are reported as same group  `RunnableImplementor.java` which make crashes hard to organize and read...

With Crashlytics.HandleManagedExceptions() I get stack trace such as:
`Fatal Exception: md5bcaacea39e485ed8e3d7f0e2edda77a7.MonoExceptionHelper: (NullReferenceException) Object reference not set to an instance of an object
       at MyApp.Core.Pages.PinPage..ctor()[0x00041](0x00041.cs:1)`

which are grouped ok in Crashlytics but I can't de-obfuscate stacktrace with `mono-symbolicate` because hashes like `<7737708e43d4468d88ea9448698fbd8e>:0` are missing.
