### ISSUE TITLE
Crashlytics ends on Firebase on September 9th, 2018

### ISSUE THREAD

**Issue by Dooks123** [xamarin/XamarinComponents#447]
Will this continue to work on the Fabric.io platform?

**Comment by Redth** [comment]
@Dooks123 not sure what you mean.  My understanding is that Firebase *Crash Reporting* ends on September 9th and that Firebase *Crashlytics* is the new dashboard/system to use.  The current release of [Xamarin.Android.Crashlytics](https://www.nuget.org/packages/Xamarin.Android.Crashlytics/) supports the new Crashlytics API and dashboard.
