### ISSUE TITLE
I can't find the source code for Login Screen 

### ISSUE THREAD

**Issue by DiomedesDominguez** [xamarin/XamarinComponents#45]
Hi, I'd like to make some extensions for the Login Screen Component https://components.xamarin.com/view/loginscreen/ but i can't find the source code.

For example the activity label:
![2016070301](https://cloud.githubusercontent.com/assets/4379316/16548986/8ce1bbcc-4167-11e6-8790-94c60dc994f9.PNG)

**Comment by bholmes** [comment]
I will add this to the list to move to the public repo.

**Comment by tdmiller** [comment]
Just bumping this to see if there is any status on this being moved to the public repo :-)

**Comment by DiomedesDominguez** [comment]
Sorry, we're still waiting. If you want the source code, use Resharper's dot net peek.

**Comment by tdmiller** [comment]
Sounds good--thanks for the quick response!

**Comment by DiomedesDominguez** [comment]
No problem bro!

**Comment by bholmes** [comment]
https://github.com/xamarin/XamarinComponents/pull/103

**Comment by newky2k** [comment]
Closing issue as #103 has now been merged
