### ISSUE TITLE
Xamarin.Android.Crashlytics - creating provider for dollar_openBracket_applicationId_closeBracket

### ISSUE THREAD

**Issue by shimfish** [xamarin/XamarinComponents#451]
I'm using the latest version of Visual Studio for Mac (7.6.4) and Xamarin.Android.Crashlytics 2.9.4.1.

I can no longer build more than 1 app using Crashlytics as it fails on Install with the following error:

`/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.Debugging.targets(479,2): error ADB0010: Failure [INSTALL_FAILED_CONFLICTING_PROVIDER: Package couldn't be installed in /data/app/com.shim.app2.xamarin-il4yfmLLTH1rB8BtkFIHKw==: Can't install because provider name dollar_openBracket_applicationId_closeBracket (in package com.shim.app2.xamarin) is already used by com.shim.app1.xamarin]`

It works fine if I remove the Crashlytics and Fabric packages.

Update: Found this in the AndroidManifest.xml

```
        <provider
            android:name="com.crashlytics.android.CrashlyticsInitProvider"
            android:exported="false"
            android:authorities="com.shim.app1.crashlyticsinitprovider"
            android:initOrder="100" />

        <provider
            android:name="com.crashlytics.android.CrashlyticsInitProvider"
            android:exported="false"
            android:authorities="dollar_openBracket_applicationId_closeBracket"
            android:initOrder="100" />
```

**Comment by ruhanijeb** [comment]
i am also facing the same issue.

**Comment by newky2k** [comment]
@ruhanijeb @shimfish  I have assigned @Redth to investigate

**Comment by jldubz** [comment]
I am also encountering the same issue and am happy to provide additional information as necessary.

**Comment by Redth** [comment]
This is a duplicate of #444

**Comment by Dooks123** [comment]
Can this please be fixed?

**Comment by dionisoliveira** [comment]
I Solved my problem deleting all app's in debug mode in my device/emulator using Crashlytics  and install package Xamarin.Build.Download last release in droid Project.
