### ISSUE TITLE
Error MT4116

### ISSUE THREAD

**Issue by andrewbenson92** [xamarin/XamarinComponents#453]
[FLAnimatedImageXamarin-1.0.01.zip](https://github.com/xamarin/XamarinComponents/files/2389424/FLAnimatedImageXamarin-1.0.01.zip)

Trying to build with SDWebImage.iOS.dll along side FLAnimatedImageXamarin.dll

Results in 

error MT4116: Could not register the assembly 'SDWebImage.iOS': error MT4118: Cannot register two managed types ('SDWebImage.FLAnimatedImage, SDWebImage.iOS' and 'FLAnimatedImageXamarin.FLAnimatedImage, FLAnimatedImageXamarin') with the same native name ('FLAnimatedImage').

[errorLog.txt](https://github.com/xamarin/XamarinComponents/files/2389436/errorLog.txt)

Can you advise on a work around?

Thanks

Regards,
Andrew Benson

> VS bug [#732185](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/732185)

**Comment by andrewbenson92** [comment]
Source: https://github.com/GhostRussia/FLAnimatedImageXamarin/releases/tag/1.0.01

**Comment by newky2k** [comment]
@andrewbenson92  I have assigned @adlair to it to investigate

**Comment by andrewbenson92** [comment]
> @andrewbenson92 I have assigned @adlair to it to investigate

Thank you

**Comment by Redth** [comment]
Moving to @SotoiGhost ... Are these both using Flipboard's FLAnimatedImage as a dependency and bundling it, thus causing the conflict?

**Comment by newky2k** [comment]
@andrewbenson92  Looks like FLAnimatedImage is pulled in via the SDWebImage cocopod

**Comment by newky2k** [comment]
@andrewbenson92  We are binding FLAnimatedImage as part of SDWebImage.  Can you not use the included version?

**Comment by andrewbenson92** [comment]
> @andrewbenson92 We are binding FLAnimatedImage as part of SDWebImage. Can you not use the included version?

Hi, yes I wasn't aware that FLAnimatedImage was in there. Awesome, thanks.
