### ISSUE TITLE
broken links in Mono.Options/README.md

### ISSUE THREAD

**Issue by mcdon-ron** [xamarin/XamarinComponents#457]
The file "https://github.com/xamarin/XamarinComponents/blob/master/XPlat/Mono.Options/README.md" has bad links to "https://github.com/xamarin/XamarinComponents/blob/master/XPlat/Mono.Options/component/GettingStarted.md" and "https://github.com/xamarin/XamarinComponents/blob/master/XPlat/Mono.Options/component/Details.md".

> VS bug [#732184](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/732184)

**Comment by newky2k** [comment]
@mcdon-ron Thanks for the update,  i've assigned @mattleibow  to the issue.  Looks like the component folder was removed in the last update.

Regards

**Comment by titusn** [comment]
not just the components folder, also nuget/ and the source folder is practically empty as well

**Comment by newky2k** [comment]
Fixed with #487
