### ISSUE TITLE
Build fail on Mac OS not on Windows

### ISSUE THREAD

**Issue by ebelrose** [xamarin/XamarinComponents#459]
We are unable to build on Mac OS or through VSTS CI which is Mac OS based.
Here is the error message
obj/Release/android/src/mono/io/fabric/sdk/android/services/events/EventsStorageListenerImplementor.java:8: error: package io.fabric.sdk.android.services.events does not exist

It does build without any issue on Windows.

**Comment by newky2k** [comment]
@ebelrose  could you provide the script that you are using to build this on mac please

Regards

**Comment by newky2k** [comment]
@ebelrose  could you try adding the Xamarin.Android.Crashlytics.Core package and see if that resolves the issue

**Comment by ebelrose** [comment]
It's already added.
I don't know what you mean talking about script.
I just build/run it from Visual Studio.
It's related to #460, I think, same behavior

**Comment by ebelrose** [comment]
Visual Studio Community 2017 for Mac
Version 7.6.7 (build 49)
Installation UUID: c2bfe105-bf10-425c-8fd8-70583757c2f8
Runtime:
	Mono 5.12.0.301 (2018-02/4fe3280bba1) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 512000301

.NET Core
Runtime : /usr/local/share/dotnet/dotnet
Version du runtime : 2.1.2
SDK : /usr/local/share/dotnet/sdk/2.1.302/Sdks
Version du SDK : 2.1.302
SDK MSBuild : /Library/Frameworks/Mono.framework/Versions/5.12.0/lib/mono/msbuild/15.0/bin/Sdks

Xamarin.Android
Version : 9.0.0.20 (Visual Studio Community)
Android SDK: /Users/ebelrose/Library/Android/sdk
	Versions Android prises en charge :
		5.1(Niveau d’API 22)
		7.0(Niveau d’API 24)
		8.1(Niveau d’API 27)

Version de SDK Tools : 26.1.1
Version des outils de plateforme du SDK : 28.0.1
Version des outils de génération du SDK : 28.0.2

Java SDK: /usr
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

Operating System
Mac OS X 10.13.6
Darwin 17.7.0 Darwin Kernel Version 17.7.0
    Thu Jun 21 22:53:14 PDT 2018
    root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64

**Comment by newky2k** [comment]
I've assigned this to @Redth to investigate

**Comment by Redth** [comment]
Duplicate of #460 please post replies in #460 instead.
