### ISSUE TITLE
SDWebImage.iOS webP support iOS12

### ISSUE THREAD

**Issue by ubeerli** [xamarin/XamarinComponents#461]
Hi

The webP support of SDWebImage.iOS 4.4.0 seems to be broken on iOS12. See https://github.com/rs/SDWebImage/releases/tag/4.4.1 
> Fix that WebP (including Animated WebP) decoding issue on iOS 12

Thanks for updating the Xamarin package.

> VS bug [#732182](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/732182)

**Comment by UlrichBodentien** [comment]
@Redth  I am experiencing this issue for iOS 12 devices as well. Are there any plans for an update?

**Comment by Redth** [comment]
Would love community help here!

**Comment by newky2k** [comment]
This has now been updated and merged
