### ISSUE TITLE
Update Glide to the latest

### ISSUE THREAD

**Issue by rubo** [xamarin/XamarinComponents#464]
Currently, the Xamarin.Android.Glide has v4.0.0 while Glide already reached to v4.8.0. Please consider updating, it's a must-have library.

> VS bug [#732178](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/732178)

**Comment by newky2k** [comment]
@rubo we can look to add this in to the roadmap.  If you have the time you could provide an update as a pull request for us to review

**Comment by adrianknight89** [comment]
That last 2017 update raises all the alarm bells for me. Would love to see this updated soon.

**Comment by Redth** [comment]
Would love some community help here!

**Comment by jamesmontemagno** [comment]
Have you seen: https://github.com/jonathanpeppers/glidex maybe we can bring this in officially with @jonathanpeppers ?

**Comment by jonathanpeppers** [comment]
I would love to just drop my binding and use an official Xamarin one.

It's weird I swear I looked for this component, but then ended up binding glide myself.

**Comment by jonathanpeppers** [comment]
I'm using 4.7.0: https://github.com/jonathanpeppers/glidex/blob/8363cade7de117c08b59b51bd63f825aa867e938/glidex/glidex.csproj#L54

And the only other improvement I have is `[assembly:LinkerSafe]`: https://github.com/jonathanpeppers/glidex/blob/8363cade7de117c08b59b51bd63f825aa867e938/glidex/Properties/AssemblyInfo.cs#L16

**Comment by rubo** [comment]
@jonathanpeppers Why does glidex use v4.7.0? No time to update or technical difficulties because of the lack of a single JAR?

**Comment by jonathanpeppers** [comment]
For some reason they quit releasing jar files here: https://github.com/bumptech/glide/releases

**Comment by jonathanpeppers** [comment]
I presume a workaround would be to make a gradle project to download everything from maven and bundle into a single, self-contained jar.

I did that in xamarin-android for r8 here: https://github.com/xamarin/xamarin-android/blob/d7dcc5b5b9c2e2466e4d39769e3dbdf378613c91/src/r8/build.gradle

I've not had time to do this in glidex yet, but I don't know if the components guys here take a different approach.

**Comment by xyfoo** [comment]
> For some reason they quit releasing jar files here: https://github.com/bumptech/glide/releases

I think even an update from v4.0.0 to v4.7.0 is still significant enough for most folks.

**Comment by rubo** [comment]
> Would love some community help here!

@Redth Your turn. Now community would love some help here: #548

**Comment by newky2k** [comment]
@rubo  #554 has been merged and published to nuget

**Comment by rsgrey** [comment]
Plz, update.
Not work with last Xamarin.Android.Support.v4 (28.0.0.3)
