### ISSUE TITLE
[Question] - Are all these awesome plugins going to be added to Xamarin Essentials too?

### ISSUE THREAD

**Issue by stesvis** [xamarin/XamarinComponents#465]
I am going to install the ones I need individually, but it would be great if they were all added to Xamarin Essentials.

**Comment by newky2k** [comment]
@stesvis Essentials won't be including absolutely every plugin and feature that we have.  We are working to add the most important ones that can work across all of the support platforms in a fresh, clean api.  If you have any wishes or suggestions you can add them directly to the Xamarin.Essentials issues list -> https://github.com/xamarin/Essentials/issues  

Regards
