### ISSUE TITLE
io.fabric.sdk.android.services.events.EventsStorageListener

### ISSUE THREAD

**Issue by AhsanSiddique** [xamarin/XamarinComponents#472]
**Error**		
error: package io.fabric.sdk.android.services.events does not exist
io.fabric.sdk.android.services.events.EventsStorageListener

**Comment by newky2k** [comment]
@AhsanSiddique  can you please provide some more context on this and even a sample project that demonstrates the issue.

Regards

**Comment by newky2k** [comment]
Over three weeks and no response

**Comment by acaliaro** [comment]
I have the same problem. I have follow instructions on ReadMe. I have also add Xamarin.GooglePlayServices.Basement,

**Comment by acaliaro** [comment]
Removed Xamarin.GooglePlayServices.Basement, same problem

**Comment by acaliaro** [comment]
[fabricerror.zip](https://github.com/xamarin/XamarinComponents/files/3279832/fabricerror.zip)

can you take a look? thanks

**Comment by EdvinM** [comment]
Same for me. Added latest packages, and all eleven and getting "**package io.fabric.sdk.android.services.events does not exist**". Any info/solution regarding this problem?
