### ISSUE TITLE
Stripe version

### ISSUE THREAD

**Issue by jzeferino** [xamarin/XamarinComponents#473]
What is the version of the current [nuget](https://www.nuget.org/packages/Xamarin.Stripe.iOS/) package for Stripe.iOS?

**Comment by newky2k** [comment]
@jzeferino  it looks like the nuget version number is the same as the stripe version -> https://github.com/xamarin/XamarinComponents/blob/master/XPlat/Stripe/bindings/iOS/build.cake#L7

Regards
