### ISSUE TITLE
Error parsing public key on new devices like the Huawei p20 Pro

### ISSUE THREAD

**Issue by StefanRademakers** [xamarin/XamarinComponents#476]
The expansion and licensing seems to work fine on most devices but I get a ParsingException on the public key on the more newer devices. I'm kinda lost where to look for a solution to this problem.
Is this an exception that happens in the library in more situations, or is it project specific?

Thanks in advance for any info that can be shed on this problem, the crash info is attached below:
Best Regards, Stefan

com.android.org.conscrypt.NativeCrypto.EVP_parse_public_key
NativeCrypto.java - line -2
com.android.org.conscrypt.OpenSSLX509CertificateFactory$ParsingException: Error parsing public key

com.android.org.conscrypt.NativeCrypto.EVP_parse_public_key NativeCrypto.java
com.android.org.conscrypt.OpenSSLKey.getPublicKey OpenSSLKey.java:270
com.android.org.conscrypt.OpenSSLRSAKeyFactory.engineGeneratePublic OpenSSLRSAKeyFactory.java:54
java.security.KeyFactory.generatePublic KeyFactory.java:357
com.google.android.vending.licensing.LicenseChecker.generatePublicKey LicenseChecker.java:113
com.google.android.vending.licensing.LicenseChecker.<init> LicenseChecker.java:94
com.google.android.vending.expansion.downloader.impl.DownloaderService$LVLRunnable.run DownloaderService.java:766
android.os.Handler.handleCallback Handler.java:809
android.os.Handler.dispatchMessage Handler.java:102
android.os.Looper.loop Looper.java:166
android.app.ActivityThread.main ActivityThread.java:7383
java.lang.reflect.Method.invoke Method.java
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run RuntimeInit.java:469
com.android.internal.os.ZygoteInit.main ZygoteInit.java:963

**Comment by newky2k** [comment]
@StefanRademakers  Could you please provide a small sample project that can demonstrate the issue that you are raising and provide some the libraries and platform that you are using and targeting.

Regards

**Comment by newky2k** [comment]
No response for three weeks, closing
