### ISSUE TITLE
Xamarin Universal Library - One Place for all xamarin great resources

### ISSUE THREAD

**Issue by luismts** [xamarin/XamarinComponents#478]
We are trying to bring you all together so the community has only one place for all xamarin great resources. So, we are reaching out to see how it can all be pulled together as there is some overlap.

Repository: https://github.com/xamarinuniverse/XamarinUniversalLibrary

**Comment by Redth** [comment]
Wondering what you're asking for exactly here?

Can you give some more info as to what you're proposing here?

**Comment by luismts** [comment]
@Redth yeah, of course.

As I said, we are trying to add the whole xamarin resources in one place for the community. A place well structured. So, you can be part of this project and **migrating** this list to the [Xamarin Universal Library](https://github.com/xamarinuniverse/XamarinUniversalLibrary). 

In the same way, there are some projects related to this but first, we are asking for support from the community. So, this will be a really nice resource in the library.

**Comment by Redth** [comment]
Thanks, if you are interested in adding items from this list to your curated list please feel free to do so!

**Comment by luismts** [comment]
Yes, we can do that. But that not the purpose. We want all of you there
