### ISSUE TITLE
[AzureMessaging] Update Android to 0.5

### ISSUE THREAD

**Issue by Redth** [xamarin/XamarinComponents#480]
There was an update to 0.5 of the Azure Notification Hubs SDK to 0.5 to support some changes in Android P.  We need to update the bindings as per the request here: https://github.com/Azure/azure-notificationhubs/issues/46#issuecomment-439148662

> VS bug [#730673](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/730673)

**Comment by MatthewGerber** [comment]
Hello - this is blocking a release. Any sense on the timeline for [the 0.5 NuGet](https://www.nuget.org/packages/Xamarin.Azure.NotificationHubs.Android)?

**Comment by newky2k** [comment]
@MatthewGerber I'm looking at it now shouldn't take too long

**Comment by MatthewGerber** [comment]
@newky2k Thanks! I see the commit has been made. How long does it take the NuGet to update?

**Comment by newky2k** [comment]
@MatthewGerber  Its live now -> https://www.nuget.org/packages/Xamarin.Azure.NotificationHubs.Android/

**Comment by MatthewGerber** [comment]
@newky2k Thank you!

**Comment by MatthewGerber** [comment]
@newky2k Confirming that this fixes the problem.
