### ISSUE TITLE
Card.io iOS problem

### ISSUE THREAD

**Issue by jzeferino** [xamarin/XamarinComponents#486]
Im running the Card.io iOS sample with iOS 11, the app runs but it doesn't detect any card I've provided.

Can someone else test this?

> VS bug [#739493](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/739493)

**Comment by newky2k** [comment]
@jzeferino Could you please provide a small sample project that demonstrates this issue.

Regards

**Comment by jzeferino** [comment]
[Here](https://github.com/jzeferino/Xamarin.CardIo.Sample) is a iOS sample, it is using the last version of card.io. Please test this on a real device.

**Comment by jzeferino** [comment]
Can you replicate this? @newky2k?

**Comment by Redth** [comment]
I highly suspect this is an issue with Card.IO itself, but we'll have a look.

**Comment by jzeferino** [comment]
Thanks for looking up at this. I will try to give a try in the original sample from Card.IO.

**Comment by jzeferino** [comment]
I've executed the sample from [card-io](https://github.com/card-io/card.io-iOS-SDK/tree/master/SampleApp) and encountered the same issue. I opened a issue in card.io [here](https://github.com/card-io/card.io-iOS-SDK/issues/295)

**Comment by Redth** [comment]
Thanks for updating, closing as this is an upstream issue.
