### ISSUE TITLE
Mono.Options source code is missing

### ISSUE THREAD

**Issue by Xyaneon** [xamarin/XamarinComponents#488]
The [source](https://github.com/xamarin/XamarinComponents/tree/master/XPlat/Mono.Options/source) folder contains .sln and .csproj files, but no actual source code files. This was previously mentioned on #457 [here](https://github.com/xamarin/XamarinComponents/issues/457#issuecomment-428172316).

> VS bug [#738670](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/738670)

**Comment by newky2k** [comment]
@Xyaneon  the source code is actually downloaded from the main mono repo.

https://github.com/xamarin/XamarinComponents/blob/master/XPlat/Mono.Options/build.cake#L18 

This repo is basically a shell to allow this to be published as a nuget package

Regards
