### ISSUE TITLE
Plugin for Jailbreak and Root detection

### ISSUE THREAD

**Issue by talhaa91** [xamarin/XamarinComponents#49]
Can we get a plugin for this?

**Comment by DiomedesDominguez** [comment]
How can you do that with native code?

**Comment by pranart** [comment]
This is DependencyService For Check Jailbreak

https://xamarin.in.th/%E0%B9%80%E0%B8%8A%E0%B9%87%E0%B8%84%E0%B8%A7%E0%B9%88%E0%B8%B2%E0%B9%80%E0%B8%84%E0%B8%A3%E0%B8%B7%E0%B9%88%E0%B8%AD%E0%B8%87%E0%B8%96%E0%B8%B9%E0%B8%81-jailbreak-%E0%B8%AB%E0%B8%A3%E0%B8%B7%E0%B8%AD%E0%B9%80%E0%B8%9B%E0%B8%A5%E0%B9%88%E0%B8%B2-%E0%B8%94%E0%B9%89%E0%B8%A7%E0%B8%A2-xamarin-ihardwaresecurity-9e5e58975754

**Comment by newky2k** [comment]
@pranart  has suggested some code or you can propose it as a new feature of Xamarin.Esssentials

https://github.com/xamarin/Essentials/wiki/Proposing-New-Features
