### ISSUE TITLE
Properly bind Kotlin StdLib so it is exposed in C#

### ISSUE THREAD

**Issue by jgold6** [xamarin/XamarinComponents#493]
It seems that the Xamarin.Kotlin.StdLib nuget still only binds version 1.1.4-3

Current version is 1.3.10: https://mvnrepository.com/artifact/org.jetbrains.kotlin/kotlin-stdlib

And it seems there was a big change in 1.3 in that kotlin-runtime was moved to kotlin-stdlib: https://mvnrepository.com/artifact/org.jetbrains.kotlin/kotlin-runtime

> VS bug [#740678](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/740678)

**Comment by jgold6** [comment]
@Redth 
After a conversation with Jon P on slack, apparently this is not a true binding but rather an easy way to add the jar to binding projects? Which might be fine as long as none of the kotlin types are used in classes that are being bound to C#.

Jon P noted that there is a bindings generator bug that prevents "brain-dead simple" binding of this library.

**Comment by Redth** [comment]
We will take a look at this in our next sprint.

**Comment by nicolasbaron** [comment]
Gentlemen, thank you for looking into this issue! Not sure if I can interrupt you here but just wanted to know when is the next sprint planned to be delivered (when can we use the new version resolving this situation we've encountered too)?

**Comment by jom16antonio** [comment]
Hi. Once fixed, will this be able to resolve issues with 
Java.Lang.NoClassDefFoundError
Failed resolution of: Lcom/xxx/xxx$Companion$1;

**Comment by nicolasbaron** [comment]
@jom16antonio hi there, would you please tell me if it has been solved?
We are the client who raised the issue.
Thank you!

**Comment by nebuto** [comment]
Hi,
Still have the issue on Kotlin callback type not recognized, did you include the "brain-dead simple" binding ?
```
../BINDINGSGENERATOR: Warning BG8800: Unknown parameter type kotlin.jvm.functions.Function1<? super java.lang.Boolean, kotlin.Unit> in method SetOnSomethingChangedListener in managed type MyFramework (BG8800)
```

**Comment by Redth** [comment]
We need to expose some APIs here...

**Comment by Redth** [comment]
We have a newer version which exposes some API's on nuget: https://www.nuget.org/packages/Xamarin.Kotlin.StdLib/1.3.31

Please open another issue if there are more API's needed in the binding.
