### ISSUE TITLE
Xamarin.SDWebImage 3.7.5 -> 4.4.0 broke animated gif support

### ISSUE THREAD

**Issue by jantanis** [xamarin/XamarinComponents#494]
[AnimatedGifSample.zip](https://github.com/xamarin/XamarinComponents/files/2651925/AnimatedGifSample.zip)
After we've upgraded Xamarin.SDWebImage 3.7.5 -> 4.4.0 animated gifs stopped working on iOS.

The provided example has 3.7.5 in it and is working. The UIButton shows the animated gif. When you upgrade tot 4.4.0 the button shows plain blue.

> VS bug [#742850](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/742850)

**Comment by newky2k** [comment]
@jantanis  Could you please provide a sample that demonstrates the problem please.

Regards

**Comment by jantanis** [comment]
@newky2k please see the updated post.

**Comment by Redth** [comment]
We'll have a look, but it sounds like this might be a problem with SDWebImage itself.
