### ISSUE TITLE
Can not resolve reference: `Xamarin.Android.Fabric`, referenced by `Xamarin.Android.Crashlytics`.

### ISSUE THREAD

**Issue by Carl-Wen** [xamarin/XamarinComponents#496]
I create a new simple project, and try to add reference `Xamarin.Android.Crashlytics`. I search  `Xamarin.Android.Crashlytics` in NuGet manage and click install button. Then it give me error message:
Can not resolve reference: `Xamarin.Android.Fabric`, referenced by `Xamarin.Android.Crashlytics`. Please add a NuGet package or assembly reference for `Xamarin.Android.Fabric`, or remove the reference to `Xamarin.Android.Crashlytics`.

> VS bug [#751306](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/751306)

**Comment by newky2k** [comment]
@Carl-Wen  is this still an issue?  Looking at the dependencies  Xamarin.Android.Fabric is listed as a dependency of  Xamarin.Android.Crashlytics.

**Comment by Dooks123** [comment]
Sometimes installing the required packages one by one works.
So first try and install `Xamarin.Android.Fabric` then the rest.

**Comment by newky2k** [comment]
@Dooks123  what are you system details?  are you using windows or mac?

**Comment by Dooks123** [comment]
@newky2k I run windows with VS2017 and nuget 3.0
I have noticed previously that sometimes when you install packages, it doesn't always install the dependencies with it. ie. I have two solutions of different apps open at the same time, compare and install packages, then some of the packages doesn't install automatically.

For crashlytics, you have to install:
- Xamarin.Android.Fabric
- Xamarin.Android.Crashlytics
- Xamarin.Android.Crashlytics.Beta
- Xamarin.Android.Crashlytics.Answers
- Xamarin.Android.Crashlytics.Core

**Comment by newky2k** [comment]
@Dooks123  is there a reason why you're running nuget 3.x?  Nuget is now up to version 5.1, and i think 4.2 was included with VS 2017

**Comment by newky2k** [comment]
No response closing
