### ISSUE TITLE
Publish Google VR packages

### ISSUE THREAD

**Issue by MarcBruins** [xamarin/XamarinComponents#50]
The Google VR components are not published on Nuget there is however a nuspec file. Would be nice if they could be submitted to Nuget

**Comment by bholmes** [comment]
agree.

Have you used them?  Are they working for you?  Any feedback before publish would be appreciated.

**Comment by shankar12** [comment]
Any update over nuget  release of google VR sdk?

**Comment by SiemensS23** [comment]
So nothing about here for a Nuget Component for Google VR SDK library, also update about 1.3.0. version?

**Comment by newky2k** [comment]
This is now out of date, the Google VR is up to 1.15.0.0
