### ISSUE TITLE
[Material Components] OverlayWindow lacks frame constructor

### ISSUE THREAD

**Issue by J-Swift** [xamarin/XamarinComponents#508]
Sorry I'm not opening a PR for this, I'm still very new to Xamarin and totally clueless on bindings. `OverlayWindow` inherits from `UIWindow`, but doesn't seem to expose the frame constructor. I was expecting to be able to new up an instance like this:

`new MaterialComponents.OverlayWindow(UIScreen.MainScreen.Bounds);`

> VS bug [#805946](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/805946)

**Comment by newky2k** [comment]
@J-Swift  i think we have released at least one update to material components.  Can you check in the latest version and if this is still an issue re log it using the new issue templates
