### ISSUE TITLE
Upgrade DZNEmptyDataSet to version 1.8.1

### ISSUE THREAD

**Issue by Wenfengcheng** [xamarin/XamarinComponents#510]
Upgrade DZNEmptyDataSet to version 1.8.1 

> #500

> VS bug [#780049](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/780049)

**Comment by newky2k** [comment]
@Wenfengcheng Thanks for your patience.  This has now been approved and pushed to Nuget.org

Thanks for your help
