### ISSUE TITLE
Error: The error target "Default" was not found

### ISSUE THREAD

**Issue by PSLHimaBindu** [xamarin/XamarinComponents#519]
Downloaded code based from Tag: Xamarin.Build.Download-0.4.11

Tried to build project .\build.psi from power shell.

I get the following error,
Error: The target "Default" was not found

Can you please suggest me ways to fix error and build project?

Thanks in advance.

**Comment by PSLHimaBindu** [comment]
I am learning to build applications using Xamarin Components starting with ARCore, Can you please suggest me branch that I can clone?

**Comment by newky2k** [comment]
@PSLHimaBindu  You should just download the last master as we vetted everything and its stable.

You should then change directory and the call the build script from the root location.  For example ARCore is in Android/ARCore so on mac you would do ../../build.cake -t=libs to build the libs

on windows it would be similar but using powershell
