### ISSUE TITLE
[Sugestion] Add better Bluetooth manager

### ISSUE THREAD

**Issue by DiomedesDominguez** [xamarin/XamarinComponents#52]
It would be a nice plugin for Xamarin create a better cross-platform implementation for a Bluetooth manager, instead of creating, for example in Xamarin.Android a BluetoothAdapter, a BluetoothSocket, a BluetoothDevice, a Stream for outputs and another for inputs.

For our apps we know common data like MAC address or the name of the device, so the plugin can just search for that device, and we only going to concentrate for the inputs and outputs methods.

**Comment by aritchie** [comment]
https://github.com/aritchie/bluetoothle 
The answer to your request.  I'd love to get this on the list too
