### ISSUE TITLE
Error: The assembly 'Cake.XCode, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'

### ISSUE THREAD

**Issue by anuuradha** [xamarin/XamarinComponents#520]
Error: The assembly 'Cake.XCode, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'
is referencing an older version of Cake.Core (0.17.0).
This assembly must reference at least Cake.Core version 0.26.0.
Another option is to downgrade Cake to an earlier version.
It's not recommended, but you can explicitly opt out of assembly verification
by configuring the Skip Verification setting to true
(i.e. command line parameter "--settings_skipverification=true",
environment variable "CAKE_SETTINGS_SKIPVERIFICATION=true",
read more about configuration at https://cakebuild.net/docs/fundamentals/conf

did anyone faced this issue while building using Cake?

> VS bug [#785736](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/785736)

**Comment by newky2k** [comment]
@anuuradha  Try deleting the tools folder and rebuilding.  It will force cake to be redownloaded.

You might wanna redownload the if branch if you've had it a while too.
