### ISSUE TITLE
Adding Crashlytics to an Android project produces "always the same" provider name

### ISSUE THREAD

**Issue by jonathanpeppers** [xamarin/XamarinComponents#522]
_From @jonathanantoine on February 4, 2019 10:14_

### Xamarin.Android Version (eg: 6.0):
Version: 9.1.5.1 (Visual Studio Enterprise)
Android SDK: /Users/jonathanantoine/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		4.4 (API level 19)
		7.1 (API level 25)
		8.1 (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.1
SDK Build Tools Version: 28.0.3

### Operating System & Version (eg: Mac OSX 10.11):
Mac OS Mojave : 10.14.2 (18C54)

###  Visual Studio Information 
Version 7.7.4 (build 1)
Installation UUID: 37cc8c40-d076-4974-8bf8-344f707f4364
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 516000221

### Google Play Services Version (eg: 8.4.0):
60.1142.1

### Describe your Issue:
Adding the Xamarin.Android.Crashlytics nuget package creates an Android provider which always get the same id/name/authorities independently of the app. This unique id is always "dollar_openBracket_applicationId_closeBracket".

Example :     `<provider android:name="com.crashlytics.android.CrashlyticsInitProvider" android:authorities="dollar_openBracket_applicationId_closeBracket" android:exported="false" android:initOrder="100" />`

If any other Xamarin app uses Crashlytics on the user device, the app's installation will fail... 

### Steps to Reproduce (with link to sample solution if possible):

1. Install a first Xamarin App with the Xamarin.Android.Crashlytics on a device / the simulator.
1. Install a second Xamarin App with the Xamarin.Android.Crashlytics on a device / the simulator --> Installation will failed. 

### Include any relevant Exception Stack traces, build logs, adb logs:
Error log when trying to deploy the second app 
```

 error ADB0000:  Deployment failed
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.Debugging.targets(502,2): error ADB0000: Mono.AndroidTools.InstallFailedException: Failure [INSTALL_FAILED_CONFLICTING_PROVIDER: Package couldn't be installed in /data/app/com.replaced.TVST-WVS3TklyYvLAe7HmzyZM1Q==: Can't install because provider name dollar_openBracket_applicationId_closeBracket (in package com.replaced.TVST) is already used by com.replaced.Podcasts]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.Debugging.targets(502,2): error ADB0000:   at Mono.AndroidTools.Internal.AdbOutputParsing.CheckInstallSuccess (System.String output, System.String packageName) [0x00159] in <a5d76a0989aa4289a65da210dedf9b89>:0 
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.Debugging.targets(502,2): error ADB0000:   at Mono.AndroidTools.AndroidDevice+<>c__DisplayClass95_0.<InstallPackage>b__0 (System.Threading.Tasks.Task`1[TResult] t) [0x0001c] in <a5d76a0989aa4289a65da210dedf9b89>:0 
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.Debugging.targets(502,2): error ADB0000:   at System.Threading.Tasks.ContinuationTaskFromResultTask`1[TAntecedentResult].InnerInvoke () [0x00024] in <98fac219bd4e453693d76fda7bd96ab0>:0 
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.Debugging.targets(502,2): error ADB0000:   at System.Threading.Tasks.Task.Execute () [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-06/external/bockbuild/builds/mono-x64/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:2344 
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.Debugging.targets(502,2): error ADB0010: Failure [INSTALL_FAILED_CONFLICTING_PROVIDER: Package couldn't be installed in /data/app/com.replaced.TVST-WVS3TklyYvLAe7HmzyZM1Q==: Can't install because provider name dollar_openBracket_applicationId_closeBracket (in package com.replaced.TVST) is already used by com.replaced.Podcasts]
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.Debugging.targets(502,2): error ADB0010:   at Mono.AndroidTools.Internal.AdbOutputParsing.CheckInstallSuccess (System.String output, System.String packageName) [0x00159] in <a5d76a0989aa4289a65da210dedf9b89>:0 
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.Debugging.targets(502,2): error ADB0010:   at Mono.AndroidTools.AndroidDevice+<>c__DisplayClass95_0.<InstallPackage>b__0 (System.Threading.Tasks.Task`1[TResult] t) [0x0001c] in <a5d76a0989aa4289a65da210dedf9b89>:0 
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.Debugging.targets(502,2): error ADB0010:   at System.Threading.Tasks.ContinuationTaskFromResultTask`1[TAntecedentResult].InnerInvoke () [0x00024] in <98fac219bd4e453693d76fda7bd96ab0>:0 
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.Debugging.targets(502,2): error ADB0010:   at System.Threading.Tasks.Task.Execute () [0x00000] in /Users/builder/jenkins/workspace/build-package-osx-mono/2018-06/external/bockbuild/builds/mono-x64/external/corert/src/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs:2344 
    3 Warning(s)
    2 Error(s)

```

_Copied from original issue: xamarin/GooglePlayServicesComponents#176_

**Comment by jonathanpeppers** [comment]
/cc @Redth 

So I built this Crashlytics sample:
```
.\build.ps1 -t external
.\build.ps1 -t libs
.\build.ps1 -t samples
```

And sure enough, the final merged manifest, `obj\Release\android\AndroidManifest.xml`:
```xml
<provider android:name="com.crashlytics.android.CrashlyticsInitProvider" android:authorities="com.xamarin.crashlyticssample.crashlyticsinitprovider" android:exported="false" android:initOrder="100" />
<provider android:name="com.crashlytics.android.CrashlyticsInitProvider" android:authorities="dollar_openBracket_applicationId_closeBracket" android:exported="false" android:initOrder="100" />
```

So then I looked through `lp` and found:
```
> cat 'obj\Debug\81\lp\7\jl\aapt\AndroidManifest.xml' | select-string applicationId

        <provider android:name="com.crashlytics.android.CrashlyticsInitProvider" android:authorities="dollar_openBracket_applicationId_closeBracket" android:exported="false" android:initOrder="100" />
```
The manifest file up one directory looks correct:
```
> cat 'obj\Debug\81\lp\7\jl\AndroidManifest.xml' | select-string applicationId

        <provider android:name="com.crashlytics.android.CrashlyticsInitProvider" android:authorities="${applicationId}.crashlyticsinitprovider" android:exported="false" android:initOrder="100" />
```

It seems like XBD is using the `aapt/AndroidManifest.xml` files, from the binlog:
```
XamarinBuildAndroidAarRestore
    Found 10 entries in C:\Users\jopepper\AppData\Local\XamarinBuildDownloadCache\fabric-1.4.3\fabric.aar
    Renaming: classes.jar to library_project_imports/classes.jar
    Renaming: proguard.txt to library_project_imports/proguard.txt
    Renaming: aapt/AndroidManifest.xml to library_project_imports/aapt/AndroidManifest.xml
    Renaming: AndroidManifest.xml to library_project_imports/AndroidManifest.xml
    Found 9 entries in C:\Users\jopepper\AppData\Local\XamarinBuildDownloadCache\crashlytics-2.9.4\crashlytics.aar
    Renaming: classes.jar to library_project_imports/classes.jar
    Renaming: aapt/AndroidManifest.xml to library_project_imports/aapt/AndroidManifest.xml
    Renaming: AndroidManifest.xml to library_project_imports/AndroidManifest.xml
    Found 9 entries in C:\Users\jopepper\AppData\Local\XamarinBuildDownloadCache\crashlyticscore-2.6.3\crashlytics-core.aar
    Renaming: classes.jar to library_project_imports/classes.jar
    Renaming: aapt/AndroidManifest.xml to library_project_imports/aapt/AndroidManifest.xml
    Renaming: AndroidManifest.xml to library_project_imports/AndroidManifest.xml
    Found 10 entries in C:\Users\jopepper\AppData\Local\XamarinBuildDownloadCache\crashlyticsanswers-1.4.2\crashlytics-answers.aar
    Renaming: classes.jar to library_project_imports/classes.jar
    Renaming: proguard.txt to library_project_imports/proguard.txt
    Renaming: aapt/AndroidManifest.xml to library_project_imports/aapt/AndroidManifest.xml
    Renaming: AndroidManifest.xml to library_project_imports/AndroidManifest.xml
    Found 9 entries in C:\Users\jopepper\AppData\Local\XamarinBuildDownloadCache\crashlyticsbeta-1.2.9\crashlytics-beta.aar
    Renaming: classes.jar to library_project_imports/classes.jar
    Renaming: aapt/AndroidManifest.xml to library_project_imports/aapt/AndroidManifest.xml
    Renaming: AndroidManifest.xml to library_project_imports/AndroidManifest.xml
```

Is this code not working as expected? https://github.com/xamarin/XamarinComponents/blob/90f0d01302a16fd2befd603274bc459b8f1c9ac5/Util/Xamarin.Build.Download/source/Xamarin.Build.Download/XamarinBuildAndroidAarRestore.cs#L38-L47

Project has `<PackageReference Include="Xamarin.Build.Download" Version="0.4.11" />`.

Here is my log: [msbuild.zip](https://github.com/xamarin/XamarinComponents/files/2830629/msbuild.zip)

**Comment by Redth** [comment]
@jonathanpeppers can you try this one? https://www.nuget.org/packages/Xamarin.Build.Download/0.4.12-preview3

**Comment by jonathanpeppers** [comment]
@Redth ok yeah, I went through and updated the `<PackageReference/>` for XBD in ~5 projects, then it worked.

I guess we can close this? We need to promote 0.4.12 to stable?

**Comment by jonathanantoine** [comment]
@Redth @jonathanpeppers (it seems there is only Jonathan in here 😂) Thanks for the quick investigation! Do you know when it will be set as stable so I can use it in production?

**Comment by jonathanpeppers** [comment]
@jonathanantoine if it fixes your build (or app) I wouldn't worry about the `preview` label: use it.

**Comment by jonathanantoine** [comment]
@jonathanpeppers it does not fix my issue. I still have this line in my manifest : 
 `   <provider android:name="com.crashlytics.android.CrashlyticsInitProvider" android:authorities="dollar_openBracket_applicationId_closeBracket" android:exported="false" android:initOrder="100" />`

By the way I also have a line which seems "good" : 

    `<provider android:name="com.crashlytics.android.CrashlyticsInitProvider" android:authorities="com.jonathanantoine.Podcasts.crashlyticsinitprovider" android:exported="false" android:initOrder="100" />`


What can I do ?

**Comment by jonathanpeppers** [comment]
@jonathanantoine you will have to `Rebuild` (or perhaps delete your `bin` and `obj` directories).

Once that `aapt\AndroidManifest.xml` file is there on disk, it will be used. The fix in Xamarin.Build.Download 0.4.12, looks like it skips extracting this file--but won't delete it.

If you still can't get it to work, attach a [diagnostic MSBuild log](https://docs.microsoft.com/en-us/xamarin/android/troubleshooting/troubleshooting#diagnostic-msbuild-output), and I'll take a look.

**Comment by jonathanantoine** [comment]
I do still the issue even after a clean/rebuild. The logs are here : [build.log.zip](https://github.com/xamarin/XamarinComponents/files/2833991/build.log.zip)

**Comment by jonathanpeppers** [comment]
@Redth I don't see this in his log:
```
Found aapt/AndroidManifest.xml, skipping...
```
But it is showing up in mine from the Crashlytics sample in this repo: [updated.zip](https://github.com/xamarin/XamarinComponents/files/2834103/updated.zip)

**Comment by jonathanantoine** [comment]
Any idea @Redth  ?

**Comment by jonathanantoine** [comment]
Can I do something to help ? I have more and more users not able to install my app because of this tooling issue :(

**Comment by Redth** [comment]
Did you try actually deleting the bin/obj folder and rebuilding?

**Comment by jonathanantoine** [comment]
I deleted bin and obj folders, cleaned solution and restarted Visual Studio For Mac. Do you have a sample solution project known to be working you would like me to test on my machine?

**Comment by jonathanantoine** [comment]
Ok so I tried again on my AppCenter build and everything is allright. I guess we can close this issue.

Thanks for your help !
