### ISSUE TITLE
YouTubePlayer

### ISSUE THREAD

**Issue by lumisoftusa** [xamarin/XamarinComponents#523]
Hi,

I am trying to use you-tube player i downloaded the complete bundle from github and goto youtube project open it and restore the packages and finally when i build the project i am getting this error.

Severity	Code	Description	Project	File	Line	Suppression State
Error		Bundle Resource 'Assets.bundle\Assets\YTPlayerView-iframe-player.html' not found on disk (should be at 'E:\New folder (3)\XamarinComponents-master\XPlat\YouTube.Player\ios\externals\Pods\youtube-ios-player-helper\youtube-ios-player-helper\Assets.bundle\Assets\YTPlayerView-iframe-player.html')	YouTube.Player.iOS

**Comment by newky2k** [comment]
@lumisoftusa  have you built the externals target?  this will download and install the pod(on iOS) which will probably install the mising files too.

Are you doing this on windows or mac?

**Comment by lumisoftusa** [comment]
Hi,

ya i am using Windows. 

Well i removed the reference and download the nuget package of YouTube.ios everything is fine.
Now currently i am trying to send the video url from Xamarin Forms and using Dependency functionality target the ios project and play the youtube video. Do you have any resource or what you can help me so  that would be great and it would save my time in Research and development;.

I have one more question infect i need your feedback because i didn't find the exact details from Youtube.
Can we use the Youtube video direct url to play youtube file naively.
If you any knowledge regarding this so that would be great to share with me.


Regards

**Comment by lumisoftusa** [comment]
Thanks guys!

I am successfully integrate the youtube player into Xamarin Forms.
