### ISSUE TITLE
[Material Components] Plans to offer Android version?

### ISSUE THREAD

**Issue by J-Swift** [xamarin/XamarinComponents#528]
You guys graciously offer the bindings for the iOS version of the official MaterialDesignComponents (MDC) library, but I can't seem to find anywhere online where you specify whether you plan on offer bindings for the Android version. Am I missing this somewhere?

Please note I'm not referring to the material design as provided by the Android Support Library, but rather the 'official' Google implementation of a material component library (https://github.com/material-components/material-components-android). I think providing the android bindings will go a long way to enabling easy cross platform design without needing to use XamarinForms.

Thank you either way, you guys do great work!

**Comment by mattleibow** [comment]
The Android bits are in a weird state. It is half in Support, half in AndroidX and half here. I _think_ these controls are folded into the Support/AndroidX packages, and this is just a reference. @Redth will have to comment.

**Comment by J-Swift** [comment]
@mattleibow My understanding is that AndroidX is a replacement for Android.Support packages. The MDC library is Googles attempt to provide out-of-the-box implementations of their Material design spec as a component library. So under the covers it likely leverages AndroidX features to create configurable UI components. If you look at the bottom of a [Component page](https://material.io/design/components/text-fields.html#implementation) in the Material Design spec you will see that the 'ios' and 'android' sections ultimately link to the [material-components-android](https://github.com/material-components/material-components-android) and [material-components-ios](https://github.com/material-components/material-components-ios) projects.

The big benefit of them doing this is that then it lowers the bar for cross-platform apps to use Material design (assuming `material-components-ios` and `material-components-android` are aligned). That's why I would love to see the android version picked up here, so I can begin to align platform implementations without needing to hand-tweak extra design on Android.

Again, thank you for considering! I'd love to be able to contribute but I still haven't found a good resource on generating bindings (any suggestions?).

**Comment by Redth** [comment]
We will be creating bindings for `com.google.android.material` as part of the AndroidX effort (You can find it on the AndroidX branch of xamarin/AndroidSupportComponents - https://github.com/xamarin/AndroidSupportComponents/tree/AndroidX/source/com.google.android.material/material ).

These basically are the renamed versions of the old Android.Support.Design packages (which you can use already for Material components on Android).
