### ISSUE TITLE
Does Xamarin.Build.Download nuget has overwrite feature

### ISSUE THREAD

**Issue by jessejiang0214** [xamarin/XamarinComponents#529]
The download nuget seems have an issue, when the old aar already exist, but the name is different.
Like the old aar name is ```play-services-base-15.0.1.aar``` and the task declare like this
```
    <ItemGroup>
      <XamarinBuildDownload Include="playservices-15.0.1/playservicesbase">
        <Url>https://dl.google.com/dl/android/maven2/com/google/android/gms/play-services-base/15.0.1/play-services-base-15.0.1.aar</Url>
        <ToFile>playservicesbase-15.0.1.aar</ToFile>
        <Kind>Uncompressed</Kind>
      </XamarinBuildDownload>
    </ItemGroup>
```
The download nuget cannot create a new aar named ```playservicesbase-15.0.1.aar```

> VS bug [#805947](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/805947)

**Comment by Redth** [comment]
The idea is that if it's already been downloaded we don't want to download it again.  I'm not sure what the use case here is, but since the aar already exists you shouldn't need to redownload it.
