### ISSUE TITLE
YouTubePlayer Crash

### ISSUE THREAD

**Issue by lumisoftusa** [xamarin/XamarinComponents#530]
Hi,

I am successfully integrated YouTubePlayer inot IOS and Android using Xamarin Forms.

I have a media gallery an display video on the section of the video from the Video Id
It works perfect but sometimes app crashed . I am using Hockey app for app crash reports.
I didn't get the exact error detail so i am attaching the error log what i got from Hockey app sdk.
Please help me out and give me a chance of thanks.

Regards

[ErrorLog.docx](https://github.com/xamarin/XamarinComponents/files/2876106/ErrorLog.docx)

**Comment by Redth** [comment]
This looks like an issue with the upstream YouTube iOS library.  Please log the issue upstream with them.
