### ISSUE TITLE
Not seeing release information for Mono.Options

### ISSUE THREAD

**Issue by jaydeept** [xamarin/XamarinComponents#531]
Hello,

We are using Mono.Options, version 5.3.0.1 for our .Net Core related project. For legal clearance of this package, we need this to be available in Release field.

**Comment by Redth** [comment]
Not sure what you're looking for exactly.  You want us to put up a GitHub Release for that version?  All the MIT licenses are in place and the source can be found here: https://github.com/mono/mono/blob/master/mcs/class/Mono.Options/Mono.Options/Options.cs

**Comment by jaydeept** [comment]
Hi @Redth ,

Yes basically something like below:
https://github.com/aspnet/AspNetCore/releases

**Comment by newky2k** [comment]
@jaydeept  sorry for the delay but here is the release of Mono.Options -> https://github.com/xamarin/XamarinComponents/releases/tag/5.12.0.273

We will be doing thing now for all component publications

Thanks
