### ISSUE TITLE
Xamarin IOS Dlls not found in Sample Xamarin App!

### ISSUE THREAD

**Issue by MarkTRooney** [xamarin/XamarinComponents#546]
Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not compile the file(s) '/Users/mark/Library/Caches/Xamarin/mtbs/builds/eShopOnContainers.iOS/7394127333854abddbb08e10b636d75d/obj/iPhone/Debug/mtouch-cache/armv7/Xamarin.iOS.dll.s'. Please file a bug report at http://bugzilla.xamarin.com	eShopOnContainers.iOS

**Comment by newky2k** [comment]
@MarkTRooney  can you provide some more details about the sample you are using, the platform and if this is still and issue.

Thanks in advance

**Comment by newky2k** [comment]
no more information provided
