### ISSUE TITLE
CREATEMULTIDEXMAINDEXCLASSLIST : error : Can't read

### ISSUE THREAD

**Issue by coosmiyn** [xamarin/XamarinComponents#549]
I just upgraded the project to Android 9 and got this error when I try to build it:
CREATEMULTIDEXMAINDEXCLASSLIST : error : Can't read [C:\Users\{user}\source\repos\{project}\{solution}\{solution}.Android\obj\Debug\81\lp\64\jl\__reference__guava.jar(;;;;;;!META-INF/MANIFEST.MF)] (invalid entry size (expected 67324752 but got 2367 bytes))

It seems it is coming form the Guava NuGet when it is installed, and I also have all the dependencies installed and the latest verions. 
The build is not finished. Any ideas?
Many thanks

EDIT: Fixed. Deleted the obj and bin files from the project folder, updated some NuGets which for some reasons either didn't show available today or just weren't there yet, and cleaned and built the solution.

**Comment by DigitalArtifex** [comment]
Receiving the exact error, including quoted expected and read sizes. I have already manually deleted all obj and bin files, clean and rebuilt my solution, upgraded all components, including to the preview versions of Auth and Firestore. Targeting 9.0 android, minimum version being 8.1. 

What am I missing here?

**Comment by coosmiyn** [comment]
@DigitalArtifex forgot I still got the problem and fixed it for good back then. What did it for me after all was downgrading the Google Guava NuGet. It got an update that day and that update was seeming to cause the problem. I remember reporting that or asking for a solution. Try that and I guess it should work.

**Comment by DigitalArtifex** [comment]
Thank you so much for your response coodmiyn..you have literally saved the day, my sanity, and my hair. I can confirm that downgrading to 27.1.0 from 27.1.0.1 works. I'll leave my other issue open and update it with the work-around as the bug still stands
