### ISSUE TITLE
Xamarin.Android.Support.v8.Renderscript arm64-v8a support?

### ISSUE THREAD

**Issue by amdlopes** [xamarin/XamarinComponents#552]
### Xamarin.Android Version (eg: 6.0):
8.3.3.2

### Operating System & Version (eg: Mac OSX 10.11):
10.13.3 (17D47)

### Support Libraries Version (eg: 23.3.0):
Xamarin.Android.Support.v8.Renderscript (27.0.2.1)

### Describe your Issue:
No apparent support to arm64-v8a - missing 64 bit versions of librsjni.so and libRSSupport.so into compiled APK. 
64 bit support is now needed as Google requires app to have 64 bit versions of native libraries after Aug 2019. 

### Steps to Reproduce (with link to sample solution if possible):
Not really applicable. 

I have a Xamarin project that binds to some Java code using my own renderscript code/libs generated from an Android Studio native project.

### Include any relevant Exception Stack traces, build logs, adb logs:
Java.Lang.Exception : Error loading RS jni library: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/NovarumDX.Imaging.Android.Test-7o0ERAMIq0vBtXJ-R58XXA==/base.apk"],nativeLibraryDirectories=[/data/app/NovarumDX.Imaging.Android.Test-7o0ERAMIq0vBtXJ-R58XXA==/lib/arm64, /system/fake-libs64, /data/app/NovarumDX.Imaging.Android.Test-7o0ERAMIq0vBtXJ-R58XXA==/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]] couldn't find "librsjni.so" Support lib API: 2301

Solution ive tried:
I've tried adding the librsjni.so and libRSSupport.so into my Xamarin project under arm64-v8a/ folder so i can ensure they are shipped with the apk. 
The native libs are indeed in the apk if that is done but the initialisation of the Android.Support.v8.Renderscript() object is now broken - which means the Nuget package Xamarin.Android.Support.v8.Renderscript is not binding to those native libraries correctly (ie no 64 bit support)

If my analysis is correct you should be aware that this blocks any Xamarin Android app using v8.support being released to app store after Aug 2019.

Please let me know your thoughts.

Antonio

**Comment by newky2k** [comment]
@amdlopes  Is this issue still causing you problems?  were you able to put together a sample that replicated the issue?

Thanks in advance

**Comment by amdlopes** [comment]
@Redth @newky2k

Like I said before I ended up not using the support library anymore and restructure my projects to the Android.Renderscript API.

It's not hard to replicate the issue... I've already mentioned it in my second post. I'll quote:
"You could just create a template xamarin android app, install version xamarin.android.support.v8.renderscript 27.0.2.1, build and generate the APK for both arch's (32 and 64 bit) , unzip/extract the APK and confirm that the native support libs (librsjni and librssupport) exist under libs/armeabi-v7a but do not under libs/arm64-v8a."

Very straightforward and will allow to evaluate the issue and potential fixes.

**Comment by santihcc** [comment]
I just found the same issue after including the arm64-v8a ABI to my current project. The 64 libraries are correctly bundled but the one linking to an Android Binding project that I need to use and is working fine when only using armeabi-v7a. 
Has anyone found a solution to this? 

Thanks

**Comment by Redth** [comment]
I believe 28.0.0.3 of this package resolves these issues.  Please open a new issue if there is anything still not working.
