### ISSUE TITLE
Xamarin Gigya - Google SignIn not firing Gigya AccountDidLogin callback

### ISSUE THREAD

**Issue by ivocarminati** [xamarin/XamarinComponents#553]
Hi all,

we are integrating Gigya SDK in our iOS and Android Xamarin apps, but we are experiencing problems with the Google Social login integration on iOS.

After the binding of the native SDK using the code from: https://github.com/xamarin/XamarinComponents/tree/master/XPlat/Gigya/iOS
for implementing the Google SignIn we followed the steps below:

- we have downloaded the following packages from Nuget: 
	- Xamarin.Build.Download
	- Xamarin.Google.iOS.Core 
	- Xamarin.Google.iOS.SignIn
	and the relative dependencies automatically downloaded from Xamarin package manager

- we have added the GoogleService-Info.plist in the root directory of the project. It contains:
	<key>CLIENT_ID</key>
	<string>the client id</string>
	<key>REVERSED_CLIENT_ID</key>
	<string>the reversed client id</string>
	<key>PLIST_VERSION</key>
	<string>1</string>
	<key>BUNDLE_ID</key>
	<string>the bundle of our app</string>

- we have added the following fields in the iOS Info.plist file:

	<key>LSApplicationQueriesSchemes</key>
	<array>
		<string>fb</string>
		<string>fbapi</string>
		<string>fbapi20130214</string>
		<string>fbapi20130410</string>
		<string>fbapi20130702</string>
		<string>fbapi20131010</string>
		<string>fbapi20131219</string>
		<string>fbapi20140410</string>
		<string>fbapi20140116</string>
		<string>fbapi20150313</string>
		<string>fbapi20150629</string>
		<string>fbapi20160328</string>
		<string>fbauth</string>
		<string>fbauth2</string>
		<string>fb-messenger-api20140430</string>
		<string>com.google.gppconsent</string>
		<string>gplus</string>
		<string>com-google-gidconsent-google</string>
		<string>com-google-gidconsent-youtube</string>
		<string>com-google-gidconsent</string>
		<string>com.google.gppconsent.2.4.1</string>
		<string>com.google.gppconsent.2.4.0</string>
		<string>googlechrome</string>
		<string>googlechrome-x-callback</string>
	</array>
	<key>GoogleClientID</key>
	<string>the client id</string>
	<key>CFBundleURLTypes</key>
	<array>
		<dict>
			<key>CFBundleURLSchemes</key>
			<array>
				<string>the reversed client id</string>
			</array>
		</dict>
	</array>

The problem is that the login flow seems to work correctly, but after the successfull login we have two main problems:

- the registration screen after successfull login is not returned from Gigya

- the callback 
		public void AccountDidLogin(GSResponse accountResponse)
   from Gigya is not fired (the same callback works correctly with facebook credentials and platform credentials)

With the same settings on an Xcode project with the native Gigya SDK all the flow works as expected without these problems.
Can you please help us on this?

PS: Do you know if is there a way to enable Gigya console logs?

I hope we can find a solution together.
Thanks in advance.
Best regards,

Ivo

**Comment by newky2k** [comment]
@ivocarminati  could you provide a sample that demonstrates this issue, if its still occuring.

Thanks in advance

**Comment by Redth** [comment]
Closing due to lack of information.  Please open a new issue if this is still a problem.
