### ISSUE TITLE
Xamarin.TwitterImagePipeline NuGet MT4116 and MT4118 errors during build

### ISSUE THREAD

**Issue by dpjustdoit** [xamarin/XamarinComponents#563]
Hi guys, 
After integration of this NuGet, unable to build for device:
```
Error MT4116: Could not register the assembly 'TwitterImagePipeline': error MT4118: Cannot register two managed types ('TwitterImagePipeline.TIPImagePipelineInspectionResultEntryBase, TwitterImagePipeline' and 'TwitterImagePipeline.TIPImagePipelineInspectionResultEntry, TwitterImagePipeline') with the same native name ('TIPImagePipelineInspectionResultEntry'). (MT4116)
```

According to this: 
https://github.com/xamarin/xamarin-macios/issues/3875
A change is needed here for the `Name` property:
https://github.com/xamarin/XamarinComponents/blob/c058e7d68b15a6bb5a022dfbd58f90b523593403/iOS/TwitterImagePipeline/source/TwitterImagePipeline/ApiDefinition.cs#L1482

Thanks

> VS bug [#866865](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/866865)

**Comment by newky2k** [comment]
@dpjustdoit Could you provide a PR with the change to fix this?

**Comment by dpjustdoit** [comment]
@newky2k Yeah

**Comment by newky2k** [comment]
@dpjustdoit  can you sign the sla on the PR so we can merge it please.

Once thats done i can merge and update the component

Thanks

**Comment by newky2k** [comment]
This has been published to nuget
