### ISSUE TITLE
New Google Place API Nuget Package Release Date

### ISSUE THREAD

**Issue by dechosenuchenna** [xamarin/XamarinComponents#566]
I Appreciate the Xamarin Team for all your efforts so far. It is just one month before google will totally discontinue the former and Deprecated Places SDK.  There is currently no news about the new API, especially for those of us that have this as a special feature in our apps, we are getting worried already.

**_I want to enquire how soon the release of the new Nuget Package will come on the RoadMap._**

**Comment by newky2k** [comment]
@dechosenuchenna We are currently work on the update and should be available soon

Thank you for your patience
