### ISSUE TITLE
How to use SDWebImage in MvxTableViewCell?

### ISSUE THREAD

**Issue by risingworld777** [xamarin/XamarinComponents#582]
I am using SDWebImage in MvvmCross project.
I am going to use `ImgView` as SDWebImage
```
this.DelayBind(() =>
            {
                var set = this.CreateBindingSet<ProductCell, ProductModel>();
                set.Bind(ImgView).To(m => m.ImgUrl);
                set.Apply();
            });
```

**Comment by newky2k** [comment]
@risingworld777  Are you asking if this will work or saying that it doesn't?

Thanks

**Comment by risingworld777** [comment]
@newky2k  I am going to bind image url to the SDWebImage. But I can't find bindable property in SDWebImage

**Comment by newky2k** [comment]
I'm not sure its possible.  This is how an image loaded, as an example,
https://github.com/xamarin/XamarinComponents/blob/master/iOS/SDWebImage/samples/SDWebImageSimpleSample/SDWebImageSimpleSample/ViewController.cs#L24-L30  and this not done via a property.

Thanks
Dave

**Comment by risingworld777** [comment]
@newky2k  Then how to get local cached image path using SDWebImage?
