### ISSUE TITLE
Support to YouTubePlayerSupportFragment

### ISSUE THREAD

**Issue by AlenToma** [xamarin/XamarinComponents#588]
Hi we need support for YouTubePlayerSupportFragment.

I cant find the source code or i could have implemented it.

Please help

**Comment by newky2k** [comment]
@AlenToma the source code for the binding is here -> https://github.com/xamarin/XamarinComponents/tree/master/XPlat/YouTube.Player/android/source/YouTube.Player.Android  but i'm not sure why the binding doesn't include that class already.

**Comment by AlenToma** [comment]
I know the binding exist(for some reason) but there is no C# actual class exist in the nuget package for YouTubePlayerSupportFragment. 

SupportFragment exist in [Xamarin.Android.Support.Fragment](https://www.nuget.org/packages/Xamarin.Android.Support.Fragment/)

**Comment by newky2k** [comment]
@AlenToma looking at the api.xml it looks its in the api and in the api.xml.fixed(both are in the obj folder) files which are the the result of the Metadata.xml file.

Not sure why its not showing up

**Comment by AlenToma** [comment]
Friend.
I hade decomiled the [Xamarin.YouTube.Player.Android](https://www.nuget.org/packages/Xamarin.YouTube.Player.Android/) dll and loked inside and there is no `YouTubePlayerSupportFragment`, there is only `YouTubePlayerFragment` which inherit from `Fragment`
in android >8 we will need YouTubePlayerFragment that inherit from `Android.Support.V4.App.Fragment` so we could use it for `SupportFragmentManager`

**Comment by newky2k** [comment]
@AlenToma  its because the binding generator fails on YouTubePlayerSupportFragment -> BINDINGSGENERATOR : warning BG8604: top ancestor YouTubePlayerSupportFragment not found for nested type YouTube.Player.YouTubePlayerSupportFragment.A.

**Comment by newky2k** [comment]
@AlenToma  Found the issue,  the binding doesn't reference the Android Support Libraries.  I'm working on an update now

**Comment by AlenToma** [comment]
Yes i know, i tried to explain that, you also need to build a new class call it `YouTubePlayerSupportFragment ` that inherit from `Android.Support.V4.App.Fragment`.

Anyway will test the new update when its done.

**Comment by AlenToma** [comment]
Is this really fixed ? there is no nuget package [Xamarin.YouTube.Player.Android 1.2.3](https://www.nuget.org/packages/Xamarin.YouTube.Player.Android/)

**Comment by AlenToma** [comment]
What is the status on this issue?

**Comment by AlenToma** [comment]
I saw that you have added     `<attr path="/api/package[@name='com.google.android.youtube.player']/class[@name='YouTubePlayerSupportFragment.a']" name="visibility">public</attr>`

but nuget package need to be uppgraded to, and also inlude a new class `YouTubePlayerSupportFragment` in the nuget package.

Im i right or im i understanding this wrong ?

**Comment by bitzeal-johan** [comment]
Found a solutoin that worked for me.

The binding generation for YouTubeSupportFragment failed because it depends on a class that is in Xamarin.Android.Arch.Lifecycle.Extensions nuget package. Added the package and it worked.

**Comment by AlenToma** [comment]
Yes i have fixed this a long time ago.
