### ISSUE TITLE
Crashlytics for Android generates conflicting provider

### ISSUE THREAD

**Issue by Dooks123** [xamarin/XamarinComponents#590]
Like [#444](https://github.com/xamarin/XamarinComponents/issues/444) and [#2141](https://github.com/xamarin/xamarin-android/issues/2141)

        <provider
            android:name="com.crashlytics.android.CrashlyticsInitProvider"
            android:exported="false"
            android:authorities="bpu.aimei.crashlyticsinitprovider"
            android:initOrder="100" />

        <provider
            android:name="com.crashlytics.android.CrashlyticsInitProvider"
            android:exported="false"
            android:authorities="dollar_openBracket_applicationId_closeBracket"
            android:initOrder="100" />

I'm still getting the issue where it generates the duplicate providers where one is correct but a second one with dollar_openBracket_applicationId_closeBracket is also added.

Visual Studio 2017

- Xamarin.Android.Fabric v1.4.3
- Xamarin.Android.Crashlytics.Core v2.6.3
- Xamarin.Android.Crashlytics.Beta v1.2.9
- Xamarin.Android.Crashlytics.Answers v1.4.2
- Xamarin.Android.Crashlytics v2.9.4.1
- Xamarin.Build.Download v0.4.11

**Comment by Dooks123** [comment]
Hi, Is there any update on the matter?

With this issue, I can not publish two different apps using Fabric in Xamarin.

A user can not possibly install two apps at the same time with this issue. Even If I didn't develop both apps, and someone else developed an app which implements fabric and the user tries to install my app, the user will get an error on the Play Store.

Please, this is urgent.

This line should be excluded somehow... 

    <provider android:name="com.crashlytics.android.CrashlyticsInitProvider" android:authorities="dollar_openBracket_applicationId_closeBracket" android:exported="false" android:initOrder="100" />

**Comment by Dooks123** [comment]
I have done more testing on this and got it to build without the duplicate "bad" line.

In the `Obj/[debug/release]/[monoversion=90]/`  you end up with folders:
- android
- assets
...
- lp <--- IN THIS FOLDER
- proguard
...

In the `lp` folder you have a bunch of folders `0, 1, 2 ....`
In my case `28/jl/AndroidManifest.xml` is the manifest for `Fabric` and looks like the following:

    <?xml version="1.0" encoding="utf-8"?>
    <manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.crashlytics.android" android:versionCode="1" android:versionName="2.9.4">
        <uses-sdk android:minSdkVersion="9" />
        <uses-permission android:name="android.permission.INTERNET" />
        <application>
            <provider android:name="com.crashlytics.android.CrashlyticsInitProvider" android:authorities="${applicationId}.crashlyticsinitprovider" android:exported="false" android:initOrder="100" />
        </application>
    </manifest>

If I modify the `<provider...` line and simply `Build` my project, the modification shows up in the final `AndroidManifest.xml` but the "bad" line still co-exists:

    <provider android:name="com.crashlytics.android.CrashlyticsInitProvider" android:authorities="com.my.app.crashlyticsinitprovider" android:exported="true" android:initOrder="100" />
    <provider android:name="com.crashlytics.android.CrashlyticsInitProvider" android:authorities="dollar_openBracket_applicationId_closeBracket" android:exported="false" android:initOrder="100" />

If I remove the entire `<application />` tag, the "good" line is gone from the final `AndroidManifest.xml` but the bad line is still there.

Then still in folder `.../lp/28/jl` there is another folder `aapt` and there is also a `AndroidManifest.xml` file and it looks like this (contains the "bad" line):

    <?xml version="1.0" encoding="utf-8"?>
    <manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.crashlytics.android" android:versionCode="1" android:versionName="2.9.4">
        <uses-sdk android:minSdkVersion="9" />
        <uses-permission android:name="android.permission.INTERNET" />
        <application>
            <provider android:name="com.crashlytics.android.CrashlyticsInitProvider" android:authorities="dollar_openBracket_applicationId_closeBracket" android:exported="false" android:initOrder="100" />
        </application>`
    </manifest>

If I once again remove the entire `<application />` tag, the "bad" line is gone out of the final `AndroidManifest.xml`

In order for me to `Archive` the app without the "bad" line:
1. Rebuild project (this removes any changes made to files in `obj`)
2. Go to the `lp` folder containing the bad manifest (again 28 in my case - didn't change) and remove the `<provider... android:authorities="dollar_openBracket_applicationId_closeBracket" ... />` line
3. Archive project
4. Success

**Comment by marcelobrunolara** [comment]
Thank you @Dooks123! Your suggested workaround works well on my projects! Besides it's a little complicated to execute these steps, it really saves who isn't working with VS 2019 yet!

**Comment by Redth** [comment]
https://github.com/xamarin/xamarin-android/issues/2141 should have fixed this issue awhile back.  Please open a new issue if it's still occurring.
