### ISSUE TITLE
ARCore HelloAR sample fails to build

### ISSUE THREAD

**Issue by dmarnel** [xamarin/XamarinComponents#595]
I'm seeing cake.build errors:

Error downloading 'XamarinComponent.1.1.0.65' from 'https://api.nuget.org/v3-flatcontainer/xamarincomponent/1.1.0.65/xamarincomponent.1.1.0.65.nupkg'.
crypt32.dll
Error downloading 'XamarinComponent.1.1.0.65' from 'https://api.nuget.org/v3-flatcontainer/xamarincomponent/1.1.0.65/xamarincomponent.1.1.0.65.nupkg'.
crypt32.dll
Install failed. Rolling back...
Error: One or more errors occurred. (Error downloading 'XamarinComponent.1.1.0.65' from 'https://api.nuget.org/v3-flatcontainer/xamarincomponent/1.1.0.65/xamarincomponent.1.1.0.65.nupkg'.)
Error downloading 'XamarinComponent.1.1.0.65' from 'https://api.nuget.org/v3-flatcontainer/xamarincomponent/1.1.0.65/xamarincomponent.1.1.0.65.nupkg'.

**Comment by newky2k** [comment]
@dmarnel  can you please provide the details of how your build the sample as its new and has never 
been linked to the old component store at any point

**Comment by dmarnel** [comment]
As per the README.md in the ARCORE folder, I'm running the following command from the command line on my Mac:

sh ../../build.sh --target=libs

**Comment by newky2k** [comment]
ah ok,  i've seen this error before and its not specifically to do with ARCore, there was an issue with download nugets via cake.

try deleting tools in the root folder so it forces cake and the other deps to be redownloaded and let me know if that makes a difference

**Comment by dmarnel** [comment]
I've found a work-around for this by just copying the ARCORE/externals folder from my Windows machine to the same location on my Mac.

**Comment by dmarnel** [comment]
Delete the entire tools folder? How will the redownloading be initiated?

**Comment by dmarnel** [comment]
Okay, I deleted the tools folder and reran the script. This is what I got:

dons-imac:ARCore dmarnel$ sh ../../build.sh --target=libs
using local cake.packages.config...
Downloading NuGet...
Feeds used:
  /Users/dmarnel/.nuget/packages/
  https://api.nuget.org/v3/index.json

Restoring NuGet package Cake.0.27.0.
Adding package 'Cake.0.27.0' to folder '/Users/dmarnel/Development/Xamarin/XamarinComponents/tools'
Added package 'Cake.0.27.0' to folder '/Users/dmarnel/Development/Xamarin/XamarinComponents/tools'
Error downloading 'XamarinComponent.1.1.0.65' from 'https://api.nuget.org/v3-flatcontainer/xamarincomponent/1.1.0.65/xamarincomponent.1.1.0.65.nupkg'.
crypt32.dll
Error downloading 'XamarinComponent.1.1.0.65' from 'https://api.nuget.org/v3-flatcontainer/xamarincomponent/1.1.0.65/xamarincomponent.1.1.0.65.nupkg'.
crypt32.dll
Install failed. Rolling back...
Error: One or more errors occurred. (Error downloading 'XamarinComponent.1.1.0.65' from 'https://api.nuget.org/v3-flatcontainer/xamarincomponent/1.1.0.65/xamarincomponent.1.1.0.65.nupkg'.)
	Error downloading 'XamarinComponent.1.1.0.65' from 'https://api.nuget.org/v3-flatcontainer/xamarincomponent/1.1.0.65/xamarincomponent.1.1.0.65.nupkg'.

**Comment by newky2k** [comment]
@dmarnel  the root cake scripts re download everything. 

I've just run the same query on my mac and it build without issue. Leave it with me and i'll investigate

**Comment by dmarnel** [comment]
Thanks, Dave. Not sure what you  mean by “leave it with me …” Are you asking for a copy of my script?

**Comment by newky2k** [comment]
@dmarnel  I had this issue before and it doesn't occur now so i'll look into why it works.  Are you up to date with VS4M and the xamarin  bits?

You could manually install the packages with nuget, which will put them in the cache

**Comment by dmarnel** [comment]
Yes, this was a first-time install.

**Comment by Redth** [comment]
We've since reworked build scripts here to use dotnet cake.  Closing the issue as it should not be a problem now.
