### ISSUE TITLE
not Found ARFragment HelloSceneorm

### ISSUE THREAD

**Issue by houssame98** [xamarin/XamarinComponents#599]
I can't find the ARFragment object in the HelloSceneform repository, does anyone have any replies?

**Comment by newky2k** [comment]
@houssame98  Can you please provide some further details about what you are doing and what/where it is missing from.  We recently updated to 1.9.0 are you using that version?

**Comment by Redth** [comment]
Closing due to lack of response, please open a new issue if you need help.
