### ISSUE TITLE
Telephony

### ISSUE THREAD

**Issue by ghuntley** [xamarin/XamarinComponents#6]
Heads up so others don't duplicate efforts, am currently working on this:

```
Telephony will be a xplat library that provides email, sms, voice and video
call functionality. Supports Xamarin.iOS, Xamarin.Android, Windows Phone 8/8.1
(Silverlight and WPA)
```

https://github.com/ghuntley/telephony

If anyone is keen to do api review on the Email class - specifically comments about attachments that would be appreciated.

**Comment by jamesmontemagno** [comment]
Closing for now, seems like Messaging and this could combine perhaps?
