### ISSUE TITLE
[Suggestion] Google FlexBoxLayout 

### ISSUE THREAD

**Issue by btripp** [xamarin/XamarinComponents#60]
Hey Guys,

I created a binding library and turned it into a Nuget. It is basically a wrapper of Googles new FlexBoxLayout.

https://github.com/btripp/FlexboxLayoutXamarinBindingAndroid

**Comment by newky2k** [comment]
@btripp  if you want to include this in the repo, please feel free to prepare a PR so we can review, test and merge it.
