### ISSUE TITLE
Assets namespace is missing from Google.AR.Sceneform.Namespace

### ISSUE THREAD

**Issue by jgold6** [xamarin/XamarinComponents#609]
Looking at the transform here:
https://github.com/xamarin/XamarinComponents/blob/master/Android/SceneForm/source/Assets/Transforms/Metadata.xml

```
<metadata>
     <attr path="/api/package[@name='com.google.ar.sceneform.assets']" name="managedName">Google.AR.Sceneform.Assets</attr>
  
    <attr path="/api/package[@name='com.google.ar.sceneform.assets']/class[@name='RenderableSource']/method[@name='call' and count(parameter)=0]" name="return">Java.Lang.Object</attr>
       
</metadata>
```

I would assume that I could find the RenderableSource class inside the Google.AR.Sceneform.Assets namespace, but after adding the [Xamarin.Android.Sceneform.Assets nuget preview package](https://www.nuget.org/packages/Xamarin.Android.SceneForm.Assets/1.9.0-preview1) I do not see the Assets namespace in the Google.AR.Sceneform namespace, hence the RenderableSource class is not available. 

Looking inside the Xamarin.Android.Sceneform.Assets.dll assembly, the top level namespace is Com.Google.Sceneform_assets, and there is only a `D` class inside:

![Screen Shot 2019-07-16 at 10 12 06 AM](https://user-images.githubusercontent.com/4606509/61326334-36fbce00-a7b2-11e9-81e1-915cb1755a34.png)

I also wonder why the package names use Xamarin.Android.XX, while ARCore uses Xamarin.Google.ARCore, etc. Since they are related it seems to me that all packages should start with Xamarin.Google rather than Xamarin.Android? Might make them all easier to find, but that is another issue.

**Comment by a-iafrate** [comment]
I need to use this class and i have the same problem, please fix it!

**Comment by a-iafrate** [comment]
@craigktreasure, you have done a great job with other issue, can you also solve this so we have all component for arcore?

Thanks!!!

**Comment by craigktreasure** [comment]
I don't know. I'll have to see what I have time for next week. I've burnt all of my extra curricular time this week I'm afraid.
