### ISSUE TITLE
Google Play Console  - Your app doesn't have any in-app products yet ( GoogleBillingClient)

### ISSUE THREAD

**Issue by RoshanBhore** [xamarin/XamarinComponents#632]
GoogleBillingClient
after adding permission of  
   android:name="com.android.vending.BILLING"
in android manifest . I uploaded app for internal testing to Google Play Console. In manage products I am getting **"Your app doesn't have any in-app products yet."**  Will it be visible after adding Google Payments merchant account or i can still use for testing purpose.

**Comment by newky2k** [comment]
@RoshanBhore looking on the internet, https://stackoverflow.com/questions/52174945/googleplay-console-app-doesnt-have-any-in-app-products-yet/52207732, it looks like you have to setup the merchant account first.

**Comment by RoshanBhore** [comment]
Okay.. Thank You :-)

**Comment by Sohel3798** [comment]
Hello @RoshanBhore I'm facing the same issue like i can't see Create subscription button on play console how you fixed it can you pls help me 

<img width="653" alt="Screenshot 2023-12-22 at 10 21 04 AM" src="https://github.com/xamarin/XamarinComponents/assets/93022175/b0336559-2629-4703-89c1-c5e1886c08e0">

**Comment by tenkyu** [comment]
@Sohel3798 did you find any solution, I have the same screen on my console.

**Comment by Sohel3798** [comment]
> @Sohel3798 did you find any solution, I have the same screen on my console.

please check your 📪

**Comment by ygnoh** [comment]
@Sohel3798 Can you tell me how to fix it?
