### ISSUE TITLE
TensorFlow Lite Add GpuDelegate bindings

### ISSUE THREAD

**Issue by Redth** [xamarin/XamarinComponents#634]
From NuGet feedback:

Could you, please, add bindings for TFLite GpuDelegate (https://www.tensorflow.org/lite/performance/gpu) to the Xamarin.Tensorflow.Lite package?
A couple months ago, TFLite introduced GpuDelegate class - a powerful mechanism for running TFLite models on a wide variety of mobile GPUs. I personally tested it on my Google Pixel 2 and got 2.5-3x performance improvement with MobileNet V1 as well as with SSD_MobileNet.
The original article can be found here: https://arxiv.org/abs/1907.01989
Thank you.

**Comment by moljac** [comment]
Seems like DONE

**Comment by OutSorcerer** [comment]
@Redth, could you please share a small example with `GpuDelegate` if `Xamarin.TensorFlow.Lite.Gpu` worked for you?

@moljac, looks like there is an issue with `Xamarin.TensorFlow.Lite.Gpu`, could you please check https://github.com/xamarin/XamarinComponents/issues/876?

**Comment by OutSorcerer** [comment]
Answering my own question, the way to use GpuDelegate in Xamarin is 

```csharp
var gpuDelegate = new Xamarin.TensorFlow.Lite.GPU.GpuDelegate();
Xamarin.TensorFlow.Lite.Interpreter.Options options = new Xamarin.TensorFlow.Lite.Interpreter.Options().AddDelegate(gpuDelegate);
var interpreter = new Xamarin.TensorFlow.Lite.Interpreter(mappedByteBuffer, options);
```

It is important that the versions of `Xamarin.TensorFlow.Lite.Gpu` is `2.1.0.1` or later (more accurately, ` 2.0.0.1`, `1.15.0.1`, `1.14.0.1` also have the fix, [see](https://github.com/xamarin/XamarinComponents/issues/876#issuecomment-631909849)).

See the full example here: https://github.com/OutSorcerer/MushroomDetector/blob/fix/MushroomDetector.Android/TensorflowClassifier.cs#L26
