### ISSUE TITLE
Youtube.Player IOS can not play some videos

### ISSUE THREAD

**Issue by Ngoc-Quang** [xamarin/XamarinComponents#639]
Same as the title. After implement this library on nuget. Most of youtube link can play. But some video cannot play on IOS (Ex: video id **5eMRpJ2D8tg** )

This bug also occur on example source code.
Will you have plan to fix it?

Thanks.

**Comment by newky2k** [comment]
@Ngoc-Quang do the same video work on the native youtube player library?

**Comment by Ngoc-Quang** [comment]
@newky2k Yes, this video can play on youtube native application

**Comment by Redth** [comment]
Unless Google addresses it in their library I'm afraid there's very little we can do to fix this.
