### ISSUE TITLE
MWPhotoBrowser does not work with storyboards

### ISSUE THREAD

**Issue by bholmes** [xamarin/XamarinComponents#64]
Getting reports in the comments

https://components.xamarin.com/view/MWPhotoBrowser

**Comment by bholmes** [comment]
May be related to [42473](https://bugzilla.xamarin.com/show_bug.cgi?id=42473).  The workaround is to disable incremental builds.

**Comment by newky2k** [comment]
This issue should be resolved now with https://bugzilla.xamarin.com/show_bug.cgi?id=42473.
