### ISSUE TITLE
OpenId fails to build

### ISSUE THREAD

**Issue by johnvowles** [xamarin/XamarinComponents#644]
Hi there,

I'm trying to change the OpenId component to use AppAuth v0.94 in order to get it working on iOS 12, but I'm getting the following cake build error (even before making any changes):

F:/Downloads/XamarinComponents/XPlat/OpenId/build.cake(109,36): error
CS1503: Argument 2: cannot convert from
'System.Collections.Generic.IReadOnlyList<Cake.Core.ICakeTaskInfo>' to
'System.Collections.Generic.IReadOnlyList<Cake.Core.CakeTask>'
Error: Error(s) occurred when compiling build script:
F:/Downloads/XamarinComponents/XPlat/OpenId/build.cake(109,36): error
CS1503: Argument 2: cannot convert from
'System.Collections.Generic.IReadOnlyList<Cake.Core.ICakeTaskInfo>' to
'System.Collections.Generic.IReadOnlyList<Cake.Core.CakeTask>'

This is happening on both Windows & Mac.

**Comment by PetrUshanov** [comment]
Hi,

I have the same problem trying to build Android/ARCore.

**Comment by newky2k** [comment]
@johnvowles @PetrUshanov  What commands are you using to build the cake files?

**Comment by Redth** [comment]
Closing due to lack of response, please open a new issue if you still need help.
