### ISSUE TITLE
MapboxSDK.Android Manifest includes features and permissions it might not need to

### ISSUE THREAD

**Issue by ekarcnevets** [xamarin/XamarinComponents#65]
The 'Getting Started' page for the Xamarin Mapbox SDK (https://components.xamarin.com/gettingstarted/mapboxsdk) implies that the 'Access Coarse Location' and 'Access Fine Location' are optional permissions. 

I have used the SDK in an App which doesn't require showing the user's location on the map, so I haven't added those permissions to my own manifest. However, upon uploading it to the play store, it wants to add these as new permissions. After some investigation I tracked them down in the manifest for the SDK itself (https://github.com/xamarin/XamarinComponents/blob/301b121b06ee6267d5136d481d0788d3009c1054/XPlat/Mapbox/Android/source/MapboxSDK.Android/Additions/Manifest.cs).

Would it make sense to remove these, along with the Wifi hardware feature as they aren't explicitly required by apps which use the SDK? Thanks :+1:

**Comment by newky2k** [comment]
The wifi seems to be a requirement of the underlying library, but if you want to create a PR with the reduced set of permissions we can look into it further.
