### ISSUE TITLE
[Material Componenets] Problem with TextField & MultiLineTextField's Floating PlaceHolder

### ISSUE THREAD

**Issue by AyonAB** [xamarin/XamarinComponents#659]
Floating placeholder of TextField and MultiLineTextField is kinda creating trouble. If you quickly switch between two TextFields, the floating placeholders get struck in Floating Enabled State. 
That means even if the TextField doesn't contain any text, the placeholder still stays floated.
I came to find that the iOS library also had this issue but it has been fixed in some commit long ago.
![Screenshot (3)](https://user-images.githubusercontent.com/30872214/64150658-4f997380-ce46-11e9-9f51-dd7f30f029d8.png)

**Comment by newky2k** [comment]
#664 I've started the process of updating material components to the latest version

**Comment by logeshpalani33** [comment]
when this issue fixed @Redth

**Comment by newky2k** [comment]
@AyonAB @logeshpalani98  We have released a pre-release version of Material Components v92 to nuget ->  https://www.nuget.org/packages/Xamarin.iOS.MaterialComponents/92.0.0-rc1.  Can you see if this is still and issue with the new version please.

**Comment by AyonAB** [comment]
@newky2k  It seems working fine now. Tried with both StoryBoard & Programmatically. But MaterialSamples should have a TextField guide to start with.

**Comment by newky2k** [comment]
Fixed in v92

**Comment by logeshpalani33** [comment]
having same problem 

![Image-1](https://user-images.githubusercontent.com/24875197/72127485-d67ecf80-3395-11ea-9e24-f73433c06ca8.jpg)

**Comment by AyonAB** [comment]
@logeshpalani98 It only happens with iOS 12 or lower iOS versions. Seems to be working fine with iOS 13 devices.
