### ISSUE TITLE
Material Components iOS update to version 88.2.0

### ISSUE THREAD

**Issue by MarvinFrankenfeld** [xamarin/XamarinComponents#662]
Are there any plans to update Material Components iOS to version 88.2.0?

If so, what is the time frame?

Best regards,
Marvin

**Comment by newky2k** [comment]
#664 I've started the process of updating material components to the latest version

**Comment by Redth** [comment]
Working on an update to 0.92.  Closing this issue for now as the PR previously mentioned will be used to track progress.
