### ISSUE TITLE
[Material Components] OverlayWindow lacks frame constructor

### ISSUE THREAD

**Issue by J-Swift** [xamarin/XamarinComponents#665]
#508 was closed but I just took at look at `Xamarin.iOS.MaterialComponents` v72.2.0.1 and it appears that the OverlayWindow still lacks a frame constructor. i.e. I can't do this:

`new MaterialComponents.OverlayWindow(UIScreen.MainScreen.Bounds);`

**Comment by J-Swift** [comment]
Possibly a stupid question, but if I wanted to open a PR for adding the binding, I don't just hand edit `iOS/MaterialComponents/source/MaterialComponents/ApiDefinition.cs` do I? I assume that is machine generated by some process?

If it's hand-edited then I can take care of the fix : ) Otherwise, I'm not sure how I can assist.

**Comment by SotoiGhost** [comment]
@J-Swift The file is hand-edited. Feel free to edit it and create a PR of it. Thanks for your contributions!

**Comment by newky2k** [comment]
@J-Swift  I added this to the v92 release which is available as a pre-release on Nuget -> https://www.nuget.org/packages/Xamarin.iOS.MaterialComponents/92.0.0-rc1
