### ISSUE TITLE
How to build locally?

### ISSUE THREAD

**Issue by craigktreasure** [xamarin/XamarinComponents#669]
It appears that the build scripts (`build.ps1` and `build.sh`) have been removed. I'm trying to update ARCore and SceneForm, but I'm a bit lost without those scripts (I'm new to cake). The README docs still reference the old build scripts and has not been updated. Can someone fill me in on how to build locally so that I can validate my changes? I'm happy to update the README for ARCore and SceneForm with my changes.

@Redth or @mattleibow?

**Comment by Redth** [comment]
Hey apologies, the README never was updated when we switched over.  Take a look at the readme now and let us know if you're able to build, thanks!

**Comment by craigktreasure** [comment]
Thank you!
