### ISSUE TITLE
Problem with Binding

### ISSUE THREAD

**Issue by shewison** [xamarin/XamarinComponents#674]
Hi,

I'm trying to create a binding for the Zebra iOS SDK. Which is available here:

[Zebra iOS SDK](https://www.zebra.com/us/en/support-downloads/software/developer-tools/scanner-sdk-for-iOS.html)

I'm running sharpie version:

3.4.23-4cde014

I'm running the following command:

`sharpie bind *.h -sdk iphoneos13.0`

I'm getting the following error:

`Unsupported clang availability platform: 'macCatalyst'`

I can find no information specifically on this error in conjunction with the macCatalyst platform.

**Comment by newky2k** [comment]
@shewison mac catalyst is the name of the framework that allows iPad apps to run on Mac.  You'll neee to have the macos catalina installed (which has not been released yet) to be able to run it.

Cheers
Dave
