### ISSUE TITLE
Error with the connection string as described

### ISSUE THREAD

**Issue by RazvanEmilR** [xamarin/XamarinComponents#690]
A typical Azure connection string looks like this:
Endpoint=sb://namespace.servicebus.windows.net/;SharedAccessKeyName=ListenSharedPolicyName;SharedAccessKey=AccessKey

Its not clear how to properly create the connection string in the sample provided from the 
connection string above.

Trying like below I got the following error once:

**Could not initialize an instance of the type 'Foundation.NSUrl': the native 'initWithString:' method returned nil.**

And most of the times this error:

**> ================================================================= 	Native Crash Reporting
> ================================================================= Got a SIGSEGV while executing native code. This usually indicates a fatal
> error in the mono runtime or one of the native libraries  used by your
> application.
> =================================================================
> 
> ================================================================= 	Native stacktrace:
> ================================================================= 	0x10473c190 -
> /private/var/containers/Bundle/Application/3DE84EC0-A042-42E6-8301-B233D104676A/MyAppName.iOS.app/MyAppName.iOS
> : (null) 	0x104732a00 -
> /private/var/containers/Bundle/Application/3DE84EC0-A042-42E6-8301-B233D104676A/MyAppName.iOS.app/MyAppName.iOS
> : (null) 	0x10473fc54 -
> /private/var/containers/Bundle/Application/3DE84EC0-A042-42E6-8301-B233D104676A/MyAppName.iOS.app/MyAppName.iOS
> : mono_pmip 	0x197a47894 - /usr/lib/system/libsystem_platform.dylib :
> <redacted> 	0x10299027c -
> /private/var/containers/Bundle/Application/3DE84EC0-A042-42E6-8301-B233D104676A/MyAppName.iOS.app/MyAppName.iOS
> : (null) 	0x1029903c4 -
> /private/var/containers/Bundle/Application/3DE84EC0-A042-42E6-8301-B233D104676A/MyAppName.iOS.app/MyAppName.iOS
> : (null) 	0x102997b70 -
> /private/var/containers/Bundle/Application/3DE84EC0-A042-42E6-8301-B233D104676A/MyAppName.iOS.app/MyAppName.iOS
> : (null) 	0x102998154 -
> /private/var/containers/Bundle/Application/3DE84EC0-A042-42E6-8301-B233D104676A/MyAppName.iOS.app/MyAppName.iOS
> : (null) 	0x1029980cc -
> /private/var/containers/Bundle/Application/3DE84EC0-A042-42E6-8301-B233D104676A/MyAppName.iOS.app/MyAppName.iOS
> : (null) 	0x102995e74 -
> /private/var/containers/Bundle/Application/3DE84EC0-A042-42E6-8301-B233D104676A/MyAppName.iOS.app/MyAppName.iOS
> : (null) 	0x102993aec -
> /private/var/containers/Bundle/Application/3DE84EC0-A042-42E6-8301-B233D104676A/MyAppName.iOS.app/MyAppName.iOS
> : (null) 	0x102992824 -
> /private/var/containers/Bundle/Application/3DE84EC0-A042-42E6-8301-B233D104676A/MyAppName.iOS.app/MyAppName.iOS
> : (null) 	0x104714530 -
> /private/var/containers/Bundle/Application/3DE84EC0-A042-42E6-8301-B233D104676A/MyAppName.iOS.app/MyAppName.iOS
> : (null) 	0x104702694 -
> /private/var/containers/Bundle/Application/3DE84EC0-A042-42E6-8301-B233D104676A/MyAppName.iOS.app/MyAppName.iOS
> : (null) 	0x1029da3ac -
> /private/var/containers/Bundle/Application/3DE84EC0-A042-42E6-8301-B233D104676A/MyAppName.iOS.app/MyAppName.iOS
> : (null) 	0x102d59af4 -
> /private/var/containers/Bundle/Application/3DE84EC0-A042-42E6-8301-B233D104676A/MyAppName.iOS.app/MyAppName.iOS
> : (null) 	0x104742fb4 -
> /private/var/containers/Bundle/Application/3DE84EC0-A042-42E6-8301-B233D104676A/MyAppName.iOS.app/MyAppName.iOS
> : mono_pmip 	0x1047dc688 -
> /private/var/containers/Bundle/Application/3DE84EC0-A042-42E6-8301-B233D104676A/MyAppName.iOS.app/MyAppName.iOS
> : mono_pmip 	0x1047dfb40 -
> /private/var/containers/Bundle/Application/3DE84EC0-A042-42E6-8301-B233D104676A/MyAppName.iOS.app/MyAppName.iOS
> : mono_pmip 	0x10299ce1c -
> /private/var/containers/Bundle/Application/3DE84EC0-A042-42E6-8301-B233D104676A/MyAppName.iOS.app/MyAppName.iOS
> : (null) 	0x10299cb14 -
> /private/var/containers/Bundle/Application/3DE84EC0-A042-42E6-8301-B233D104676A/MyAppName.iOS.app/MyAppName.iOS
> : (null) 	0x19bd632f8 -
> /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore :
> <redacted> 	0x197a05610 - /usr/lib/system/libdispatch.dylib :
> <redacted> 	0x197a06184 - /usr/lib/system/libdispatch.dylib :
> <redacted> 	0x1979e935c - /usr/lib/system/libdispatch.dylib :
> <redacted> 	0x197cb63c4 -
> /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation :
> <redacted> 	0x197cb13b8 -
> /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation :
> <redacted> 	0x197cb08bc -
> /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation :
> CFRunLoopRunSpecific 	0x1a1b1c328 -
> /System/Library/PrivateFrameworks/GraphicsServices.framework/GraphicsServices
> : GSEventRunModal 	0x102d59af4 -
> /private/var/containers/Bundle/Application/3DE84EC0-A042-42E6-8301-B233D104676A/MyAppName.iOS.app/MyAppName.iOS
> : (null) 	0x104742fb4 -
> /private/var/containers/Bundle/Application/3DE84EC0-A042-42E6-8301-B233D104676A/MyAppName.iOS.app/MyAppName.iOS
> : mono_pmip 	0x1047dc688 -
> /private/var/containers/Bundle/Application/3DE84EC0-A042-42E6-8301-B233D104676A/MyAppName.iOS.app/MyAppName.iOS
> : mono_pmip 	0x1047e1834 -
> /private/var/containers/Bundle/Application/3DE84EC0-A042-42E6-8301-B233D104676A/MyAppName.iOS.app/MyAppName.iOS
> : mono_pmip 	0x104727df0 -
> /private/var/containers/Bundle/Application/3DE84EC0-A042-42E6-8301-B233D104676A/MyAppName.iOS.app/MyAppName.iOS
> : (null) 	0x10488da04 -
> /private/var/containers/Bundle/Application/3DE84EC0-A042-42E6-8301-B233D104676A/MyAppName.iOS.app/MyAppName.iOS
> : _Z9__isctypeim 	0x1029d8f34 -
> /private/var/containers/Bundle/Application/3DE84EC0-A042-42E6-8301-B233D104676A/MyAppName.iOS.app/MyAppName.iOS
> : (null) 	0x197b3b460 - /usr/lib/system/libdyld.dylib : <redacted>
> 
> ================================================================= 	Basic Fault Address Reporting
> ================================================================= Memory around native instruction pointer (0x197a46f44): 0x197a46f34 
> c0 03 5f d6 1f 20 03  	0x19bd466d4 -
> /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore :
> UIApplicationMain 	0x103683020 -
> /private/var/containers/Bundle/Application/3DE84EC0-A042-42E6-8301-B233D104676A/MyAppName.iOS.app/MyAppName.iOS
> : (null) 	0x1035dbc7c -
> /private/var/containers/Bundle/Application/3DE84EC0-A042-42E6-8301-B233D104676A/MyAppName.iOS.app/MyAppName.iOS
> : (null) 	0x1035dbc04 -
> /private/var/containers/Bundle/Application/3DE84EC0-A042-42E6-8301-B233D104676A/MyAppName.iOS.app/MyAppName.iOS
> : (null) 	0x1029d9064 -
> /private/var/containers/Bundle/Application/3DE84EC0-A042-42E6-8301-B233D104676A/MyAppName.iOS.app/MyAppName.iOS
> : (null) d5 1f 20 03  d5 01 ec 7c 92  .._.. . .. ....|. 0x197a46f44 
> 20 00 c0 3d c3 f9 ff 10 62  04 c1 3c 02 0c 40 92   ..
> =....b. .<.. @. 0x197a46f54  63 00 02 cb 61 00 c0 3d 00  1c a1 4e 05 00 00 14   c...a..= ...N.... 0x197a46f64  1f  20 03 d5 1f 20 03 d5 1f
> 20 03 d5 20 0c c1 3c   . ... ... .. . .<
> 
> ================================================================= 	Managed Stacktrace:
> ================================================================= 	  at <unknown> <0xffffffff> 	  at
> ApiDefinition.Messaging:void_objc_msgSend_IntPtr_IntPtr_IntPtr
> <0x00007> 	  at
> WindowsAzure.Messaging.SBNotificationHub:RegisterNative <0x00333> 	 
> at MyAppName.iOS.AppDelegate:RegisteredForRemoteNotifications
> <0x002db> 	  at System.Object:runtime_invoke_dynamic <0x00103> 	  at
> <unknown> <0xffffffff> 	  at UIKit.UIApplication:UIApplicationMain
> <0x00007> 	  at UIKit.UIApplication:Main <0x0002b> 	  at
> UIKit.UIApplication:Main <0x00043> 	  at
> MyAppName.iOS.Application:Main <0x000a3> 	  at
> System.Object:runtime_invoke_dynamic <0x00103>
> =================================================================**

```

The code in my application as attempted:

public override void RegisteredForRemoteNotifications(
            UIApplication application, NSData deviceToken)
        {
            try
            {
                var cs = SBConnectionString.CreateListenAccess(
                new NSUrl("sb://" + HUBNAME + "-ns.servicebus.windows.net/"),
                LISTENSECRETKEY);      //  where LISTENSECRETKEY is just the key part without the 
                                                     //  ;SharedAccessKey="

                var hub = new SBNotificationHub(cs, HUBNAME);

                // await hub.UnregisterAllAsync(deviceToken);

                hub.RegisterNative(deviceToken, null, err => {

                    if (err != null)
                    {
                        Console.WriteLine("Error: " + err.Description);
                        //homeViewController.RegisteredForNotifications("Error: " + err.Description);
                    }
                    else
                    {
                        Console.WriteLine("Success");
                        //homeViewController.RegisteredForNotifications("Successfully registered for notifications");
                    }
                });
            }
            catch(Exception ex)
            {
                Debug.WriteLine(ex.Message);
            }

```

**Comment by Redth** [comment]
I think if you already have your full connection string you can use:

`new SBNotificationHub("myconnectionstring", "hubpath");`
