### ISSUE TITLE
Will there be any update available to support AndroidX support library

### ISSUE THREAD

**Issue by cybvitthal** [xamarin/XamarinComponents#715]
Currently, this library uses "Android.Support.V4.App" as a reference of support library.
Is there any plan to migrate it to AndroidX?

**Comment by moljac** [comment]
>this library uses "Android.Support.V4.App"

Which library?

Regarding AndroidX:

https://github.com/xamarin/AndroidSupportComponents/tree/AndroidX

**Comment by cybvitthal** [comment]
It was a comment.

Xamarin.GooglePlayServices.Maps is dependent on using Android.Support.V4.App

**Comment by Redth** [comment]
https://github.com/xamarin/AndroidX

Google has started releasing versions of Play Services and Firebase which depend on AndroidX instead of support and we are working on binding them here: https://github.com/xamarin/GooglePlayServicesComponents
