### ISSUE TITLE
Textfield floating label not working some times in Xamarin.iOS

### ISSUE THREAD

**Issue by logeshpalani33** [xamarin/XamarinComponents#729]
I have used the material components text field, in some time the label won't floating up, it will stay in place holder place 
The sample output given below, 

![Simulator Screen Shot - iPhone 8 Plus - 2019-11-05 at 12 51 48](https://user-images.githubusercontent.com/24875197/68192145-ea453880-ffd6-11e9-98ea-dff1a85b80fe.png)

**Comment by newky2k** [comment]
@logeshpalani98  We have released a pre-release version of Material Components v92 to nuget -> https://www.nuget.org/packages/Xamarin.iOS.MaterialComponents/92.0.0-rc1. Can you see if this is still an issue with the new version please.

**Comment by newky2k** [comment]
fixed in v92

**Comment by logeshpalani33** [comment]
have same problem in this release also 

![Image-1](https://user-images.githubusercontent.com/24875197/72127455-b64f1080-3395-11ea-9932-dc32b23cbebb.jpg)

**Comment by chrisbrkt** [comment]
I had the same issue while implementing this; the layouting seems to break sometimes. 
Two solutions worked for me though:
   - Either initialise the TextInputController in ViewWillAppear
   - Or, if you want it as a component, inherit from UIView and add the TextField as child view. Inheriting directly from TextField will cause some issues too
