### ISSUE TITLE
Xamarin.iOS - How to set custom size to material floating button

### ISSUE THREAD

**Issue by logeshpalani33** [xamarin/XamarinComponents#731]
I'm using the material Component package "Xamarin.iOS.MaterialComponents" and setting up Bottom App Bar with center floating action button. But there is no property available for setting size. I need to set custom sizes.
![Simulator Screen Shot - iPhone 11 - 2019-11-06 at 12 14 18](https://user-images.githubusercontent.com/24875197/68275085-bb8b9880-0090-11ea-973b-299199fee276.png)

**Comment by Redth** [comment]
We'd need more information about what the obj-c equivalent use case is here.  It's possible there are more API's added for this in v0.92 which we are currently working on binding.

**Comment by logeshpalani33** [comment]
yes @Redth  If, we need to set custom height and width for that floating action button, there is no properties for that,  I mean, we should use the default properties of Normal, Small, there is no set access for height and width.

**Comment by Redth** [comment]
Honestly we are at the mercy of which API’s Google provides in the native library. We just bind them. So if it’s one we are missing and have not exposed that is fixable but if the API you want to use doesn’t exist on the native side I’m afraid you’re out of luck.

**Comment by thekeviv** [comment]
@Redth I want to make my first code contribution to Xamarin and picked this issue as an experiment. I found this interface for the Floating Button. In this interface, there do seem to be methods for setting minimum and maximum sizes. 

```
 [BaseType(typeof(Button),
        Name = "MDCFloatingButton")]
    interface FloatingButton
    {
        [Export("mode", ArgumentSemantic.Assign)]
        FloatingButtonMode Mode { get; set; }

        [Export("imageLocation", ArgumentSemantic.Assign)]
        FloatingButtonImageLocation ImageLocation { get; set; }

        [Export("imageTitleSpace")]
        nfloat ImageTitleSpace { get; set; }

        [Static]

        [Export("defaultDimension")]
        nfloat DefaultDimension { get; }

        [Static]

        [Export("miniDimension")]
        nfloat MiniDimension { get; }

        [Static]
        [Export("floatingButtonWithShape:")]
        FloatingButton Create(FloatingButtonShape shape);

        [DesignatedInitializer]
        [Export("initWithFrame:shape:")]
        IntPtr Constructor(CGRect frame, FloatingButtonShape shape);

        [Export("initWithFrame:")]
        IntPtr Constructor(CGRect frame);

        [Export("setMinimumSize:forShape:inMode:")]
        void SetMinimumSize(CGSize minimumSize, FloatingButtonShape shape, FloatingButtonMode mode);

        [Export("setMaximumSize:forShape:inMode:")]
        void SetMaximumSize(CGSize maximumSize, FloatingButtonShape shape, FloatingButtonMode mode);

        [Export("setContentEdgeInsets:forShape:inMode:")]
        void SetContentEdgeInsets(UIEdgeInsets contentEdgeInsets, FloatingButtonShape shape, FloatingButtonMode mode);

        [Export("setHitAreaInsets:forShape:inMode:")]
        void SetHitAreaInsets(UIEdgeInsets hitAreaInsets, FloatingButtonShape shape, FloatingButtonMode mode);

        [Export("expand:completion:")]
        void Expand(bool animated, [NullAllowed]  Action completion);

        [Export("collapse:completion:")]
        void Collapse(bool animated, [NullAllowed]  Action completion);
    }
```

From here, I tried finding the implementation for this interface, while I couldn't find it, I found this in https://github.com/xamarin/XamarinComponents/blob/master/iOS/MaterialComponents/samples/MaterialSample/ButtonsSamples/ButtonsViewController.cs


```
Button button;
		public Button Button {
			get => button;
			set {
				RemoveButton ();
				button = value;
				ContentView.AddSubview (button);
				AddButtonConstraints ();
			}
		}

		#endregion

		#region Constructors

		public ButtonTableViewCell (IntPtr handle) : base (handle) { }

		#endregion

		#region Cell Life Cycle

		public override void PrepareForReuse ()
		{
			base.PrepareForReuse ();

			RemoveButton ();
		}

		#endregion

		#region Internal Functionality

		void AddButtonConstraints ()
		{
			if (UIDevice.CurrentDevice.CheckSystemVersion (9, 0)) {
				button.CenterYAnchor.ConstraintEqualTo (ContentView.CenterYAnchor, 0).Active = true;
				button.TrailingAnchor.ConstraintEqualTo (ContentView.TrailingAnchor, -offset).Active = true;
			} else {
				var centerYAnchor = NSLayoutConstraint.Create (button, NSLayoutAttribute.CenterX, NSLayoutRelation.Equal, ContentView, NSLayoutAttribute.CenterX, 1, 0);
				var trailingAnchor = NSLayoutConstraint.Create (button, NSLayoutAttribute.Trailing, NSLayoutRelation.Equal, ContentView, NSLayoutAttribute.Trailing, 1, -offset);
				NSLayoutConstraint.ActivateConstraints (new [] { centerYAnchor, trailingAnchor });
			}
		}
```

There is also a createButton method in this file which has a switch statement to create a FloatingActionButton although the place of this file seems suspicious to me!

It seems that based on this info, maybe the floating button component is not being created using just a direct binding to a library of Google and is actually being rendered using code from the Xamarin team. If you can verify this and let me know, I can dig more into this and see if any code changes are needed and can let you know and finally make my first code contribution
