### ISSUE TITLE
ManifestMerger error on build (preview 03)

### ISSUE THREAD

**Issue by coosmiyn** [xamarin/XamarinComponents#734]
When I try to build using the ManifestMerger I get this error. I am not sure why. I tried cleaning, deleting bin and obj because I had problems in the past using the manifest in the obj directory, but I couldn't get it anyway to work.
Did anyone get this?

`/Users/coosmiyn/.nuget/packages/xamarin.android.manifestmerger/1.0.0-preview03/build/monoandroid/Xamarin.Android.ManifestMerger.targets(5,5): Error MSB3073: The command ""/Users/coosmiyn/Library/Developer/Xamarin/jdk/microsoft_dist_openjdk_1.8.0.25/bin/java" -cp "/Users/coosmiyn/.nuget/packages/xamarin.android.manifestmerger/1.0.0-preview03/build/monoandroid/common.jar:/Users/coosmiyn/.nuget/packages/xamarin.android.manifestmerger/1.0.0-preview03/build/monoandroid/guava.jar:/Users/coosmiyn/.nuget/packages/xamarin.android.manifestmerger/1.0.0-preview03/build/monoandroid/kotlin-stdlib-jdk8.jar:/Users/coosmiyn/.nuget/packages/xamarin.android.manifestmerger/1.0.0-preview03/build/monoandroid/kotlin-stdlib.jar:/Users/coosmiyn/.nuget/packages/xamarin.android.manifestmerger/1.0.0-preview03/build/monoandroid/kxml2.jar:/Users/coosmiyn/.nuget/packages/xamarin.android.manifestmerger/1.0.0-preview03/build/monoandroid/manifest-merger.jar:/Users/coosmiyn/.nuget/packages/xamarin.android.manifestmerger/1.0.0-preview03/build/monoandroid/sdk-common.jar:/Users/coosmiyn/.nuget/packages/xamarin.android.manifestmerger/1.0.0-preview03/build/monoandroid/sdklib.jar" "com.android.manifmerger.Merger" --main "obj/Release/android/AndroidManifest.xml" --libs "obj/Release/lp/61/jl/AndroidManifest.xml:obj/Release/lp/95/jl/AndroidManifest.xml:obj/Release/lp/59/jl/AndroidManifest.xml:obj/Release/lp/92/jl/AndroidManifest.xml:obj/Release/lp/66/jl/AndroidManifest.xml:obj/Release/lp/50/jl/AndroidManifest.xml:obj/Release/lp/68/jl/AndroidManifest.xml:obj/Release/lp/57/jl/AndroidManifest.xml:obj/Release/lp/32/jl/AndroidManifest.xml:obj/Release/lp/35/jl/AndroidManifest.xml:obj/Release/lp/102/jl/AndroidManifest.xml:obj/Release/lp/69/jl/AndroidManifest.xml:obj/Release/lp/56/jl/AndroidManifest.xml:obj/Release/lp/51/jl/AndroidManifest.xml:obj/Release/lp/58/jl/AndroidManifest.xml:obj/Release/lp/67/jl/AndroidManifest.xml:obj/Release/lp/93/jl/AndroidManifest.xml:obj/Release/lp/94/jl/AndroidManifest.xml:obj/Release/lp/60/jl/AndroidManifest.xml:obj/Release/lp/34/jl/AndroidManifest.xml:obj/Release/lp/20/jl/AndroidManifest.xml:obj/Release/lp/18/jl/AndroidManifest.xml:obj/Release/lp/29/jl/AndroidManifest.xml:obj/Release/lp/42/jl/AndroidManifest.xml:obj/Release/lp/89/jl/AndroidManifest.xml:obj/Release/lp/45/jl/AndroidManifest.xml:obj/Release/lp/73/jl/AndroidManifest.xml:obj/Release/lp/87/jl/AndroidManifest.xml:obj/Release/lp/74/jl/AndroidManifest.xml:obj/Release/lp/28/jl/AndroidManifest.xml:obj/Release/lp/1/jl/AndroidManifest.xml:obj/Release/lp/26/jl/AndroidManifest.xml:obj/Release/lp/21/jl/AndroidManifest.xml:obj/Release/lp/75/jl/AndroidManifest.xml:obj/Release/lp/86/jl/AndroidManifest.xml:obj/Release/lp/72/jl/AndroidManifest.xml:obj/Release/lp/44/jl/AndroidManifest.xml:obj/Release/lp/43/jl/AndroidManifest.xml:obj/Release/lp/88/jl/AndroidManifest.xml:obj/Release/lp/38/jl/AndroidManifest.xml:obj/Release/lp/36/jl/AndroidManifest.xml:obj/Release/lp/91/jl/AndroidManifest.xml:obj/Release/lp/65/jl/AndroidManifest.xml:obj/Release/lp/96/jl/AndroidManifest.xml:obj/Release/lp/100/jl/AndroidManifest.xml:obj/Release/lp/54/jl/AndroidManifest.xml:obj/Release/lp/98/jl/AndroidManifest.xml:obj/Release/lp/53/jl/AndroidManifest.xml:obj/Release/lp/30/jl/AndroidManifest.xml:obj/Release/lp/37/jl/AndroidManifest.xml:obj/Release/lp/39/jl/AndroidManifest.xml:obj/Release/lp/99/jl/AndroidManifest.xml:obj/Release/lp/52/jl/AndroidManifest.xml:obj/Release/lp/101/jl/AndroidManifest.xml:obj/Release/lp/55/jl/AndroidManifest.xml:obj/Release/lp/97/jl/AndroidManifest.xml:obj/Release/lp/63/jl/AndroidManifest.xml:obj/Release/lp/64/jl/AndroidManifest.xml:obj/Release/lp/90/jl/AndroidManifest.xml:obj/Release/lp/46/jl/AndroidManifest.xml:obj/Release/lp/41/jl/AndroidManifest.xml:obj/Release/lp/83/jl/AndroidManifest.xml:obj/Release/lp/77/jl/AndroidManifest.xml:obj/Release/lp/48/jl/AndroidManifest.xml:obj/Release/lp/70/jl/AndroidManifest.xml:obj/Release/lp/84/jl/AndroidManifest.xml:obj/Release/lp/24/jl/AndroidManifest.xml:obj/Release/lp/23/jl/AndroidManifest.xml:obj/Release/lp/4/jl/AndroidManifest.xml:obj/Release/lp/3/jl/AndroidManifest.xml:obj/Release/lp/85/jl/AndroidManifest.xml:obj/Release/lp/71/jl/AndroidManifest.xml:obj/Release/lp/76/jl/AndroidManifest.xml:obj/Release/lp/49/jl/AndroidManifest.xml:obj/Release/lp/40/jl/AndroidManifest.xml:obj/Release/lp/47/jl/AndroidManifest.xml:obj/Release/lp/22/jl/AndroidManifest.xml:obj/Release/lp/25/jl/AndroidManifest.xml" --out "obj/Release/android/AndroidManifest.xml"" exited with code 1. (MSB3073) (ClubHub.Android)`

**Comment by moljac** [comment]
@coosmiyn 

>Did anyone get this?

I did, but few weeks ago. Updating to newer version helped. I know `preview03` is the latest one.

This looks like commandline:
```
"com.android.manifmerger.Merger" \
--main "obj/Release/android/AndroidManifest.xml" \
--libs \
      "obj/Release/lp/61/jl/AndroidManifest.xml:obj/Release/lp/95/jl/AndroidManifest.xml: .... VeryLongList"
```
I would 

1. run the sample in this repo and try to deduce commandline pattern.
2. then switch to your sample and try to run the commandline with increased verbosity

Do you maybe mix Android.Support and AndroidX?
Can you list Android.Support (AndroidX) and GooglePlayService/Firebase package references?

Few links

* .   https://developer.android.com/studio/build/manifest-merge
* .

**Comment by coosmiyn** [comment]
I tried running the command in the terminal, but it says that the file name is too long.

**Comment by coosmiyn** [comment]
I am using quite a few packages.

From Android.Support I am using Compat, Core.UI, Core.Utils, CustomTabs, Design, Fragment, Media.Compat, v4, v7.AppCompat, v7.CardView, v7.MediaRouter.
From Firebase I have Ads, Analytics, Analytics.Impl, AppIndexing, Auth, Auth.Interlop, Common, Config, Core, Iid, Measurement.Connector, Measurement.Connector.Impl and Messaging.
The Google Play Services are Ads, Ads.Identifier, Base, Basement, Flags, Gass, Gcm, Location, Maps, Measurement.Api, Measurement.Base, Places, Stats, Tasks. 

I am in the process of deleting most of them, but I think it asked me before to install some of those, I was in a rush and I just installed them, also they are listed as dependencies for some of the packages.

**Comment by merravid** [comment]
Getting same error. Installed Manifest Merger preview03 to try and get latest Xamarin.Firebase.Messaging to work.

**Comment by merravid** [comment]
Some more info: When running the command in the command line, the errors I get are the following:

D:\...\obj\Debug\90\android\AndroidManifest.xml:36:5-88 Error:
        Element service#com.xxxxxx.app.mp.Services.MPFirebaseMessagingService at AndroidManifest.xml:36:5-88 duplicated with element declared at AndroidManifest.xml:21:5-25:15
D:\...\obj\Debug\90\android\AndroidManifest.xml:37:5-84 Error:
        Element service#com.xxxxxx.app.mp.Services.MPAuthenticatorService at AndroidManifest.xml:37:5-84 duplicated with element declared at AndroidManifest.xml:13:5-18:15
D:\...\obj\Debug\90\android\AndroidManifest.xml:181:5-183:15 Error:
        Element service#com.google.firebase.components.ComponentDiscoveryService at AndroidManifest.xml:181:5-183:15 duplicated with element declared at AndroidManifest.xml:164:5-166:15
D:\...\obj\Debug\90\android\AndroidManifest.xml:202:5-146 Error:
        Element activity#com.braintreepayments.api.threedsecure.ThreeDSecureWebViewActivity at AndroidManifest.xml:202:5-146 duplicated with element declared at AndroidManifest.xml:195:5-99
D:\...\obj\Debug\90\android\AndroidManifest.xml Error:
        Validation failed, exiting

**Comment by merravid** [comment]
OK, it seems that fixing the first two duplicate entries by only declaring them as attributes on the classes (and not in the manifest), fixes it.

**Comment by otshenri** [comment]
@coosmiyn have you fixed your issue? what was the solution for you?

**Comment by otshenri** [comment]
Same issue here, locally preview3 works but on CI it doesn't. I'm able to reproduce locally when downgrading to preview2.

Running from command line I get this: 
```
.../Xamarin.Android.ManifestMerger.1.0.0-preview02/build/monoandroid/sdk-common.jar: line 14: syntax error near unexpected token `)'
.../Xamarin.Android.ManifestMerger.1.0.0-preview02/build/monoandroid/sdk-common.jar: line 14: `?P%[?
                                                                                                                                      dM4?"-ޑ?S<?
                                                                                                                                                 ???1?.?u
?_.E??????PK'                                                                                                                                            ?M?rWN?o?,Ca?0F?&p)??-F
```

Not mixing AndroidX.
List of packages:
![image](https://user-images.githubusercontent.com/8706308/69150688-70827400-0ad9-11ea-8dca-0933475b3813.png)

Any thoughts?

**Comment by moljac** [comment]
@otshenri 
I hit those and updates did help. Not sure whether VS4mac, mono od Android SDK.

please can you provide more data about those 3?

**Comment by otshenri** [comment]
@moljac I think VS4mac shouldn't matter because we're having the same issue with Azure CI build. Targeting Android 9.0 and using MonoAndroid90.

**Comment by alihaluk** [comment]
I have some problem, can't publish production. using VS4Mac latest version.

**Comment by otshenri** [comment]
@moljac is there anything else we could try or some more information we could provide you? It's preventing us from publishing as well.

**Comment by Redth** [comment]
Is everyone using `PackageReference` ?

**Comment by otshenri** [comment]
Solution for us was changing the CI build agent from Windows machine to Mac machine. Hope it helps someone :)

**Comment by KennyDizi** [comment]
same here!
[build error.txt](https://github.com/xamarin/XamarinComponents/files/3903781/build.error.txt)

**Comment by Redth** [comment]
Hmm... I wonder if we're hitting the max command line argument invocation length or something funny (which would explain why it would work on Mac and not Windows).

@xamarindevelopervietnam can you try copying and pasting the command it's trying to run into a terminal and manually running it to see more output?

So
```
"C:\java-jdk-231-x64\bin\java.exe" -cp "C:\Users\ASUS\.nuget\packages\xamarin.android.manifestmerger\1.0.0-preview03\build\monoandroid\common.jar;C:\Users\ASUS\.nuget\packages\xamarin.android.manifestmerger\1.0.0-preview03\build\monoandroid\guava.jar;C:\Users\ASUS\.nuget\packages\xamarin.android.manifestmerger\1.0.0-preview03\build\monoandroid\kotlin-stdlib-jdk8.jar;C:\Users\ASUS\.nuget\packages\xamarin.android.manifestmerger\1.0.0-preview03\build\monoandroid\kotlin-stdlib.jar;C:\Users\ASUS\.nuget\packages\xamarin.android.manifestmerger\1.0.0-preview03\build\monoandroid\kxml2.jar;C:\Users\ASUS\.nuget\packages\xamarin.android.manifestmerger\1.0.0-preview03\build\monoandroid\manifest-merger.jar;C:\Users\ASUS\.nuget\packages\xamarin.android.manifestmerger\1.0.0-preview03\build\monoandroid\sdk-common.jar;C:\Users\ASUS\.nuget\packages\xamarin.android.manifestmerger\1.0.0-preview03\build\monoandroid\sdklib.jar" "com.android.manifmerger.Merger" --main "obj\DB_SMHOME\100\android\AndroidManifest.xml" --libs "obj\DB_SMHOME\100\lp\101\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\102\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\103\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\104\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\105\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\110\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\112\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\113\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\114\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\115\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\116\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\117\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\118\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\120\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\121\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\123\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\124\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\125\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\127\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\129\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\130\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\131\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\132\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\133\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\134\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\135\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\136\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\137\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\138\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\139\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\140\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\141\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\142\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\143\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\144\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\145\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\146\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\147\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\148\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\149\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\150\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\151\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\152\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\153\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\154\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\155\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\156\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\157\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\158\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\160\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\161\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\162\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\163\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\164\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\165\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\166\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\167\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\168\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\169\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\170\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\171\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\172\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\173\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\174\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\175\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\176\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\177\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\178\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\179\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\18\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\180\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\187\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\188\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\189\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\190\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\191\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\192\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\193\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\194\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\195\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\196\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\197\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\198\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\199\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\20\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\200\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\203\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\22\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\23\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\27\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\28\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\29\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\3\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\30\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\31\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\32\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\5\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\64\jl\AndroidManifest.xml;obj\DB_SMHOME\100\lp\66\jl\AndroidManifest.xml" --out "obj\DB_SMHOME\100\android\AndroidManifest.xml"
```

**Comment by KennyDizi** [comment]
@Redth obj\DB_SMHOME\100\android\AndroidManifest.xml does not exist

**Comment by KennyDizi** [comment]
same thing on macOS
[same on macOS.docx](https://github.com/xamarin/XamarinComponents/files/3909305/same.on.macOS.docx)

**Comment by Redth** [comment]
@xamarindevelopervietnam are you able to create a [.binlog](https://docs.microsoft.com/en-us/visualstudio/msbuild/obtaining-build-logs-with-msbuild?view=vs-2019) and share it?

**Comment by KennyDizi** [comment]
@Redth how to create .binlog?

**Comment by Redth** [comment]
https://docs.microsoft.com/en-us/visualstudio/msbuild/obtaining-build-logs-with-msbuild?view=vs-2019

**Comment by alexshikov** [comment]
Having the same issue on Mac.

**Comment by alexshikov** [comment]
We are having the same issue. We do use `PackageReference` in all `csproj` files.

Executing the command from the command line (from Android project folder) gives the next error:
```
/Users/Seifer/Projects/Proj/Droid/obj/Debug/android/AndroidManifest.xml:49:9-51:51 Error:
	Attribute meta-data#onesignal_app_id@value at AndroidManifest.xml:49:9-51:51 requires a placeholder substitution but no value for <onesignal_app_id> is provided.
/Users/Seifer/Projects/Proj/Droid/obj/Debug/android/AndroidManifest.xml:53:9-55:70 Error:
	Attribute meta-data#onesignal_google_project_number@value at AndroidManifest.xml:53:9-55:70 requires a placeholder substitution but no value for <onesignal_google_project_number> is provided.
```

**Comment by alexshikov** [comment]
OneSignal package referenced only from the Core project. Simply updating nuget from `3.6.0` to `3.7.0` fixed the issue.

**Comment by coosmiyn** [comment]
It's me again. After a long time not being able to work on this, I found the error. I had a duplicate declaration in the Manifest.
I tried running the command from the error text in the terminal (Visual Studio Mac) and it said I had a duplicate. In Visual Studio it said only "Exited with code 1".
It works now just fine, with all the Firebase components working as intended.

**Comment by moljac** [comment]
@coosmiyn 
Thanks a  lot for feedback. Appreciated.
