### ISSUE TITLE
Failure binding .framework with cocoapod dependencies

### ISSUE THREAD

**Issue by deelw** [xamarin/XamarinComponents#735]
I'm trying to generate bindings for a third party framework (iProov.framework, https://github.com/iProov/ios). This library was written in Swift en has three cocoapods dependencies which are specified in the iProov.podspec file. The library works fine in a XCode project. I need C# bindings for use in a Xamarin iOS project.

Steps:
1. I have cloned the repo https://github.com/iProov/ios to a local folder.
2. I installed objectivesharpie-3.4.47.pkg
3. In the Terminal within the repo folder, I executed the following command:
sharpie bind -sdk iphoneos13.2 -framework iProov.framework

This results in the following errors:
./iProov.framework/Headers/iProov-Swift.h:189:9: fatal error: module 'SocketIO'
      not found
@import SocketIO;
 ~~~~~~~^~~~~~~~
/private/var/folders/pz/qrnhtw956h319sp7v16jl6h00000gn/T/com.xamarin.ObjectiveSharpie/95b1763679444344a1bff1e3f2841d1f.h:1:9: fatal error: 
      could not build module 'iProov'
@import iProov;

I tried a very lot more with pod init/install, sharpie pod init, created a static library xcode project, etc. but without success.

**Comment by SotoiGhost** [comment]
@deelw You need to pass dependency frameworks/libraries paths to clang on `sharpie` so it can resolve third-parties imports. e.g:

`sharpie bind -sdk iphoneos13.2 -framework iProov.framework -c -Fpath/to/dependency1/folder -Fpath/to/dependency2/folder`

or you can point to the Headers folder of the framework/library:

`sharpie bind -sdk iphoneos13.2 -framework iProov.framework -c -Ipath/to/dependency1/Foo1.framework/Headers -Ipath/to/dependency2/Headers`

You can play with `-F` and `-I`. Hope this helps you.

**Comment by deelw** [comment]
@SotoiGhost I have done and played with -F and -I but without success.

I referenced the dependency folders and subfolders of a pod install of the dependencies, including 
KeychainAccess 3.2.0, Socket.IO-Client-Swift 15.1.0, SwiftyJSON 4.0.0 and Starscream 3.1

Because that did not solve my problem, I also downloaded the complete git repos of the dependencies and built the .framework files and referenced the path as a sharpie command (clang) -F parameter. I could not compile Socket.IO-Client-Swift succesfully because module Starscream not found while I did make a podfile including pod 'Starscream', '~> 3.1' and succesfully did run pod install. I also created .m files referencing #import <ProductName/ProductModuleName-Swift.h>

I tried a lot more, and also consulted colleges, without success.. I hope you would try to create the bindings yourself? Is it impossible or am I doing something wrong?

**Comment by SotoiGhost** [comment]
@deelw I think I made it work. Here's a zip that contains files that bind iProov using `sharpie`. You will need to install [`cocoapods-rome`][1] to make it work.

After you install `cocoapods-rome`. Just unzip the attached zip and run `make` in the command line.

Hope this helps you.

[iProov.zip](https://github.com/xamarin/XamarinComponents/files/3865485/iProov.zip)

[1]: https://github.com/CocoaPods/Rome#installation

**Comment by deelw** [comment]
@SotoiGhost Yes, it works!! Thanks you very much for your help!

**Comment by SotoiGhost** [comment]
Yw @deelw! Glad that I could help. Closing this issue now. Best!
