### ISSUE TITLE
AndroidThings | [INSTALL_FAILED_MISSING_SHARED_LIBRARY]

### ISSUE THREAD

**Issue by simix-felipebaltazar** [xamarin/XamarinComponents#746]
## Description
I'm trying to use `Xamarin.Android.Things` on my project, but it fail to deploy.
I think this might be related to D8 compiler

<p align="center">
	<kbd>
		<img src="https://user-images.githubusercontent.com/42358163/69278074-51124680-0bc0-11ea-8fb2-70e3478edd0e.png" alt="image" style="max-width:100%;"/>
	</kbd>
</p>

- My Settings:

<p align="center">
	<kbd>
		<img src="https://user-images.githubusercontent.com/42358163/69278148-7e5ef480-0bc0-11ea-8c37-94c9dbc82f6b.png" alt="image" style="max-width:100%;"/>
	</kbd>
</p>

## Details
Visual Studio 2019 16.3.9
Target android 8.1 (27)
Min android 4.4 (19)

> Only an android project, without Xamarin.Forms

## Output

<details>
    <summary>
        <b>Click here </b>
    </summary>

1>------ Compilação iniciada: Projeto: simix.supermidia, Configuração: Debug Any CPU ------
Installing shared runtime
Target device is x86.
Installing the Mono shared runtime (debug - 1565368993)...
Installing platform framework
Installing the API 27 platform framework..
Verificações de tempo de execução concluídas
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(2106,5): warning MSB3277: foram encontrados conflitos entre versões diferentes "Microsoft.CSharp" que não puderam ser resolvidos. Esses conflitos de referência estão relacionados no log de build quando o detalhamento do log está definido como detalhado.
1>  simix.supermidia -> D:\Simix\SuperMidia\Xamarin\simix.supermidia\simix.supermidia\bin\Debug\simix.supermidia.dll
1>  Não é possível resolver o conflito entre "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" e "mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e". Escolhendo "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" arbitrariamente.
1>  Não é possível resolver o conflito entre "System, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e" e "System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=969db8053d3322ac, Retargetable=Yes". Escolhendo "System, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e" arbitrariamente.
1>D:\Simix\SuperMidia\Xamarin\simix.supermidia\simix.supermidia\obj\Debug\81\android\AndroidManifest.xml : warning XA4218: Unable to find //manifest/application/uses-library at path: C:\Program Files (x86)\Android\android-sdk\platforms\android-27\optional\com.symbol.emdk.jar
1>D:\Simix\SuperMidia\Xamarin\simix.supermidia\simix.supermidia\obj\Debug\81\android\AndroidManifest.xml : warning XA4218: Unable to find //manifest/application/uses-library at path: C:\Program Files (x86)\Android\android-sdk\platforms\android-27\optional\com.google.android.things.jar
1>R8 : warning : The rule `-keep public class * extends java.lang.annotation.Annotation {
1>R8 : warning : Resource 'META-INF/MANIFEST.MF' already exists.
1>R8 : warning : Resource 'META-INF/MSFTSIG.SF' already exists.
1>R8 : warning : Resource 'META-INF/MSFTSIG.RSA' already exists.
1>R8 : warning : Resource 'META-INF/MANIFEST.MF' already exists.
1>R8 : warning : Resource 'META-INF/MSFTSIG.SF' already exists.
1>R8 : warning : Resource 'META-INF/MSFTSIG.RSA' already exists.
1>R8 : warning : Resource 'META-INF/MANIFEST.MF' already exists.
1>R8 : warning : Resource 'META-INF/MANIFEST.MF' already exists.
1>R8 : warning : Resource 'META-INF/MANIFEST.MF' already exists.
2>Iniciando a implantação em Genymotion Custom Phone ...
2>Implantando em Genymotion Custom Phone...
Compilação iniciada.
Projeto "simix.supermidia.csproj" (Install destino(s)):
Found Java SDK version 1.8.0.
Found Java SDK version 1.8.0.
Dex Fast Deployment Enabled: False
MonoAndroid Tools: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Xamarin\Android\
Android Platform API level: 27
TargetFrameworkVersion: v8.1
Android NDK: 
Android SDK: C:\Program Files (x86)\Android\android-sdk\
Android SDK Build Tools: C:\Program Files (x86)\Android\android-sdk\build-tools\28.0.3\
Java SDK: C:\Program Files\Android\Jdk\microsoft_dist_openjdk_1.8.0.25\
Application Java class: android.support.multidex.MultiDexApplication
  PackageName: com.simix.supermidia.pro
Ignorando o destino "_ResolveLibraryProjectImports" porque todos os arquivos de saída estão atualizados em relação aos arquivos de entrada.
Ignorando o destino "_BuildLibraryImportsCache" porque todos os arquivos de saída estão atualizados em relação aos arquivos de entrada.
Ignorando o destino "_BuildAdditionalResourcesCache" porque todos os arquivos de saída estão atualizados em relação aos arquivos de entrada.
Ignorando o destino "_CreateAdditionalResourceCache" porque ele não tem saídas.
Ignorando o destino "_GenerateAndroidResourceDir" porque todos os arquivos de saída estão atualizados em relação aos arquivos de entrada.
Ignorando o destino "_GenerateLayoutBindings" porque ele não tem saídas.
Ignorando o destino "_ConvertLibraryResourcesCases" porque todos os arquivos de saída estão atualizados em relação aos arquivos de entrada.
Ignorando o destino "_CompileAndroidLibraryResources" porque todos os arquivos de saída estão atualizados em relação aos arquivos de entrada.
Ignorando o destino "_ConvertResourcesCases" porque todos os arquivos de saída estão atualizados em relação aos arquivos de entrada.
Ignorando o destino "_CompileResources" porque todos os arquivos de saída estão atualizados em relação aos arquivos de entrada.
Checking Android SDK Build-tools version...
Selected Android SDK Build Tools Path: C:\Program Files (x86)\Android\android-sdk\build-tools\28.0.3\
Selected Android SDK Build Tools Version: 28.0.3
Android SDK Build Tools Version: 28.0.3 meets minimum requirements for Vector Drawables. OK.
Finished Checking Android SDK Build-tools version.
Ignorando o destino "_UpdateAndroidResgen" porque todos os arquivos de saída estão atualizados em relação aos arquivos de entrada.
  Adding assembly reference for simix.supermidia, recursively...
  Adding assembly reference for AndHUD, recursively...
  Adding assembly reference for AutoMapper, recursively...
    Adding assembly reference for netstandard, recursively...
      Adding assembly reference for System.Drawing.Common, recursively...
      Adding assembly reference for System.IO.Compression, recursively...
      Adding assembly reference for System.IO.Compression.FileSystem, recursively...
      Adding assembly reference for System.ComponentModel.Composition, recursively...
      Adding assembly reference for System.Numerics, recursively...
      Adding assembly reference for System.Runtime.Serialization, recursively...
        Adding assembly reference for System.ServiceModel.Internals, recursively...
      Adding assembly reference for System.Transactions, recursively...
    Adding assembly reference for System.Reflection.Emit, recursively...
    Adding assembly reference for System.Reflection.Emit.ILGeneration, recursively...
  Adding assembly reference for CommonServiceLocator, recursively...
  Adding assembly reference for Cronos, recursively...
  Adding assembly reference for DarkSkyApi, recursively...
    Adding assembly reference for System.Resources.ResourceManager, recursively...
    Adding assembly reference for System.Threading.Tasks, recursively...
    Adding assembly reference for System.IO, recursively...
    Adding assembly reference for System.Diagnostics.Debug, recursively...
    Adding assembly reference for System.Runtime.Serialization.Primitives, recursively...
    Adding assembly reference for System.Linq, recursively...
    Adding assembly reference for System.Globalization, recursively...
    Adding assembly reference for System.Net.Primitives, recursively...
    Adding assembly reference for System.Runtime.Serialization.Json, recursively...
  Adding assembly reference for FFImageLoading, recursively...
    Adding assembly reference for System.Collections, recursively...
    Adding assembly reference for System.Reflection, recursively...
    Adding assembly reference for System.Threading, recursively...
    Adding assembly reference for System.Runtime.Extensions, recursively...
    Adding assembly reference for System.Text.Encoding, recursively...
    Adding assembly reference for System.Text.RegularExpressions, recursively...
  Adding assembly reference for FFImageLoading.Platform, recursively...
  Adding assembly reference for FirebirdSql.Data.FirebirdClient, recursively...
  Adding assembly reference for GalaSoft.MvvmLight, recursively...
    Adding assembly reference for System.ObjectModel, recursively...
    Adding assembly reference for System.Linq.Expressions, recursively...
    Adding assembly reference for System.Reflection.Extensions, recursively...
  Adding assembly reference for GalaSoft.MvvmLight.Extras, recursively...
    Adding assembly reference for System.ComponentModel, recursively...
  Adding assembly reference for GalaSoft.MvvmLight.Platform, recursively...
  Adding assembly reference for HtmlAgilityPack, recursively...
  Adding assembly reference for ICSharpCode.SharpZipLib, recursively...
  Adding assembly reference for Java.Interop, recursively...
  Adding assembly reference for Microsoft.AppCenter.Analytics.Android.Bindings, recursively...
  Adding assembly reference for Microsoft.AppCenter.Analytics, recursively...
  Adding assembly reference for Microsoft.AppCenter.Android.Bindings, recursively...
  Adding assembly reference for Microsoft.AppCenter.Crashes.Android.Bindings, recursively...
  Adding assembly reference for Microsoft.AppCenter.Crashes, recursively...
  Adding assembly reference for Microsoft.AppCenter, recursively...
  Adding assembly reference for Microsoft.AspNetCore.Connections.Abstractions, recursively...
  Adding assembly reference for Microsoft.AspNetCore.Http.Connections.Client, recursively...
  Adding assembly reference for Microsoft.AspNetCore.Http.Connections.Common, recursively...
  Adding assembly reference for Microsoft.AspNetCore.Http.Features, recursively...
  Adding assembly reference for Microsoft.AspNetCore.SignalR.Client.Core, recursively...
  Adding assembly reference for Microsoft.AspNetCore.SignalR.Client, recursively...
  Adding assembly reference for Microsoft.AspNetCore.SignalR.Common, recursively...
  Adding assembly reference for Microsoft.AspNetCore.SignalR.Protocols.Json, recursively...
  Adding assembly reference for Microsoft.CSharp, recursively...
  Adding assembly reference for Microsoft.Data.Sqlite, recursively...
  Adding assembly reference for Microsoft.DotNet.PlatformAbstractions, recursively...
    Adding assembly reference for System.Runtime.InteropServices.RuntimeInformation, recursively...
    Adding assembly reference for System.AppContext, recursively...
    Adding assembly reference for System.IO.FileSystem, recursively...
    Adding assembly reference for System.Runtime.InteropServices, recursively...
  Adding assembly reference for Microsoft.Extensions.Caching.Abstractions, recursively...
  Adding assembly reference for Microsoft.Extensions.Caching.Memory, recursively...
  Adding assembly reference for Microsoft.Extensions.Configuration.Abstractions, recursively...
  Adding assembly reference for Microsoft.Extensions.Configuration.Binder, recursively...
  Adding assembly reference for Microsoft.Extensions.Configuration, recursively...
  Adding assembly reference for Microsoft.Extensions.DependencyInjection.Abstractions, recursively...
  Adding assembly reference for Microsoft.Extensions.DependencyInjection, recursively...
  Adding assembly reference for Microsoft.Extensions.DependencyModel, recursively...
    Adding assembly reference for System.IO.FileSystem.Primitives, recursively...
  Adding assembly reference for Microsoft.Extensions.Logging.Abstractions, recursively...
  Adding assembly reference for Microsoft.Extensions.Logging, recursively...
  Adding assembly reference for Microsoft.Extensions.Options, recursively...
  Adding assembly reference for Microsoft.Extensions.Primitives, recursively...
  Adding assembly reference for Mono.Android, recursively...
  Adding assembly reference for Mono.Android.Export, recursively...
  Adding assembly reference for mscorlib, recursively...
  Adding assembly reference for MySql.Data.CF, recursively...
  Adding assembly reference for Newtonsoft.Json, recursively...
  Adding assembly reference for Npgsql, recursively...
  Adding assembly reference for Oracle.ManagedDataAccess, recursively...
  Adding assembly reference for Plugin.CurrentActivity, recursively...
  Adding assembly reference for Plugin.Permissions, recursively...
  Adding assembly reference for Polly, recursively...
  Adding assembly reference for Refit, recursively...
  Adding assembly reference for Remotion.Linq, recursively...
    Adding assembly reference for System.Linq.Queryable, recursively...
  Adding assembly reference for RestSharp, recursively...
  Adding assembly reference for Simix.Mobile.Core, recursively...
  Adding assembly reference for Simix.SuperMidia.Core, recursively...
  Adding assembly reference for Simix.SuperMidia.Entities, recursively...
  Adding assembly reference for Simix.SuperMidia.Services, recursively...
  Adding assembly reference for SQLite-net, recursively...
  Adding assembly reference for SQLitePCL.raw, recursively...
  Adding assembly reference for SQLitePCLRaw.batteries_green, recursively...
  Adding assembly reference for SQLitePCLRaw.batteries_v2, recursively...
  Adding assembly reference for SQLitePCLRaw.core, recursively...
  Adding assembly reference for SQLitePCLRaw.lib.e_sqlite3, recursively...
  Adding assembly reference for SQLitePCLRaw.provider.e_sqlite3, recursively...
  Adding assembly reference for Symbol.XamarinEMDK, recursively...
  Adding assembly reference for System.Buffers, recursively...
  Adding assembly reference for System.Collections.Immutable, recursively...
  Adding assembly reference for System.Configuration.ConfigurationManager, recursively...
    Adding assembly reference for System.Security.Cryptography.ProtectedData, recursively...
      Adding assembly reference for System.Security, recursively...
  Adding assembly reference for System.Core, recursively...
  Adding assembly reference for System.Data, recursively...
  Adding assembly reference for System.Diagnostics.DiagnosticSource, recursively...
    Adding assembly reference for System.Diagnostics.Tracing, recursively...
  Adding assembly reference for System, recursively...
    Adding assembly reference for Mono.Security, recursively...
  Adding assembly reference for System.IO.Pipelines, recursively...
  Adding assembly reference for System.Json, recursively...
  Adding assembly reference for System.Memory, recursively...
  Adding assembly reference for System.Net, recursively...
  Adding assembly reference for System.Net.Http, recursively...
  Adding assembly reference for System.Runtime.CompilerServices.Unsafe, recursively...
  Adding assembly reference for System.Runtime, recursively...
  Adding assembly reference for System.Security.AccessControl, recursively...
  Adding assembly reference for System.Security.Permissions, recursively...
  Adding assembly reference for System.Security.Principal.Windows, recursively...
  Adding assembly reference for System.ServiceModel, recursively...
    Adding assembly reference for System.IdentityModel, recursively...
  Adding assembly reference for System.Threading.Channels, recursively...
  Adding assembly reference for System.Threading.Tasks.Extensions, recursively...
  Adding assembly reference for System.Web.Services, recursively...
  Adding assembly reference for System.Xml, recursively...
  Adding assembly reference for System.Xml.Linq, recursively...
  Adding assembly reference for System.Xml.Serialization, recursively...
  Adding assembly reference for Xamarin.Android.Arch.Core.Common, recursively...
  Adding assembly reference for Xamarin.Android.Arch.Lifecycle.Common, recursively...
  Adding assembly reference for Xamarin.Android.Arch.Lifecycle.Runtime, recursively...
  Adding assembly reference for Xamarin.Android.Support.Animated.Vector.Drawable, recursively...
  Adding assembly reference for Xamarin.Android.Support.Annotations, recursively...
  Adding assembly reference for Xamarin.Android.Support.Compat, recursively...
  Adding assembly reference for Xamarin.Android.Support.Core.UI, recursively...
  Adding assembly reference for Xamarin.Android.Support.Core.Utils, recursively...
  Adding assembly reference for Xamarin.Android.Support.Design, recursively...
  Adding assembly reference for Xamarin.Android.Support.Fragment, recursively...
  Adding assembly reference for Xamarin.Android.Support.Media.Compat, recursively...
  Adding assembly reference for Xamarin.Android.Support.Transition, recursively...
  Adding assembly reference for Xamarin.Android.Support.v4, recursively...
  Adding assembly reference for Xamarin.Android.Support.v7.AppCompat, recursively...
  Adding assembly reference for Xamarin.Android.Support.v7.CardView, recursively...
  Adding assembly reference for Xamarin.Android.Support.v7.MediaRouter, recursively...
  Adding assembly reference for Xamarin.Android.Support.v7.Palette, recursively...
  Adding assembly reference for Xamarin.Android.Support.v7.RecyclerView, recursively...
  Adding assembly reference for Xamarin.Android.Support.Vector.Drawable, recursively...
  Adding assembly reference for Xamarin.Android.Things, recursively...
Não é possível resolver o conflito entre "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" e "mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e". Escolhendo "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" arbitrariamente.
Não é possível resolver o conflito entre "System, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e" e "System, Version=2.0.0.0, Culture=neutral, PublicKeyToken=969db8053d3322ac, Retargetable=Yes". Escolhendo "System, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e" arbitrariamente.
Ignorando o destino "_CopyConfigFiles" porque todos os arquivos de saída estão atualizados em relação aos arquivos de entrada.
Ignorando o destino "_CopyIntermediateAssemblies" porque todos os arquivos de saída estão atualizados em relação aos arquivos de entrada.
Ignorando o destino "_ConvertPdbFiles" porque todos os arquivos de saída estão atualizados em relação aos arquivos de entrada.
Ignorando o destino "_CopyPdbFiles" porque todos os arquivos de saída estão atualizados em relação aos arquivos de entrada.
Ignorando o destino "_CopyMdbFiles" porque todos os arquivos de saída estão atualizados em relação aos arquivos de entrada.
Ignorando o destino "_LinkAssembliesShrink" porque todos os arquivos de saída estão atualizados em relação aos arquivos de entrada.
Ignorando o destino "_GenerateJavaStubs" porque todos os arquivos de saída estão atualizados em relação aos arquivos de entrada.
Ignorando o destino "_ConvertCustomView" porque todos os arquivos de saída estão atualizados em relação aos arquivos de entrada.
Unable to find //manifest/application/uses-library at path: C:\Program Files (x86)\Android\android-sdk\platforms\android-27\optional\com.symbol.emdk.jar
Unable to find //manifest/application/uses-library at path: C:\Program Files (x86)\Android\android-sdk\platforms\android-27\optional\com.google.android.things.jar
Ignorando o destino "_AddStaticResources" porque todos os arquivos de saída estão atualizados em relação aos arquivos de entrada.
Ignorando o destino "_GeneratePackageManagerJava" porque todos os arquivos de saída estão atualizados em relação aos arquivos de entrada.
Ignorando o destino "_CreateAdditionalResourceCache" porque ele não tem saídas.
Ignorando o destino "_GenerateAndroidAssetsDir" porque todos os arquivos de saída estão atualizados em relação aos arquivos de entrada.
Ignorando o destino "_CreateBaseApk" porque todos os arquivos de saída estão atualizados em relação aos arquivos de entrada.
Ignorando o destino "_CreateAdditionalResourceCache" porque ele não tem saídas.
Ignorando o destino "_CompileJava" porque todos os arquivos de saída estão atualizados em relação aos arquivos de entrada.
Ignorando o destino "_CreateAdditionalResourceCache" porque ele não tem saídas.
Ignorando o destino "_CompileToDalvikWithD8" porque todos os arquivos de saída estão atualizados em relação aos arquivos de entrada.
Excluindo o arquivo "bin\Debug\com.simix.supermidia.pro.apk".
Copiando o arquivo de "D:\Simix\SuperMidia\Xamarin\simix.supermidia\simix.supermidia\obj\Debug\81\android\bin\com.simix.supermidia.pro.apk" para "D:\Simix\SuperMidia\Xamarin\simix.supermidia\simix.supermidia\bin\Debug\com.simix.supermidia.pro.apk".
Criando "obj\Debug\81\android_debug_keystore.flag" porque "AlwaysCreate" foi especificado.
C:\Program Files\Android\Jdk\microsoft_dist_openjdk_1.8.0.25\bin\keytool.exe -list -alias androiddebugkey -storepass android -keypass android -keystore "C:\Users\felipe.baltazar\AppData\Local\Xamarin\Mono for Android\debug.keystore" 
Excluindo o arquivo "D:\Simix\SuperMidia\Xamarin\simix.supermidia\simix.supermidia\bin\Debug\com.simix.supermidia.pro-Signed.apk".
C:\Program Files (x86)\Android\android-sdk\build-tools\28.0.3\zipalign.exe -p 4 "D:\Simix\SuperMidia\Xamarin\simix.supermidia\simix.supermidia\obj\Debug\81\android\bin\com.simix.supermidia.pro.apk" "bin\Debug\\com.simix.supermidia.pro-Signed.apk" 
C:\Program Files\Android\Jdk\microsoft_dist_openjdk_1.8.0.25\bin\java.exe -jar "C:\Program Files (x86)\Android\android-sdk\build-tools\28.0.3\lib\apksigner.jar" sign --ks "C:\Users\felipe.baltazar\AppData\Local\Xamarin\Mono for Android\debug.keystore" --ks-pass pass:android --ks-key-alias androiddebugkey --key-pass pass:android --min-sdk-version 19 --max-sdk-version 27  D:\Simix\SuperMidia\Xamarin\simix.supermidia\simix.supermidia\bin\Debug\com.simix.supermidia.pro-Signed.apk 
Signed android package 'bin\Debug\com.simix.supermidia.pro-Signed.apk'
Excluindo o arquivo "obj\Debug\81\upload.flag".
Detecting installed packages...
Copying application to device...
10% ... 1408kb of 13507kb copied
20% ... 2752kb of 13507kb copied
30% ... 4096kb of 13507kb copied
40% ... 5440kb of 13507kb copied
60% ... 8128kb of 13507kb copied
80% ... 10816kb of 13507kb copied
90% ... 12160kb of 13507kb copied
100% ... 13507kb of 13507kb copied
ADB0000:  Deployment failed
Mono.AndroidTools.InstallFailedException: Failure [INSTALL_FAILED_MISSING_SHARED_LIBRARY]
   em Mono.AndroidTools.Internal.AdbOutputParsing.CheckInstallSuccess(String output, String packageName) na E:\A\_work\445\s\External\androidtools\Mono.AndroidTools\Internal\AdbOutputParsing.cs:linha 341
   em Mono.AndroidTools.AndroidDevice.<>c__DisplayClass95_0.<InstallPackage>b__0(Task`1 t) na E:\A\_work\445\s\External\androidtools\Mono.AndroidTools\AndroidDevice.cs:linha 753
   em System.Threading.Tasks.ContinuationTaskFromResultTask`1.InnerInvoke()
   em System.Threading.Tasks.Task.Execute()
ADB0010: Failure [INSTALL_FAILED_MISSING_SHARED_LIBRARY]
   em Mono.AndroidTools.Internal.AdbOutputParsing.CheckInstallSuccess(String output, String packageName) na E:\A\_work\445\s\External\androidtools\Mono.AndroidTools\Internal\AdbOutputParsing.cs:linha 341
   em Mono.AndroidTools.AndroidDevice.<>c__DisplayClass95_0.<InstallPackage>b__0(Task`1 t) na E:\A\_work\445\s\External\androidtools\Mono.AndroidTools\AndroidDevice.cs:linha 753
   em System.Threading.Tasks.ContinuationTaskFromResultTask`1.InnerInvoke()
   em System.Threading.Tasks.Task.Execute()
Projeto de compilação pronto "simix.supermidia.csproj" -- FALHA.
FALHA da compilação.
2>Falha ao implantar no Genymotion Custom Phone.
========== Compilar: 1 com êxito, 0 com falha, 0 atualizados, 0 ignorados ==========
========== Implantação: 0 com êxito, 1 com falha, 0 ignorados ==========

</details>

**Comment by Redth** [comment]
Do you have a sample you can share which reproduces this?

**Comment by simix-felipebaltazar** [comment]
@Redth Sorry, I've forgotten to share a sample

[AndroidThingsExample.zip](https://github.com/xamarin/XamarinComponents/files/3911244/AndroidThingsExample.zip)

Btw, its simple to reproduce:
1- Create an android project;
2- Add Xamarin.Android.Things nuget
3- Setup like below
4- Try to run on android

![image](https://user-images.githubusercontent.com/42358163/69959230-6737d500-14e5-11ea-87f3-29caf8bcca56.png)

**Comment by simix-felipebaltazar** [comment]
@Redth 
Was it possible to reproduce the problem?

**Comment by Redth** [comment]
@simix-felipebaltazar I can't reproduce the issue here.  I have a raspberry pi 3 running android things and I can deploy your project in both debug and release mode using the latest Visual Studio 2019 v16.4 stable release.

**Comment by Redth** [comment]
@simix-felipebaltazar i just realized i noticed the same error initially when I tried to deploy to a non-AndroidThings device `[INSTALL_FAILED_MISSING_SHARED_LIBRARY]`.  This is due to not running on an AndroidThings device.  Completely missed this in the first description/title.  Sorry, but I'm pretty confident this is your issue.

**Comment by simix-felipebaltazar** [comment]
@Redth 
My mistake, sorry about that...
I'm trying to use [Odroid C2](https://www.hardkernel.com/shop/odroid-c2/) with AndroidThings, in official google docs it is not mentioned...

**Comment by Redth** [comment]
Yeah unfortunately there is a shared library which exists in the Android Things OS itself and is needed at runtime for the things app.

**Comment by mcferdev** [comment]
@simix-felipebaltazar Vi que é brasileiro. Conseguiu fazer funcionar AR no Android ? Abs

**Comment by simix-felipebaltazar** [comment]
@mcferdev eu não tentei utilizar AR ainda, apenas estava tentando usar a parte IOT desse projeto.
Mas precisa ser um dispositivo que utilize  AndroidThings como sistema operacional
