### ISSUE TITLE
Mapbox Samples don't work - Is this project active?

### ISSUE THREAD

**Issue by dapug** [xamarin/XamarinComponents#76]
**MapboxSampleAndroid** wont even load. It hangs VS with indefinite "initializing" of the project.

**MapboxSampleiOS** will load, but wont build.  Error "Pointers and fixed size buffers may only be used in an unsafe context".  SO I marked several methods in Additions.cs with "unsafe" and I re-created the iOS project, and everything builds. BUT, when I deploy (to Simulator with iOS 10), I then get this error:

> System.Exception: Could not create an native instance of the type 'Mapbox.MapView': the native class hasn't been loaded.
> 
> It is possible to ignore this condition by setting ObjCRuntime.Class.ThrowOnInitFailure to false.

MapView.cs ctor

**My enviro:** 
VS 2015 Enterprise Update 3 installed with Xamarin 4.2.0.695. Running in VMware on Macbook, Xcode 8.0 (8A218a). Other iOS apps launch and run fine from VS (no issue with provisioning, etc).

As a side note, I am noting extremely sparse documentation for Mapbox (even on Mapbox end, not just Xamarin).  I would like to know how important Mapbox is to the community - what other xplat map solution is there if not this?  Will this be a key focus for Xamarin/MS?  I would think maps on mobile is a common requirement for a lot of developers out there. It's a obviously an official first class citizen in the Xamarin Components here, but I'm shocked to see the current state of all this.  I literally am dead in the water right now.

**Comment by Redth** [comment]
We have deprecated our bindings for Mapbox and have delisted the existing NuGet packages for them.

Please see the [README](https://github.com/xamarin/XamarinComponents/blob/master/XPlat/Mapbox/README.md) for more information.
