### ISSUE TITLE
Xamarin Build Targets error when building xamarin ios project

### ISSUE THREAD

**Issue by ramkrishnatkr** [xamarin/XamarinComponents#761]
Could not load file or assembly 'Microsoft.Win32.Registry, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

**Comment by ramkrishnatkr** [comment]
CrashlyticsSample application results in build error Xamarin.Firebase.iOS.Crashlytics v3.14.0 interaction with Xamarin.Build.Download v0.7.1

Could not load file or assembly 'Microsoft.Win32.Registry, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified. CrashlyticsSample ...\GoogleApisForiOSComponents-master\samples\Firebase\Crashlytics\CrashlyticsSample\packages\Xamarin.Build.Download.0.7.1\build\Xamarin.Build.Download.targets

**Comment by logeshpalani33** [comment]
Missing or corrupted your targeted iOS SDK version, check it or change you target version of project and try,.

**Comment by jmichas** [comment]
I am having this same problem too with any version of Xamarin.Build.Download that I try and Xamarin.Firebase.iOS.AdMob 7.47.0. I tried retargeting the iOS SDK and clean rebuilding but I get the same error. I even tried to manually download the firebase cache files and unpack them in the XamarinBuildDownloadCache directory but that had no effect either. 

I'm stuck at this point.

```
Task "XamarinDownloadArchives"
  Task Parameter:AllowUnsecureUrls=False
  Task Parameter:
      Archives=
          GAppM-6.0.4
                  Kind=Tgz
                  Url=https://dl.google.com/dl/cpdc/e025a69c2394726b/GoogleAppMeasurement-6.0.4.tar.gz
          FAnlytcs-6.0.4
                  Kind=Tgz
                  Url=https://dl.google.com/dl/cpdc/2717022184840456/FirebaseAnalytics-6.0.4.tar.gz
          FAdM-7.47.0
                  Kind=Tgz
                  Url=https://dl.google.com/dl/cpdc/5aa8adac9be8c6fe/Google-Mobile-Ads-SDK-7.47.0.tar.gz
          GCnsnt-1.0.3
                  Kind=Zip
                  Url=https://github.com/googleads/googleads-consent-sdk-ios/archive/v1.0.3.zip
  Task Parameter:DestinationBase=C:\Users\XXX\AppData\Local\XamarinBuildDownloadCache\
  Task Parameter:CacheDirectory=C:\Users\XXX\AppData\Local\XamarinBuildDownloadCache\
  Task Parameter:VsInstallRoot=C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise
  Task Parameter:IsAndroid=False
X:\Projects\XXX\XXX App\packages\Xamarin.Build.Download.0.8.0\build\Xamarin.Build.Download.targets(52,3): error : Could not load file or assembly 'Microsoft.Win32.Registry, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
Done executing task "XamarinDownloadArchives" -- FAILED.
```

**Comment by jmichas** [comment]
So, I changed my iOS project to use PackageReferences instead of packages.config and get a different output. I removed all the admob and xamarin.build.download nugets and I was able to build. Adding the admob stuff back gave me a bunch of native linker errors. It appears that the build download is not running.

I get 
`Target "_XamarinBuildDownloadMasterTarget" skipped, due to false condition; ('$(_XamarinBuildDownloadMasterDependsOnTargets)'!='') was evaluated as (''!='').`

not sure why it isnt running. I tried explicitly installing the build.download nuget but same issue every time.

**Comment by jmichas** [comment]
Well, I am able to build now. I cleaned and manually deleted the bin and obj directories.
Now I get warnings like this:
```
Could not resolve reference "C:\Users\XXX\AppData\Local\XamarinBuildDownloadCache\FAdM-7.47.0\Frameworks\GoogleMobileAdsFramework-Current\GoogleMobileAds.framework". If this reference is required by your code, you may get compilation errors. | XXX.Mobile.iOS | C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets 
```

How can I prevent these warnings?

**Comment by ramkrishnatkr** [comment]
The only solution I got was to downgrade Xamarin.Build.Download v0.4.11

**Comment by jmichas** [comment]
Yeah, a bit annoying, it doesn't seem to affect anything.
I just wanted to add for completeness, for anyone else who has struggled upgrading Admob or maybe any of the firebase stuff, the steps that have worked for me.

1. Upgrade from packages.config to PackageReference 
(You can do this by right clicking the project node in VS2019 I believe. I could not get any version combo to work with packages.config)
2. Right click the project node in VS2019 and clean
3. Manually go into the project folder and delete bin and obj
4. Go to your mac build server to ~/Library/Caches/Xamarin/mtbs/builds and delete your project folder in there
5. Right click project in VS2019 and rebuild

With any luck it will build and the only problem you will have is the warnings I mentioned above.
This also took me forever to figure out, I removed the admob nugets many times along with xamarin.build.download. I commented out my ad code and made sure everything built fine. Once I did that I committed and tinkered with adding different versions of the ad nugets and build download. It was painful but works now. BTW, I ended up with the latest admob and build download nugets I think 7.47 and 0.8

**Comment by lu-nguyen-khoa** [comment]
I have same issue, 

> "Could not load file or assembly 'Microsoft.Win32.Registry, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified."

But my parner's computer build it Ok. My PC have same problem.

**Comment by jmichas** [comment]
@haiduong741 Did you upgrade your iOS project to use PackageReferences? I had the same error on mine when I was using packages.config. I tried installing the Microsoft.Win32.Registry nuget but it made not differences until I switch to PackageReference.

**Comment by lu-nguyen-khoa** [comment]
@jmichas How to upgrade to use PackageReferences? I has found any solutions from internet but not working. 1 hour before, I was downgrade Xamarin.Build.Download from 8.0 to 4.11, It working.

**Comment by lu-nguyen-khoa** [comment]
I think this is a solution:
Step 1: Downgrade Xamarin.Build.Download to 4.11 -> Remove obj, bin -> Rebuild -> It worked
Step 2: Upgrade Xamarin.Build.Download to lastest version -> Remove obj, bin -> Rebuild -> It worked
I think maybe XamarinBuildDownloadCache had been broken. We downgrade to repair XamarinBuildDownloadCache.

**Comment by Shubham-Pawaiya** [comment]
> I think this is a solution:
> Step 1: Downgrade Xamarin.Build.Download to 4.11 -> Remove obj, bin -> Rebuild -> It worked
> Step 2: Upgrade Xamarin.Build.Download to lastest version -> Remove obj, bin -> Rebuild -> It worked
> I think maybe XamarinBuildDownloadCache had been broken. We downgrade to repair XamarinBuildDownloadCache.

After doing these steps, IOS project works but my android project give this error:-
`The "Xamarin.Build.Download.XamarinBuildAndroidAarRestore" task could not be loaded from the assembly C:\Users\USERNAME\.nuget\packages\xamarin.build.download\0.4.11\build\Xamarin.Build.Download.dll.  Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.	`

**Comment by lu-nguyen-khoa** [comment]
> > I think this is a solution:
> > Step 1: Downgrade Xamarin.Build.Download to 4.11 -> Remove obj, bin -> Rebuild -> It worked
> > Step 2: Upgrade Xamarin.Build.Download to lastest version -> Remove obj, bin -> Rebuild -> It worked
> > I think maybe XamarinBuildDownloadCache had been broken. We downgrade to repair XamarinBuildDownloadCache.
> 
> After doing these steps, IOS project works but my android project give this error:-
> `The "Xamarin.Build.Download.XamarinBuildAndroidAarRestore" task could not be loaded from the assembly C:\Users\USERNAME\.nuget\packages\xamarin.build.download\0.4.11\build\Xamarin.Build.Download.dll. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. `

Android we can uninstall Xamarin.Build.Download. I had install iOS project only. Notifications works well.

**Comment by Shubham-Pawaiya** [comment]
> > > I think this is a solution:
> > > Step 1: Downgrade Xamarin.Build.Download to 4.11 -> Remove obj, bin -> Rebuild -> It worked
> > > Step 2: Upgrade Xamarin.Build.Download to lastest version -> Remove obj, bin -> Rebuild -> It worked
> > > I think maybe XamarinBuildDownloadCache had been broken. We downgrade to repair XamarinBuildDownloadCache.
> > 
> > 
> > After doing these steps, IOS project works but my android project give this error:-
> > `The "Xamarin.Build.Download.XamarinBuildAndroidAarRestore" task could not be loaded from the assembly C:\Users\USERNAME\.nuget\packages\xamarin.build.download\0.4.11\build\Xamarin.Build.Download.dll. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask. `
> 
> Android we can uninstall Xamarin.Build.Download. I had install iOS project only. Notifications works well.

Unistalled it from Android but still it isnt working. and giving same error.

**Comment by AmirMahdiNassiri** [comment]
I have the same issue using the latest version of Xamarin (4.54.5.0.356) and the latest Visual Studio 2019. I also tried different versions of Xamarin.Build.Download, ranging from 0.4.11 to the latest 0.10. Nothing works for me!

**Comment by lu-nguyen-khoa** [comment]
> (4.54.5.0.356)
Xamarin not has this version :D 
- You try go to C:\Users\[Username]\AppData\Local Remove Folder XamarinBuildDownloadCache (Windows) and install Xamarin.Build.Download version 4.11. Build and Run
My versions: 
- XF: 4.4 lastest
- Xamarin.Build.Download: 4.11

**Comment by shalomthegreat** [comment]
I was having the exact same problem and followed all the suggestions I could find. T**he only thing that finally worked**: right click your project.iOS and select manage nuget packages, search for Xamarin.Build.Download and install or update (mine was updated from 0.8 to 0.10). 

(I could even undo those changes from the project directory and the build is still working.)

**Comment by lmcckl** [comment]
VS2019, I delete the nuget cache, bin and obj folders. work for me

**Comment by rettigcd** [comment]
I had a similar problem.  The issue was that the package it is trying to extract contains files with names that are too long for Windows 10.
