### ISSUE TITLE
Mono.Options NuGet version update?

### ISSUE THREAD

**Issue by beevik** [xamarin/XamarinComponents#763]
The last time the [NuGet package](https://www.nuget.org/packages/Mono.Options/) for this repo was updated was June 2, 2017.  Since that time, Mono.Options has added a number of new features (like nested CommandSets) that I'd like to use in one of my projects.

Are there any plans to update the NuGet package for Mono.Options?

**Comment by logeshpalani33** [comment]
Update you're mono version manually
