### ISSUE TITLE
Adding refrence to 'Xamarin.Android.Crashlytics' causes multiple compile time errors

### ISSUE THREAD

**Issue by sachinkanadia** [xamarin/XamarinComponents#767]
Hi There,

When adding a reference through Nuget to Xamarin.Android.Crashlytics version 2.9.4.3 for my Xamarin.Android project I receive a whole host of compile time errors:

![AndroidCrashlyticsErrors](https://user-images.githubusercontent.com/18262347/70868359-ff1ecf80-1f77-11ea-8b85-60ffaa210ea7.png)

Please can you advise on how to resolve these issues.

Thanks

**Comment by Redth** [comment]
Are you using AAPT2?

**Comment by Redth** [comment]
This appears to be a duplicate of #766
Closing and tracking issue there.

**Comment by axayi** [comment]
i have the similar issue i am using VS 2017 15.9.21  and Xamarin.Android.Crashlytics  version 2.9.4.1
for my Xamarin.Android project I receive build errors.

**Comment by axayi** [comment]
i have supporting packages as follows 
Xamarin.Android.Crashlytics- package version 2.9.4.1
Xamarin.Android.Crashlytics.Answers - - package version 1.4.2
Xamarin.Android.Crashlytics.Beta - package version 1.2.9
Xamarin.Android.Crashlytics.Core - package version 2.6.3
Xamarin.Android.Fabric- package version 1.4.3


anyone knows about this how i can resolve  ? If i uninstall all these packages i.e crashlytics supporting.
then app will works fine but i need to include crashlytics
