### ISSUE TITLE
CrashlyticsSample application results in build error Xamarin.Firebase.iOS.Crashlytics v3.14.0 interaction with Xamarin.Build.Download v0.7.1 

### ISSUE THREAD

**Issue by ramkrishnatkr** [xamarin/XamarinComponents#770]
Could not load file or assembly 'Microsoft.Win32.Registry, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.	CrashlyticsSample	...\GoogleApisForiOSComponents-master\samples\Firebase\Crashlytics\CrashlyticsSample\packages\Xamarin.Build.Download.0.7.1\build\Xamarin.Build.Download.targets	52

**Comment by mattleibow** [comment]
@Redth any idea why XBD references Win32 registry?

**Comment by Redth** [comment]
No, haven’t looked closely yet.

**Comment by antonioseric** [comment]
I am having same issue with newer version [3.14.0.3](https://www.nuget.org/packages/Xamarin.Firebase.iOS.Crashlytics/3.14.0.3) and  Xamarin.Build.Download v0.9.0
