### ISSUE TITLE
Xamarin.Build.Download potentially duplicating .aar's

### ISSUE THREAD

**Issue by Redth** [xamarin/XamarinComponents#771]
It seems that if a NuGet package embeds a .aar but also specifies Xamarin.Build.Download restore metadata, there may be duplicate .aar's included in the app packaging.

**Comment by jonathanpeppers** [comment]
I had some more details over here: https://github.com/xamarin/xamarin-android/pull/4043#discussion_r360230852

**Comment by Redth** [comment]
PR #774 should help resolve this.  XBD 0.8.0 is released.
