### ISSUE TITLE
after adding sdwebimage.ios apple rejects it 

### ISSUE THREAD

**Issue by nininea1** [xamarin/XamarinComponents#786]
Your app uses or references the following non-public APIs:

- LinkPresentation.framework
- QuickLookThumbnailing.framework

The use of non-public APIs is not permitted on the App Store because it can lead to a poor user experience should these APIs change.

any solution ?

**Comment by newky2k** [comment]
@nininea1  I had a look on the Xamarin side and the native source and I can't see any references to either of those frameworks(at least from a cursory search of the code).  Have you adding anything else?

**Comment by Redth** [comment]
We are closing this issue since no response was received.  Please open a new issue referring to this one if you have more information.
