### ISSUE TITLE
Error when building project with Xamarin.Android.Crashlytics

### ISSUE THREAD

**Issue by shults-s** [xamarin/XamarinComponents#814]
### Steps to Reproduce
1. Install ```Xamarin.Android.Crashlytics``` package.
In my case, I had to manually install the following packages due to an error NU1607 (Version conflict detected): ```Xamarin.GooglePlayServices.Basement```, ```Xamarin.GooglePlayServices.Tasks```, ```Xamarin.Firebase.Iid```, ```Xamarin.Firebase.Common```, ```Xamarin.Build.Download```.
2. Try to build solution.

### Expected Behavior
Successful build.

### Actual Behavior
Build failed with error ```Type com.google.android.gms.common.internal.zzf is referenced as an interface from `com.google.android.gms.internal.zzcfb.``` produced by D8 both in Debug and Release modes. And lots of warnings NU1608 (Detected package version outside of dependency constraint).
At the same time, the Firebase Cloud Messaging is working fine.

### Version Information
* Microsoft Visual Studio Community 2019 16.4.4
* Xamarin 16.4.000.309 (d16-4@1d551f9)
* Xamarin.Android SDK  10.1.3.7 (d16-4/d66aed0)
* Xamarin.Android Tools: xamarin/xamarin-android-tools/master@9f4ed4b

**Comment by virsanna** [comment]
I second the issue. 
Firebase Cloud Messaging isn't used, but Firebase Authentication is working fine.

Microsoft Visual Studio Community 2019 16.5.4
Xamarin 16.5.000.533 (d16-5@9152e1b)
Xamarin.Android SDK   10.2.0.100 (d16-5/988c811)
Xamarin.Android Tools: xamarin/xamarin-android-tools/d16-5@9f4ed4b

**Comment by ivanj9** [comment]
Same error. 
Firebase Cloud Messaging is working with no issues.

Microsoft Visual Studio Enterprise 2019 Version 16.6.2
Xamarin   16.6.000.1061 (d16-6@8e68aa8)
Xamarin.Android SDK   10.3.1.4 (d16-6/3a10de9)

**Comment by tamasszadvari** [comment]
Try to add the Xamarin.Firebase.Core NuGet package with the same version as the other Xamarin.Firebase.* packages which you have already added to your project. The auto-resolving function for the NuGet package dependencies can cause this, and adding the Xamarin.Firebase.Core package with the required version explicitly solved the issue for me.

**Comment by criapix** [comment]
> Try to add the Xamarin.Firebase.Core NuGet package with the same version as the other Xamarin.Firebase.* packages which you have already added to your project. The auto-resolving function for the NuGet package dependencies can cause this, and adding the Xamarin.Firebase.Core package with the required version explicitly solved the issue for me.

Thanks @tamasszadvari . Adding manually the Xamarin.Firebase.Core package solved my case.

**Comment by moljac** [comment]
Problem solved. Closing this one
