### ISSUE TITLE
Unable to cast object of type 'MaterialComponents.TabBarUnderlineIndicatorTemplate' to type 'MaterialComponents.TabBarIndicatorTemplate'

### ISSUE THREAD

**Issue by Digifais** [xamarin/XamarinComponents#821]
Add a `MaterialComponents.TabBar` on iOS, inspect the property `SelectionIndicatorTemplate` of the `TabBar` while debugging and you can see that following exception is thrown:

> System.InvalidCastException: Unable to cast object of type 'MaterialComponents.TabBarUnderlineIndicatorTemplate' to type 'MaterialComponents.TabBarIndicatorTemplate'

**Comment by nullpotent** [comment]
I solved this by not using the property and instead just calling the objective-c setter directly:

`TabBar.PerformSelector(new ObjCRuntime.Selector("setSelectionIndicatorTemplate:"), new MyIndicator());`
