### ISSUE TITLE
Still using 'Xamarin.Android.Support.v7.RecyclerView 28.0.0.1' in Nuget package. This is prohibiting a migration over to androidX. 

### ISSUE THREAD

**Issue by RashadAkoodieRabbit** [xamarin/XamarinComponents#828]

**Comment by JMan7777** [comment]
Same issue here with other packages from MS as well.

Square.Picasso 2.71828.0 -> Xamarin.Android.Support.Annotations (>= 28.0.0.3) 

Please migrate to Android X. 

Thx

**Comment by moljac** [comment]
@RashadAkoodieRabbit 

Who/what is still using `Xamarin.Android.Support.v7.RecyclerView` v 28.0.0.1?

@JMan7777 

Square.Picasso:

https://mvnrepository.com/artifact/com.squareup.picasso/picasso/2.71828

https://search.maven.org/artifact/com.squareup.picasso/picasso/2.71828/pom

Android Support 27.1.0

Bottom line: we cannot migrate to AndroidX before library that is bound migrates. This problem have Android java and kotlin developers too.
