### ISSUE TITLE
Missing androidx.room.RxRoom package?

### ISSUE THREAD

**Issue by sgong-pdftron** [xamarin/XamarinComponents#832]
The only two Room packages I can find are:

https://www.nuget.org/packages/Xamarin.AndroidX.Room.Runtime/
https://www.nuget.org/packages/Xamarin.AndroidX.Room.Common/

The RxJava2 support is missing from these two packages.

Any plan on creating the RxRoom package?
https://developer.android.com/reference/androidx/room/RxRoom

Thank you very much for your help!

**Comment by moljac** [comment]
@sgong-pdftron 
Why creating issue in this repo?

Please report AndroidX issues in AndroidX repository:

https://github.com/xamarin/AndroidX

If you open it in AndroidX, please close this one here.

**Comment by moljac** [comment]
Closing this one

**Comment by sgong-pdftron** [comment]
Thanks @moljac I've created the new issue here: https://github.com/xamarin/AndroidX/issues/107 Thanks!
