### ISSUE TITLE
MapBox SDK iOS

### ISSUE THREAD

**Issue by Julien-Mialon** [xamarin/XamarinComponents#84]
Hello,

Great job on the MapBox ios SDK, I just have one issue with this, when trying to use offline storage, I can't access fields of struct OfflinePackProgress (https://github.com/xamarin/XamarinComponents/blob/master/XPlat/Mapbox/iOS/source/MapboxSDK.iOS/StructsAndEnums.cs#L73-L78)

I can guess it's because they are not marked as public, but is there any reason for this ?

Thanks,
Julien.

**Comment by Redth** [comment]
We have deprecated our bindings for Mapbox and have delisted the existing NuGet packages for them.

Please see the [README](https://github.com/xamarin/XamarinComponents/blob/master/XPlat/Mapbox/README.md) for more information.
