### ISSUE TITLE
Xamarin Android Crashlytics build Errors

### ISSUE THREAD

**Issue by axayi** [xamarin/XamarinComponents#881]
i have the similar issue i am using VS 2017 15.9.21 and Xamarin.Android.Crashlytics version 2.9.4.1
for my Xamarin.Android project I receive build errors.
The same setup was working at my workstation desktop but now i am laptop and haven't made any changes to the solution

i have supporting packages as follows
Xamarin.Android.Crashlytics- package version 2.9.4.1
Xamarin.Android.Crashlytics.Answers - - package version 1.4.2
Xamarin.Android.Crashlytics.Beta - package version 1.2.9
Xamarin.Android.Crashlytics.Core - package version 2.6.3
Xamarin.Android.Fabric- package version 1.4.3

anyone knows about this how i can resolve ? If i uninstall all these packages i.e crashlytics supporting.
then app will works fine but i need to include crashlytics

**Comment by moljac** [comment]
@cmnagaraj610 thanks for the feedback.

Copy text and paste it here, please.

Save images for Instagram.

**Comment by axayi** [comment]
Error details

1.    Error		Download failed. Please download https://maven.google.com/com/crashlytics/sdk/android/crashlytics/2.9.4/crashlytics-2.9.4.aar to a file called **Local project path** \XamarinBuildDownloadCache\crashlytics-2.9.4..aar.	

2. Error		Download failed. Please download https://maven.google.com/com/crashlytics/sdk/android/beta/1.2.9/beta-1.2.9.aar to a file called **Local project path** \XamarinBuildDownloadCache\crashlyticsbeta-1.2.9..aar.				

3.   Error		Download failed. Please download https://maven.google.com/com/crashlytics/sdk/android/answers/1.4.2/answers-1.4.2.aar to a file called  **Local project path** \XamarinBuildDownloadCache\crashlyticsanswers-1.4.2..aar.

**Comment by moljac** [comment]
We are not allowed to host binaries (jars, aars, zips) in our repo, so in order to do binding those must be downloaded and this is done in cake script with target `externals` (in most cases). So:

```
dotnet cake -t=externals
```

or to run complete build

```
dotnet cake -t=ci
```

It is all here: https://github.com/xamarin/XamarinComponents#building

Closing this one, because it is not an issue.
