### ISSUE TITLE
Xamarin.Android.ManifestMerger causes crash on build

### ISSUE THREAD

**Issue by gvuksa** [xamarin/XamarinComponents#882]
AndroidManifestMerger prevents build with Xamarin.Android 10.2 SDK version. This issue happens in the App Center. In VS it builds normally.

**Comment by gvuksa** [comment]
Update, Xamarin.Android.ManifestMerger prev-3 is not compatible with android SDK 10.2

**Comment by moljac** [comment]
@gvuksa 
Forget `Xamarin.Android.ManifestMerger` nuget. The reason it never was published as stable is that manifest merging is now part of build (Xamarin.Android core) which is more logical.

Add this MsBuild property to your build (csproject):

```
  <PropertyGroup>
    <AndroidManifestMerger>manifestmerger.jar</AndroidManifestMerger>
  </PropertyGroup>
```

https://github.com/xamarin/GooglePlayServicesComponents/blob/master/source/GooglePlayServicesTargets.cshtml#L30-L32

If that fixes your problem, please close this issue yourself.

**Comment by gvuksa** [comment]
@moljac thanks for the info. The reason I was using Xamarin.Android.ManifestMerger was because of the issue with FirebaseAuth.Instance always being null. However, it seems that with Android SDK 10.2 this is no longer a case, the issue with FireabaseAuth is resolved and it does not require ManifestMerger or any other change in to the project. So, although ManifestMerger still crashes build I will close this issue.
