### ISSUE TITLE
Glide Compatibility with AndroidX

### ISSUE THREAD

**Issue by velocitysystems** [xamarin/XamarinComponents#904]
Given it is recommended to upgrade from Android support libraries to AndroidX, may an updated version of `Xamarin.Android.Glide` please be released based on **Glide 4.10.0 and above**?

We have recently upgraded our app to target Android 10 (API 29) but are unable to use `Xamarin.Android.Glide` due to its dependency on `Xamarin.Android.Support.v4 (>= 28.0.0.1)`. We originally raised this issue [here](https://github.com/jonathanpeppers/glidex/issues/62). 

@jonathanpeppers Who maintains the [glidex](https://github.com/jonathanpeppers/glidex) package is willing to provide an updated release for AndroidX compatibility once this dependency is updated. Thanks so much!

**Comment by velocitysystems** [comment]
Hi @Redth @mattleibow, do you possibly have any thoughts on this?

**Comment by Redth** [comment]
We have a PR up: https://github.com/xamarin/XamarinComponents/pull/916

**Comment by velocitysystems** [comment]
Awesome @Redth! Look forward to seeing it merged. Great news!

**Comment by Redth** [comment]
Merged, released!

**Comment by velocitysystems** [comment]
Fantastic, great work!
