### ISSUE TITLE
Square bindings

### ISSUE THREAD

**Issue by tranb3r** [xamarin/XamarinComponents#924]
Square.Picasso bindings have been recently migrated from mattleibow/square-bindings to this repo.
Could you please do the same thing with other square bindings (OkHttp, OkIO, UrlConnection ...) ?
These projects do not seem to be maintained anymore in mattleibow/square-bindings, and moving them here would definitely give them more visibility.

**Comment by mattleibow** [comment]
I want to do that. Just haven't gotten to it yet. But that is the plan.

If you need something right now, then you can also just move it there and I can review the PR. Rather move, merge and then update.

All the projects are separate so you don't have to worry about references between them.

**Comment by tranb3r** [comment]
Unfortunately I don't have the time to work on this now.
Adding @4brunu and @antonioseric and @galcantara-asapp : maybe one of you guys could be interested to help with this task...

**Comment by antonioseric** [comment]
@tranb3r i can help you with this task...

**Comment by antonioseric** [comment]
@tranb3r @mattleibow I create PR #948 for android binding will create new one for other projects...

**Comment by mattleibow** [comment]
@antonioseric thanks for the PR!

The bits are merged!
