### ISSUE TITLE
Created a plugin, could you add it to the list?

### ISSUE THREAD

**Issue by AnthroHeader** [xamarin/XamarinComponents#94]
I have created a cross platform library to get application identity information (app display name, package id and version string), attempting to follow all the requirements for creating Xamarin Plugins.

The project is hosted at [albertofustinoni/AppInfoPlugin](https://github.com/albertofustinoni/AppInfoPlugin) and a [NuGet package](https://www.nuget.org/packages/Xam.Plugin.AppInfo) is available

If it qualifies, would it be possible to add it to the list of Xamarin Plugins?

**Comment by jamesmontemagno** [comment]
Thanks for submitting, we review all of the plugins on a monthly basis.
