### ISSUE TITLE
Play Core In-App Review bindings

### ISSUE THREAD

**Issue by jooni91** [xamarin/XamarinComponents#946]
Are there any plans on adding bindings for the Play Core in-app review feature in Xamarin.Android?
I noticed that 'in-app update' bindings exist, but I couldn't find anything pointing to the existence of in-app review bindings. Can we expect to see that any time soon?

This feature does add great value to Android apps by bringing the review experience directly into the app like you can on iOS with the `SKStoreReviewController`.

More about the feature: https://developer.android.com/guide/playcore/in-app-review#when-to-request

**Comment by moljac** [comment]
Play.Core was bound while ago, but I have issues on CI and not enough time to dive in deeper.

https://github.com/xamarin/XamarinComponents/pull/936

https://github.com/xamarin/XamarinComponents/pull/937

https://github.com/xamarin/XamarinComponents/pull/938

**Comment by saamerm** [comment]
Great news @moljac and @jooni91, I just did it here: 
https://github.com/PatGet/XamarinPlayCoreUpdater

You can clone it, test it and play around with it!

**Comment by moljac** [comment]
closing this one.

Play.Core is available in GPS-FB-MLKit repo

https://github.com/xamarin/GooglePlayServicesComponents/
