### ISSUE TITLE
SceneForm cake build Error

### ISSUE THREAD

**Issue by M1tiens** [xamarin/XamarinComponents#953]
I'm having an issue on building using the cake process for the sceneform component. While trying to build i get the following output log

"/Users/andre/Downloads/XamarinComponents-master/Android/SceneForm/SceneForm.sln" (Restore;Build target) (1) ->
"/Users/andre/Downloads/XamarinComponents-master/Android/SceneForm/source/Animation/Animation.csproj" (default target) (2:6) ->
"/Users/andre/Downloads/XamarinComponents-master/Android/SceneForm/source/Rendering/Rendering.csproj" (default target) (7:9) ->
(CoreCompile target) -> 
  obj/Release/monoandroid90/generated/src/Google.AR.Sceneform.Rendering.ViewRenderable.cs(101,70): error CS0426: The type name 'Builder' does not exist in the type 'Renderable' [/Users/andre/Downloads/XamarinComponents-master/Android/SceneForm/source/Rendering/Rendering.csproj]
  obj/Release/monoandroid90/generated/src/Google.AR.Sceneform.Rendering.EnvironmentalHdrLightEstimate.cs(148,93): error CS0426: The type name 'CubeMapImage' does not exist in the type 'EnvironmentalHdrLightEstimate' [/Users/andre/Downloads/XamarinComponents-master/Android/SceneForm/source/Rendering/Rendering.csproj]
  obj/Release/monoandroid90/generated/src/Google.AR.Sceneform.Rendering.ModelRenderable.cs(108,70): error CS0426: The type name 'Builder' does not exist in the type 'Renderable' [/Users/andre/Downloads/XamarinComponents-master/Android/SceneForm/source/Rendering/Rendering.csproj]

Tried other projects such as ARCORE

**Comment by Andrec-Dxs** [comment]
Issue solved... Code fix is on a pull request

**Comment by moljac** [comment]
closing this issue
