### ISSUE TITLE
Xamarin.Android.Crashlytics: Update to latest by Nov 15,2020

### ISSUE THREAD

**Issue by krishnaxamarin** [xamarin/XamarinComponents#956]
Hi Everyone, 

We are getting below message in Firebase and needs to be changed by NOV 15 2020. Can we get the package updated to the latest for Crashlytics? 

"Note: The Fabric SDK is now deprecated and will continue reporting your app's crashes until November 15, 2020. On this date, the Fabric SDK and old versions of the Firebase Crashlytics SDK will stop sending crashes for your app. To continue getting crash reports in the Firebase console, make sure you upgrade to the Firebase Crashlytics SDK versions 17.0.0+ for Android, 4.0.0+ for iOS, and 6.15.0+ for Unity."

**Comment by sbkrishnan2506** [comment]
Hello,
Is there any update on this issue?

Note: The Fabric SDK is now deprecated and will continue reporting your app's crashes until November 15, 2020. On this date, the Fabric SDK and old versions of the Firebase Crashlytics SDK will stop sending crashes for your app. To continue getting crash reports in the Firebase console, make sure you upgrade to the Firebase Crashlytics SDK versions 17.0.0+ for Android, 4.0.0+ for iOS, and 6.15.0+ for Unity.

Please let us know, if any other way to resolve this issue.

Thanks

**Comment by krishnaxamarin** [comment]
Hi, Can anyone provide an update for this issue ?

**Comment by trinnguyen** [comment]
Found this one: https://www.nuget.org/packages/Xamarin.Firebase.Crash which is from the same repository as other bindings for Firebase services.

But still, the latest version (including the preview one) is based on version 16+ instead of 17+. Found latest development here: https://github.com/xamarin/GooglePlayServicesComponents/blob/master_based_androidx_based_updates_202006/config.json

**Comment by jeremiethibeault** [comment]
I believe this is the version on Crashlytics 17 https://www.nuget.org/packages/Xamarin.Firebase.Crashlytics/117.0.0-preview02.

This commit updates the config.json file [fc2fdf62](https://github.com/xamarin/GooglePlayServicesComponents/commit/fc2fdf62c38c121eff6863234a926ba8b9a6f0ef#diff-06b2d3b23dce96e1619d2b53d6c947ecR32)

**Comment by trinnguyen** [comment]
@jeremiethibeault You are right! Firebase use new artifactId for crashlytics 17+, `com.google.firebase:firebase-crashlytics` as specified in the config.json file. Would go with this Nuget package.

**Comment by PTEC3D50** [comment]
Hello everyone, I currently try to make the Xamarin.Firebase.Crash work on my app, but I struggle there is no Crash reported to my Console.
Can someone explain how to use this nuget since there is not a simple documentation for this nuget? @jeremiethibeault @trinnguyen

**Comment by polieadie** [comment]
Does anybody able to make this work? https://www.nuget.org/packages/Xamarin.Firebase.Crashlytics/117.0.0-preview02
I am having this error:
Java.Lang.RuntimeException
  Message=Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.IllegalStateException: The Crashlytics build ID is missing. This occurs when Crashlytics tooling is absent from your app's build configuration. Please review Crashlytics onboarding instructions and ensure you have a valid Crashlytics account.

**Comment by PaulsonM** [comment]
What will be the version of Xamarin.Firebase.iOS.Crashlytics that addresses this update?

**Comment by sasa-bobic** [comment]
From Firebase source:

https://github.com/firebase/firebase-android-sdk/blob/master/firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsCore.java#L110

https://github.com/firebase/firebase-android-sdk/blob/aa3c89f5217a72d83a55f771d1ad5a12483f9aaf/firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CommonUtils.java#L805

It seems new Crashlytics SDK depends on "mapping file" resource id being available at runtime (I'm guessing generated by gradle?).

Is don't have this exception @polieadie mentioned after manually adding this string resource:
`<string name="com.google.firebase.crashlytics.mapping_file_id">none</string>`

**Comment by AjayK17** [comment]
Can anyone please suggest how to use this as i have not found any reference for it-
https://www.nuget.org/packages/Xamarin.Firebase.Crashlytics/117.0.0-preview02

**Comment by polieadie** [comment]
> From Firebase source:
> 
> https://github.com/firebase/firebase-android-sdk/blob/master/firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CrashlyticsCore.java#L110
> 
> https://github.com/firebase/firebase-android-sdk/blob/aa3c89f5217a72d83a55f771d1ad5a12483f9aaf/firebase-crashlytics/src/main/java/com/google/firebase/crashlytics/internal/common/CommonUtils.java#L805
> 
> It seems new Crashlytics SDK depends on "mapping file" resource id being available at runtime (I'm guessing generated by gradle?).
> 
> Is don't have this exception @polieadie mentioned after manually adding this string resource:
> `<string name="com.google.firebase.crashlytics.mapping_file_id">none</string>`

I still receive the error below:
![image](https://user-images.githubusercontent.com/28383778/95178816-71f08400-07f2-11eb-9e29-9c819a7b939e.png)

I already included the string resource here:
![image](https://user-images.githubusercontent.com/28383778/95178969-99dfe780-07f2-11eb-809d-5b80ff6ec0b8.png)

**Comment by sasa-bobic** [comment]
@polieadie I can only think of: try cleaning you solution and/or check file properties (build action) for that xml (/Resources/values/string.xml).

I just check in my test project; removing that string and the exception is back; no exception otherwise.

![strings](https://user-images.githubusercontent.com/55833702/95180782-b95f1c00-07c2-11eb-9ca3-af55bb6c0f73.PNG)
![strings_properties](https://user-images.githubusercontent.com/55833702/95180794-bbc17600-07c2-11eb-8490-f78869f8e235.PNG)

**Comment by polieadie** [comment]
@sasa-bobic Clean - Close - Open the solution worked for me. Thank you very much for you support.
However, up to this time, I still don't see anything on Crashlytics dashboard.

![image](https://user-images.githubusercontent.com/28383778/95286476-06f88900-0896-11eb-9d69-787801851a30.png)

**Comment by polieadie** [comment]
All working now after I archived.
Thank you very much @sasa-bobic 👍

**Comment by AjayK17** [comment]
@polieadie Can you please suggest how to use/initialise Crashlytics using this package - 
[https://www.nuget.org/packages/Xamarin.Firebase.Crashlytics/117.0.0-preview02]

Any documentation or example reference would be great.
Thanks

**Comment by polieadie** [comment]
@AjayK17
I assume you haven't tried it yet?
No need to initialize as it will do it by itself.
You just need to install as well all the dependencies.
You can't find any documentation for now as it is still on beta.
Please try first instead of looking for documentation just like I did or everybody else.

**Comment by AmoseKumar24** [comment]
@polieadie 
Below are steps i followed for xamarin firebase crashlytics
I installed Xamain.Firebase.Crashlytics 117preview02 version.
I was getting this error when i run the app

Java.Lang.RuntimeException: 'Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.IllegalStateException: 
The Crashlytics build ID is missing. This occurs when Crashlytics tooling is absent from your app's build configuration. 
Please review Crashlytics onboarding instructions and ensure you have a valid Crashlytics account.'

after adding this code 
<img width="506" alt="Code" src="https://user-images.githubusercontent.com/72500936/95415183-3f0ed300-094d-11eb-9101-0832a88cca6f.PNG">

issue is fixed

after that i was getting this error when i run the app
Java.Lang.NoSuchMethodError: 'No static method checkBuilderRequirement(Ljava/lang/Object;Ljava/lang/Class;)V in class Ldagger/internal/Preconditions; 
or its super classes (declaration of 'dagger.internal.Preconditions' appears in /data/app
after that i added the Xamain.goodle.dagger package, issue is fixed

now able to run the app and i made the app crash but crash is not updated in firebase console crashlytics dashboard. it is showing like this. Please advise me if i missed anything
<img width="623" alt="Sample" src="https://user-images.githubusercontent.com/72500936/95412810-711d3680-0947-11eb-8042-77887cc4bfa0.PNG">

**Comment by polieadie** [comment]
@AmoseKumar24 
You are on the right track.
Did you already tried to build on Release mode?
Also, try to monitor the build output if the initialization is successful.

**Comment by AmoseKumar24** [comment]
Yes @polieadie i already tried release mode
Just now i checked build output window 
10-08 11:03:01.871 I/FirebaseCrashlytics(16125): Initializing Crashlytics 17.0.0
10-08 11:03:01.936 I/FirebaseInitProvider(16125): FirebaseApp initialization successful
firebase initialization is successful

10-08 11:03:47.717 E/FirebaseCrashlytics(16125): Settings request failed.
i am also getting this message in output window. Have you got this?

**Comment by codeanees** [comment]
Hi Team,

I am little confused with this.  For our app we are using **Xamarin.Android.Crashlytics** which is in production/live.  However. I do receive an email from Firebase team stating  "Please upgrade to the Firebase Crashlytics SDK by November 15, 2020 to continue getting crash reports,"  

Does this mean, If we don't upgrade the app, Will it impact the app? What are all the implications if we don't do this?

I saw people commenting to use **Xamarin.Firebase.Crashlytics**? Does this a simple change?

**Comment by trinnguyen** [comment]
@codeanees Have a look at the official Firebase Crashlytics page: https://firebase.google.com/docs/crashlytics/get-started?platform=android

The full note is:
*Note: The Fabric SDK is now deprecated and will continue reporting your app's crashes until November 15, 2020. On this date, the Fabric SDK and old versions of the Firebase Crashlytics SDK will stop sending crashes for your app. To continue getting crash reports in the Firebase console, make sure you upgrade to the Firebase Crashlytics SDK versions 17.0.0+ for Android, 4.0.0+ for iOS, and 6.15.0+ for Unity.*

> What are all the implications if we don't do this?

Crashes will be no longer sent to the Firebase dashboard after November 15, 2020

The **Xamarin.Android.Crashlytics** nuget package was built with the old Firebase Crashlytics that based on Fabric SDK that is already deprecated. The new one (**Xamarin.Firebase.Crashlytics**) that mentioned here was built with the new official SDK for Android (version 17+). More information here: https://firebase.googleblog.com/2020/06/crashlytics-sdk-now-available.html

> Does this a simple change?

I hope so, I am going to use the use this new Nuget package soon, and also find the right one for iOS.

**Comment by codeanees** [comment]
Thanks a lot for the information @trinnguyen 

I see the **Xamarin.Firebase.Crashlytics** is still in preview state.  I would like Microsoft/Xamarin Team to push a stable release asap.  It is a really a priority right now as we are nearing November 15, 2020.  Please keep update this forum with the information related to this migration. Much helpful.

https://www.nuget.org/packages/Xamarin.Firebase.Crashlytics/117.0.0-preview02

**Comment by acuntex** [comment]
Please also consider possible implementation, testing and publish times.

Even if Microsoft releases a new version a few days before the dead line, there is no time to implement, test and then wait for Apple.
Plus: Users have to update, which can last even longer.

**Comment by sbkrishnan2506** [comment]
Hi,
When I tried to implement the Xamain.Firebase.Crashlytics 117preview02 version.
I got the below error in output window
E/FirebaseCrashlytics(29192): Failed to retrieve settings from https://firebase-settings.crashlytics.com/spi/v2/platforms/android/gmp/1:xxxxxxxx09xx:android:xxxxxb411b9cc2a51xxxxx/settings
Please let me know if any fix.

Thanks

**Comment by Mataboge** [comment]
@AmoseKumar24 your error is specific to Dagger, the missing method cannot be found on the dagger version that comes with nuget. You need to download the Dagger Nuget separately [here](https://github.com/xamarin/XamarinComponents/tree/master/Android/GoogleDagger) or search 'Xamarin.Google.Dagger' in the Nuget Package manager

**Comment by a-imai** [comment]
Hi,
I upgraded from the Fabrics SDK to the Firebase SDK using Xamarin.Firebase.Crashlytics 117.0.0-preview02.
And I summarized the procedure at that time in the document.
https://github.com/a-imai/XamarinCrashlyticsUpgradeSample

It also describes how I dealt with the `Failed to retrieve settings from ...` error.
I'm still asking Google a question. I will update it when I get a reply, but I can't expect much.

This's just a record I've tried, not a PERFECT procedure. Please note.
I hope it helps someone.

**Comment by jbtdevgit** [comment]
> 
> 
> Hi,
> I upgraded from the Fabrics SDK to the Firebase SDK using Xamarin.Firebase.Crashlytics 117.0.0-preview02.
> And I summarized the procedure at that time in the document.
> https://github.com/a-imai/XamarinCrashlyticsUpgradeSample
> 
> It also describes how I dealt with the `Failed to retrieve settings from ...` error.
> I'm still asking Google a question. I will update it when I get a reply, but I can't expect much.
> 
> This's just a record I've tried, not a PERFECT procedure. Please note.
> I hope it helps someone.

Hi @a-imai
Regarding Firebase.Crashlytics 117.0.0, is it a must to download the AndroidX package and its dependencies?

**Comment by a-imai** [comment]
Hi @jbtamaresgit ,
At least, I got the following error at build time after installing Xamarin.Firebase.Crashlytics.
```
Could not find 1 Android X assemblies, make sure to install the following NuGet packages:
 - Xamarin.AndroidX.AppCompat.AppCompatResources
You can also copy-and-paste the following snippet into your .csproj file:
  <PackageReference Include="Xamarin.AndroidX.AppCompat.AppCompatResources" Version="1.1.0.1" />
```
So I followed the instructions and copy-and-paste. It went well.
Originally, my project included the following packages. I don't know if it's related to Crashlytics.
- Xamarin.AndroidX.Leanback  1.0.0
- Xamarin.AndroidX.MediaRouter  1.1.0

**Comment by jbtdevgit** [comment]
> Hi @jbtamaresgit ,
> At least, I got the following error at build time after installing Xamarin.Firebase.Crashlytics.
> 
> ```
> Could not find 1 Android X assemblies, make sure to install the following NuGet packages:
>  - Xamarin.AndroidX.AppCompat.AppCompatResources
> You can also copy-and-paste the following snippet into your .csproj file:
>   <PackageReference Include="Xamarin.AndroidX.AppCompat.AppCompatResources" Version="1.1.0.1" />
> ```
> 
> So I followed the instructions and copy-and-paste. It went well.
> Originally, my project included the following packages. I don't know if it's related to Crashlytics.
> 
> * Xamarin.AndroidX.Leanback  1.0.0
> * Xamarin.AndroidX.MediaRouter  1.1.0

Hi @a-imai , 
Alright thanks, I will try the preview. Seems like there's no news regarding of a stable release of the package for now. So either make use of the preview or create a binding library for it. Nvm that, https://www.nuget.org/packages/Xamarin.Firebase.Crashlytics/ they just released the official version just now

**Comment by a-imai** [comment]
We are pleased that the official version has been released!
I've tried it out, and found that the steps in my document work fine.

**Comment by sbkrishnan2506** [comment]
Hi

I have tried with the latest version still the same issue, I couldn't see any crashes in the console
![image](https://user-images.githubusercontent.com/56611791/97220846-85b05a00-17a2-11eb-9f2b-e12256187351.png)

Below error in the output window.
10-26 16:31:29.036 I/FirebaseCrashlytics(10340): Initializing Crashlytics 17.0.0
10-26 16:31:29.075 I/FirebaseInitProvider(10340): FirebaseApp initialization successful

10-26 16:31:33.782 E/FirebaseInstanceId(10340): Failed to resolve target intent service, skipping classname enforcement
10-26 16:31:33.796 E/FirebaseInstanceId(10340): Error while delivering the message: ServiceIntent not found.

**Comment by jbtdevgit** [comment]
Hi @sbkrishnan2506 ,

You should ask this to [google firebase git issues](https://github.com/firebase/firebase-tools/issues) and post the logcat over there, they might help you better. For remedy, try to recreate and set up the application in the firebase, try to create a crash, and post the logcat. I've tried the crash in a device in release mode and not simulator - so this might be an issue for crashlytics not being able to send the reports using simulator. If you're using debug please refer to the [GoogleFirebaseDocsDebug](https://firebase.google.com/docs/crashlytics/test-implementation?authuser=0&platform=android#enable_debug_logging)

**Comment by Baptista** [comment]
hello,
Im getting this error 
**Java.Lang.RuntimeException:** 'Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.IllegalStateException: The Crashlytics build ID is missing. This occurs when Crashlytics tooling is absent from your app's build configuration. Please review Crashlytics onboarding instructions and ensure you have a valid Crashlytics account.'

And a create a new project just with this package and google-services.json

anyone have an a idea?

thks

**Comment by aandino-dev** [comment]
Hi @Baptista, 

Need to add com.crashlytics.android.build_id in Resources/values/strings.xml

https://github.com/a-imai/XamarinCrashlyticsUpgradeSample/tree/main#4-comcrashlyticsandroidbuild_id



> hello,
> Im getting this error
> **Java.Lang.RuntimeException:** 'Unable to get provider com.google.firebase.provider.FirebaseInitProvider: java.lang.IllegalStateException: The Crashlytics build ID is missing. This occurs when Crashlytics tooling is absent from your app's build configuration. Please review Crashlytics onboarding instructions and ensure you have a valid Crashlytics account.'
> 
> And a create a new project just with this package and google-services.json
> 
> anyone have an a idea?
> 
> thks

**Comment by Baptista** [comment]
thks it was that. 
its works with a new project i create from scratch.
but when i try it in my old project still have this issue:

Java.Lang.NoSuchMethodError: no static method "Lcom/google/firebase/crashlytics/FirebaseCrashlytics;.getInstance()Lcom/google/firebase/crashlytics/FirebaseCrashlytics;"

**Comment by Baptista** [comment]
In some fields after FirebaseApp.InitializeApp(this) , in FirebaseApp have this: 
Unable to cast object of type 'Mono.Debugger.Soft.PointerValue' to type 'Mono.Debugger.Soft.PrimitiveValue'.

anyone have this issues?

**Comment by sbkrishnan2506** [comment]
https://github.com/a-imai/XamarinCrashlyticsUpgradeSample

**Comment by troyanas** [comment]
@Baptista same here
@sbkrishnan2506 This Sample is great and I managed to solve all problems locally and it works for new project, but does not apply for old projects. still nothing is shown on Firebase dashboard. This is FirebaseCrashlytics log:
[firebase-crashlytics-log.txt](https://github.com/xamarin/XamarinComponents/files/5488420/firebase-crashlytics-log.txt)

**Comment by Baptista** [comment]
i solved my by removed multi-dex

**Comment by troyanas** [comment]
I will try to investigate it with sample app if that helps, but if turning it off on main app, it does not compile since it exceeds method limit

**Comment by a-imai** [comment]
Hi,
I updated my docs and changed it to use `com.google.firebase.crashlytics.mapping_file_id` instead of `com.crashlytics.android.build_id`.
https://github.com/a-imai/XamarinCrashlyticsUpgradeSample/blob/main/README.md#4-comgooglefirebasecrashlyticsmapping_file_id

`com.crashlytics.android.build_id` is deprecated.
https://github.com/xamarin/GooglePlayServicesComponents/issues/393#issuecomment-721753382

**Comment by troyanas** [comment]
Was receiving the following error:

`FirebaseCrashlytics: Crashlytics is handling uncaught exception "java.lang.NoSuchMethodError: No virtual method callTimeout(JLjava/util/concurrent/TimeUnit;)Lokhttp3/OkHttpClient$Builder; in class Lokhttp3/OkHttpClient$Builder; or its super classes (declaration of 'okhttp3.OkHttpClient$Builder' appears in /data/app/com.visma.admincontrol-o8ZilAnrNyJL1Cdgboj-AA==/base.apk!classes2.dex)" from thread com.google.firebase.crashlytics.startup1`

Solved after referencing OkHttp nuget.

`<PackageReference Include="Karamunting.Android.Square.OkHttp">
<Version>3.14.2</Version>
</PackageReference>
`

**Comment by padmasrisekar** [comment]
@troyanas Could anyone please provide the details, which version of Xamarin forms and Xamarin.iOS supports for firebase crashlytics update.

Thanks in Advance.

**Comment by trinnguyen** [comment]
Version 17.0.0 does not work for me. I created anther binding for version 17.1.1 and it works well. Checkout the Nuget and example here: https://github.com/trinnguyen/xamarin-bindings/tree/master/Firebase.Crashlytics

**Comment by aandino-dev** [comment]
There is a new commit for Xamarin.Firebase.Crashlytics 117.1.0 on https://github.com/xamarin/GooglePlayServicesComponents/tree/master

**Comment by aandino-dev** [comment]
A new version has been officially released 117.1.0 https://www.nuget.org/packages/Xamarin.Firebase.Crashlytics/117.1.0

**Comment by raghavendragrtally** [comment]
Not receiving crash logs,
In MainActivity i have just hardcoded  **FirebaseCrashlytics.Instance.Log("Error Log")** by this the app crashes but logs are not reported.
1. Is it mandatory install all the below supporting plugin along with 'Xamarin.Firebase.Craslytics'..?
Xamarin.Google.Dagger,Xamarin.Firebase.Messaging,Xamarin.Google.Android.DataTransport.TransportBackendCct,Xamarin.Google.Android.DataTransport.TransportRuntime(Not installed, as i didn't get any compile time error)
2. google-services.json is replaced with new, build action made 'GoogleServiceJson'
3. Stringe.xml     <string name="com.google.firebase.crashlytics.mapping_file_id">none</string>

Am i missing something..? 

I have followed all the steps, but still my crashlytics console have the badge '**As of November 16, we are only processing crashes from the Firebase Android SDK 17.0.0+. As a result, you might be seeing no new crashes in your dashboard. Learn More'**

**Comment by raghavendragrtally** [comment]
Hi

**Exisiting app:**
when i use ' FirebaseCrashlytics.Instance.SetCrashlyticsCollectionEnabled(true)' the app crashes with below error message.
_Error:_
[MonoDroid] java.lang.NoSuchMethodError: No virtual method get(Ljava/lang/Class;)Ljava/lang/Object; in class Lcom/google/firebase/FirebaseApp; or its super classes (declaration of 'com.google.firebase.FirebaseApp' appears in base.apk)
[MonoDroid] 	at com.google.firebase.crashlytics.FirebaseCrashlytics.getInstance(FirebaseCrashlytics.java:230)

Error2:
No virtual method get(Ljava/lang/Class;)Ljava/lang/Object; in class Lcom/google/firebase/FirebaseApp; or its super classes (declaration of 'com.google.firebase.FirebaseApp' appears in /data/app/com.***.**-lDWnhDBUIKVAwFGGDwd9KQ==/base.apk)

But same works in a new sample project.

**Comment by moljac** [comment]
@raghavendragrtally 
Check R8 (proguard) rules 1st.

If it works with new sample, then something in your project settings is not OK. Most lilkely using R8 vs proguard. R8 is more aggressive when optimizing, so it might remove some code.

**Comment by moljac** [comment]
Closing this one.

**Comment by raghavendragrtally** [comment]
Xamarin.Firebase.Messaging Version 120.2.4 was causing the problem. Xamarin.Firebase.Messaging, Update solved my issue.

**Comment by c-lamont** [comment]
I have everything up to date and was having this error.
@sasa-bobic answer resolved the issue for me, by adding the string resource
`<string name="com.google.firebase.crashlytics.mapping_file_id">none</string>`
