### ISSUE TITLE
Upgrade kotlin binding to 1.4.0

### ISSUE THREAD

**Issue by 4brunu** [xamarin/XamarinComponents#965]
Could you please upgrade the kotlin binding to 1.4.0?
Thanks

**Comment by mattleibow** [comment]
@antonioseric you have been working on all the Kotlin updates, so I just wanted to check to see if you have started on the v1.4 series?

No need to duplicate the work 😄

**Comment by antonioseric** [comment]
@mattleibow i didn't started with 1.4.0 i was thinking over weekend. If you don't have time i can do it :)

**Comment by antonioseric** [comment]
I also add PR for Kotlin 1.4.10 #978

**Comment by 4brunu** [comment]
That's awesome thanks 😊

**Comment by 4brunu** [comment]
@mattleibow could you please take a look at https://github.com/xamarin/XamarinComponents/pull/971 and https://github.com/xamarin/XamarinComponents/pull/978? Thanks 😊

**Comment by mattleibow** [comment]
Just letting everyone know that both v1.4 versions are out!

**Comment by 4brunu** [comment]
Thanks 😊
