### ISSUE TITLE
Update OkHttp binding to the new version 4.8.1 and 4.9.0

### ISSUE THREAD

**Issue by 4brunu** [xamarin/XamarinComponents#969]
Hi,
Could you please upgrade the OkHttp binding to the news versions 4.8.1 and 4.9.0?
Thanks

**Comment by tranb3r** [comment]
Could you please update OkHttp-UrlConnection to 4.8.1 as well ?

**Comment by 4brunu** [comment]
@antonioseric hey, first of all thanks for your amazing work with the PRs you opened with the new versions of moshi and OkHttp.
Could you help with this issue?
Thanks 🙂

**Comment by antonioseric** [comment]
@mattleibow can you merge and publish OkIO PRs so we have dependencies for this issue.
#975 #976 #977

**Comment by antonioseric** [comment]
Also #1009 which is dependency for OkHttp 4.9.0

**Comment by tranb3r** [comment]
I've published new versions, feel free to use it if like me you cannot wait for an "official" release from microsoft (#1010)
https://www.nuget.org/packages/Xamarin.SquareUp.OkHttp3/4.9.0
https://www.nuget.org/packages/Xamarin.SquareUp.OkHttp3.UrlConnection/4.9.0
https://www.nuget.org/packages/Xamarin.SquareUp.OkIO/2.9.0

**Comment by 4brunu** [comment]
@antonioseric now that https://github.com/xamarin/XamarinComponents/pull/1009 is merged and released, could you please update OkHttp to the last version?
Thanks 😊

**Comment by 4brunu** [comment]
@antonioseric thanks for creating the PRs to update the binding, I think now we can close this issue 👍
