### ISSUE TITLE
Update moshi binding with new versions 1.10.0 and 1.9.3

### ISSUE THREAD

**Issue by 4brunu** [xamarin/XamarinComponents#970]
Hi,
Could you please add the new versions of the moshi binding 1.10.0 and 1.9.3?
Thanks

**Comment by 4brunu** [comment]
@antonioseric hey, first of all thanks for the PRs you opened with the new versions of moshi.
I don't want to abuse your patience, but when you have some time, could you please also create a PR with the binding of 1.11.0?
Thanks 🙂

**Comment by 4brunu** [comment]
@mattleibow Thanks for merging https://github.com/xamarin/XamarinComponents/pull/997.
Could you please also release it?
Because it's not available yet here https://www.nuget.org/packages/Square.Moshi/
Thanks

**Comment by 4brunu** [comment]
@mattleibow could you please release moshi 1.11.0? Thanks

**Comment by 4brunu** [comment]
@moljac could you please release moshi 1.11.0 that was already merged? Thanks

**Comment by moljac** [comment]
Will try to ASAP

**Comment by 4brunu** [comment]
Thanks for your help, looking forward to it 😊

**Comment by 4brunu** [comment]
@moljac @mattleibow any news on this? 🙂

**Comment by moljac** [comment]
Notes to myself

https://www.nuget.org/packages/Square.Moshi/1.9.3

https://www.nuget.org/packages/Square.Moshi/1.10.0

1.11 must be published

**Comment by 4brunu** [comment]
@moljac any news on this? 🙂

**Comment by moljac** [comment]
@4brunu 
Nope. Had quake here, so not too productive over the holidays

**Comment by 4brunu** [comment]
Sorry to hear about that 😕

**Comment by moljac** [comment]
@4brunu 
Bruno no need to be sorry  - it was 2020. But thanks. 

Investigating why that was merged but never published. Most likely wrong tags

**Comment by moljac** [comment]
@4brunu 

Aren't those 1.9.3 ans 1.10.0?

https://www.nuget.org/packages/Square.Moshi/1.9.3

https://www.nuget.org/packages/Square.Moshi/1.10.0

They are pbulished

If you need 1.11.0 close this one and open new one please

**Comment by 4brunu** [comment]
Yes, but the version 1.11.0 was merged in https://github.com/xamarin/XamarinComponents/pull/997 and never got published to nuget.
I created https://github.com/xamarin/XamarinComponents/issues/1067 to track that issue.
