### ISSUE TITLE
When is EN API v2 (iOS) and v1.6 (Android) supported?

### ISSUE THREAD

**Issue by JanettHolst290490** [xamarin/XamarinComponents#991]
In a couple of weeks, we (Denmark) will need the support of 
IOS EN API V2
Android EN API V1.5 and V1.6

It looks like https://github.com/xamarin/XamarinComponents/pull/955 has been on hold for a while. What are the prospects of this ?

**Comment by mattleibow** [comment]
Hi @JanettHolst290490. Sorry for the very long wait. I just answered your questions on this : https://github.com/xamarin/XamarinComponents/pull/955#issuecomment-723326150

I will also be posting more details in the Teams channel either this weekend or Monday. But for now, we hope to release a version for use very soon. The code should be ready for testing.

I'll close for now.
